package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("EduInfSgmt")
public class PbcrsReportEduinfsgmt implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_EDUINFSGMT.EDUINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String EduInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_EDUINFSGMT.EDULEVEL
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("EduLevel")
	private String EduLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_EDUINFSGMT.ACADEGREE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("AcaDegree")
	private String AcaDegree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_EDUINFSGMT.EDUINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("EduInfoUpDate")
	private String EduInfoUpDate;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_EDUINFSGMT.EDUINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_EDUINFSGMT.EDUINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getEduInfSgmtSeqNo() {
		return EduInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_EDUINFSGMT.EDUINFSGMTSEQNO
	 * @param EduInfSgmtSeqNo  the value for PBCRS_REPORT_EDUINFSGMT.EDUINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setEduInfSgmtSeqNo(String EduInfSgmtSeqNo) {
		this.EduInfSgmtSeqNo = EduInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_EDUINFSGMT.EDULEVEL
	 * @return  the value of PBCRS_REPORT_EDUINFSGMT.EDULEVEL
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getEduLevel() {
		return EduLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_EDUINFSGMT.EDULEVEL
	 * @param EduLevel  the value for PBCRS_REPORT_EDUINFSGMT.EDULEVEL
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setEduLevel(String EduLevel) {
		this.EduLevel = EduLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_EDUINFSGMT.ACADEGREE
	 * @return  the value of PBCRS_REPORT_EDUINFSGMT.ACADEGREE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getAcaDegree() {
		return AcaDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_EDUINFSGMT.ACADEGREE
	 * @param AcaDegree  the value for PBCRS_REPORT_EDUINFSGMT.ACADEGREE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setAcaDegree(String AcaDegree) {
		this.AcaDegree = AcaDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_EDUINFSGMT.EDUINFOUPDATE
	 * @return  the value of PBCRS_REPORT_EDUINFSGMT.EDUINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getEduInfoUpDate() {
		return EduInfoUpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_EDUINFSGMT.EDUINFOUPDATE
	 * @param EduInfoUpDate  the value for PBCRS_REPORT_EDUINFSGMT.EDUINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setEduInfoUpDate(String EduInfoUpDate) {
		this.EduInfoUpDate = EduInfoUpDate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 8817203703860522091L;
}