package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("InFalMmbsInf")
public class PbcrsReportInfalmmbsinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4335860844540204837L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.INFALMMBSINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String InFalMmbsInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FamMemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FamMemCertType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FamMemCertNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.FAMREL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FamRel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.FAMRELAASSFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FamRelaAssFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfSurcCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INFALMMBSINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.INFALMMBSINFSEQNO
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.INFALMMBSINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInFalMmbsInfSeqNo() {
		return InFalMmbsInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.INFALMMBSINFSEQNO
	 * @param InFalMmbsInfSeqNo  the value for PBCRS_REPORT_INFALMMBSINF.INFALMMBSINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInFalMmbsInfSeqNo(String InFalMmbsInfSeqNo) {
		this.InFalMmbsInfSeqNo = InFalMmbsInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INFALMMBSINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.NAME
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getName() {
		return Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.NAME
	 * @param Name  the value for PBCRS_REPORT_INFALMMBSINF.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setName(String Name) {
		this.Name = Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.IDTYPE
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDType() {
		return IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.IDTYPE
	 * @param IDType  the value for PBCRS_REPORT_INFALMMBSINF.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDType(String IDType) {
		this.IDType = IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.IDNUM
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDNum() {
		return IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.IDNUM
	 * @param IDNum  the value for PBCRS_REPORT_INFALMMBSINF.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDNum(String IDNum) {
		this.IDNum = IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMNAME
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.FAMMEMNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFamMemName() {
		return FamMemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMNAME
	 * @param FamMemName  the value for PBCRS_REPORT_INFALMMBSINF.FAMMEMNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFamMemName(String FamMemName) {
		this.FamMemName = FamMemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTTYPE
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFamMemCertType() {
		return FamMemCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTTYPE
	 * @param FamMemCertType  the value for PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFamMemCertType(String FamMemCertType) {
		this.FamMemCertType = FamMemCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTNUM
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFamMemCertNum() {
		return FamMemCertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTNUM
	 * @param FamMemCertNum  the value for PBCRS_REPORT_INFALMMBSINF.FAMMEMCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFamMemCertNum(String FamMemCertNum) {
		this.FamMemCertNum = FamMemCertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMREL
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.FAMREL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFamRel() {
		return FamRel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMREL
	 * @param FamRel  the value for PBCRS_REPORT_INFALMMBSINF.FAMREL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFamRel(String FamRel) {
		this.FamRel = FamRel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMRELAASSFLAG
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.FAMRELAASSFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFamRelaAssFlag() {
		return FamRelaAssFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.FAMRELAASSFLAG
	 * @param FamRelaAssFlag  the value for PBCRS_REPORT_INFALMMBSINF.FAMRELAASSFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFamRelaAssFlag(String FamRelaAssFlag) {
		this.FamRelaAssFlag = FamRelaAssFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.INFSURCCODE
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfSurcCode() {
		return InfSurcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.INFSURCCODE
	 * @param InfSurcCode  the value for PBCRS_REPORT_INFALMMBSINF.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfSurcCode(String InfSurcCode) {
		this.InfSurcCode = InfSurcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INFALMMBSINF.RPTDATE
	 * @return  the value of PBCRS_REPORT_INFALMMBSINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDate() {
		return RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INFALMMBSINF.RPTDATE
	 * @param RptDate  the value for PBCRS_REPORT_INFALMMBSINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDate(String RptDate) {
		this.RptDate = RptDate;
	}
}