package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("GuarAcctBsSgmt")
public class PbcrsReportEnguaracctbssgmt implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3468390624363236740L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuarAcctBsSgmtSeqNo;
	
	@XStreamOmitField
	private String ReportFlag;
	
	@XStreamOmitField
	private String IsDel;
	@XStreamOmitField
	private String SourceSys;

	@XStreamOmitField
	private String orgCode;
	
	
	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.INFRECTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String AcctType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTCODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String AcctCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String RptDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATECODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String RptDateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.NAME
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.IDTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String IDType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.IDNUM
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String IDNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENGUARACCTBSSGMT.MNGMTORGCODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String MngmtOrgCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuarAcctBsSgmtSeqNo() {
        return GuarAcctBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
     *
     * @param GuarAcctBsSgmtSeqNo the value for PBCRS_REPORT_ENGUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuarAcctBsSgmtSeqNo(String GuarAcctBsSgmtSeqNo) {
        this.GuarAcctBsSgmtSeqNo = GuarAcctBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.INFRECTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENGUARACCTBSSGMT.INFRECTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTTYPE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getAcctType() {
        return AcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTTYPE
     *
     * @param AcctType the value for PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setAcctType(String AcctType) {
        this.AcctType = AcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTCODE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTCODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getAcctCode() {
        return AcctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTCODE
     *
     * @param AcctCode the value for PBCRS_REPORT_ENGUARACCTBSSGMT.ACCTCODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setAcctCode(String AcctCode) {
        this.AcctCode = AcctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getRptDate() {
        return RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATE
     *
     * @param RptDate the value for PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setRptDate(String RptDate) {
        this.RptDate = RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATECODE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATECODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getRptDateCode() {
        return RptDateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATECODE
     *
     * @param RptDateCode the value for PBCRS_REPORT_ENGUARACCTBSSGMT.RPTDATECODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setRptDateCode(String RptDateCode) {
        this.RptDateCode = RptDateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.NAME
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.NAME
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getName() {
        return Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.NAME
     *
     * @param Name the value for PBCRS_REPORT_ENGUARACCTBSSGMT.NAME
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.IDTYPE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.IDTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getIDType() {
        return IDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.IDTYPE
     *
     * @param IDType the value for PBCRS_REPORT_ENGUARACCTBSSGMT.IDTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setIDType(String IDType) {
        this.IDType = IDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.IDNUM
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.IDNUM
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getIDNum() {
        return IDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.IDNUM
     *
     * @param IDNum the value for PBCRS_REPORT_ENGUARACCTBSSGMT.IDNUM
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setIDNum(String IDNum) {
        this.IDNum = IDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.MNGMTORGCODE
     *
     * @return the value of PBCRS_REPORT_ENGUARACCTBSSGMT.MNGMTORGCODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getMngmtOrgCode() {
        return MngmtOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENGUARACCTBSSGMT.MNGMTORGCODE
     *
     * @param MngmtOrgCode the value for PBCRS_REPORT_ENGUARACCTBSSGMT.MNGMTORGCODE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setMngmtOrgCode(String MngmtOrgCode) {
        this.MngmtOrgCode = MngmtOrgCode;
    }

	public String getIsDel() {
		return IsDel;
	}

	public void setIsDel(String isDel) {
		IsDel = isDel;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}
    
    
}