package com.hkbank.pbcrs.model;

import java.util.Date;

public class PbcrsReportLog {

	
    /**LOG_STATE_ERR:E：错误*/
    public static final String LOG_STATE_ERR="E";
    /**LOG_STATE_FIN:F： 已完成*/
    public static final String LOG_STATE_FIN="F";
    /**STATE_NORMAL:P： 过程中*/
    public static final String LOG_STATE_PROC="P";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.LOG_NBR
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private Integer logNbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.ETL_TX_DATE
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private Date etlTxDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.REPORT_NAME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private String reportName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.LOG_STATE
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private String logState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.LOG_INFO
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private String logInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.START_TIME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_LOG.END_TIME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	private Date endTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.LOG_NBR
	 * @return  the value of PBCRS_REPORT_LOG.LOG_NBR
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public Integer getLogNbr() {
		return logNbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.LOG_NBR
	 * @param logNbr  the value for PBCRS_REPORT_LOG.LOG_NBR
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setLogNbr(Integer logNbr) {
		this.logNbr = logNbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.ETL_TX_DATE
	 * @return  the value of PBCRS_REPORT_LOG.ETL_TX_DATE
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public Date getEtlTxDate() {
		return etlTxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.ETL_TX_DATE
	 * @param etlTxDate  the value for PBCRS_REPORT_LOG.ETL_TX_DATE
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setEtlTxDate(Date etlTxDate) {
		this.etlTxDate = etlTxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.REPORT_NAME
	 * @return  the value of PBCRS_REPORT_LOG.REPORT_NAME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public String getReportName() {
		return reportName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.REPORT_NAME
	 * @param reportName  the value for PBCRS_REPORT_LOG.REPORT_NAME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.LOG_STATE
	 * @return  the value of PBCRS_REPORT_LOG.LOG_STATE
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public String getLogState() {
		return logState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.LOG_STATE
	 * @param logState  the value for PBCRS_REPORT_LOG.LOG_STATE
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setLogState(String logState) {
		this.logState = logState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.LOG_INFO
	 * @return  the value of PBCRS_REPORT_LOG.LOG_INFO
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public String getLogInfo() {
		return logInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.LOG_INFO
	 * @param logInfo  the value for PBCRS_REPORT_LOG.LOG_INFO
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setLogInfo(String logInfo) {
		this.logInfo = logInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.START_TIME
	 * @return  the value of PBCRS_REPORT_LOG.START_TIME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.START_TIME
	 * @param startTime  the value for PBCRS_REPORT_LOG.START_TIME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_LOG.END_TIME
	 * @return  the value of PBCRS_REPORT_LOG.END_TIME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_LOG.END_TIME
	 * @param endTime  the value for PBCRS_REPORT_LOG.END_TIME
	 * @mbggenerated  Mon Jul 22 10:35:46 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
}