package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("InstitutionBalanceSheet")
public class PbcrsReportInsbalshe {
	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	@XStreamOmitField
	private String InstitutionBSSeqNo;

	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_INSBALSHE.INSTITUTIONBSBSSGMTSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	@XStreamOmitField
	private String InstitutionBSBsSgmtSeqNo;

	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSGMTSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	@XStreamOmitField
	private String InstitutionBSSgmtSeqNo;
	
	
	@XStreamAlias("InstitutionBalanceSheetBsSgmt")
	private PbcrsReportInsbalshebssgmt InstitutionBalanceSheetBsSgmt;
	@XStreamAlias("InstitutionBalanceSheetSgmt")
	private PbcrsReportInsbalshesgmt InstitutionBalanceSheetSgmt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSEQNO
	 * 
	 * @return the value of PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	public String getInstitutionBSSeqNo() {
		return InstitutionBSSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSEQNO
	 * 
	 * @param InstitutionBSSeqNo
	 *            the value for PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	public void setInstitutionBSSeqNo(String InstitutionBSSeqNo) {
		this.InstitutionBSSeqNo = InstitutionBSSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_INSBALSHE.INSTITUTIONBSBSSGMTSEQNO
	 * 
	 * @return the value of PBCRS_REPORT_INSBALSHE.INSTITUTIONBSBSSGMTSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	public String getInstitutionBSBsSgmtSeqNo() {
		return InstitutionBSBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * PBCRS_REPORT_INSBALSHE.INSTITUTIONBSBSSGMTSEQNO
	 * 
	 * @param InstitutionBSBsSgmtSeqNo
	 *            the value for PBCRS_REPORT_INSBALSHE.INSTITUTIONBSBSSGMTSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	public void setInstitutionBSBsSgmtSeqNo(String InstitutionBSBsSgmtSeqNo) {
		this.InstitutionBSBsSgmtSeqNo = InstitutionBSBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSGMTSEQNO
	 * 
	 * @return the value of PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSGMTSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	public String getInstitutionBSSgmtSeqNo() {
		return InstitutionBSSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSGMTSEQNO
	 * 
	 * @param InstitutionBSSgmtSeqNo
	 *            the value for PBCRS_REPORT_INSBALSHE.INSTITUTIONBSSGMTSEQNO
	 * 
	 * @mbggenerated Mon Mar 18 10:55:37 CST 2019
	 */
	public void setInstitutionBSSgmtSeqNo(String InstitutionBSSgmtSeqNo) {
		this.InstitutionBSSgmtSeqNo = InstitutionBSSgmtSeqNo;
	}

	public PbcrsReportInsbalshebssgmt getInstitutionBalanceSheetBsSgmt() {
		return InstitutionBalanceSheetBsSgmt;
	}

	public void setInstitutionBalanceSheetBsSgmt(
			PbcrsReportInsbalshebssgmt institutionBalanceSheetBsSgmt) {
		InstitutionBalanceSheetBsSgmt = institutionBalanceSheetBsSgmt;
	}

	public PbcrsReportInsbalshesgmt getInstitutionBalanceSheetSgmt() {
		return InstitutionBalanceSheetSgmt;
	}

	public void setInstitutionBalanceSheetSgmt(
			PbcrsReportInsbalshesgmt institutionBalanceSheetSgmt) {
		InstitutionBalanceSheetSgmt = institutionBalanceSheetSgmt;
	}
	
}