package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("GuarRltRepymtInfSgmt")
public class PbcrsReportGuarltrepinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5017043066837426307L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.GUARRLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String GuarRltRepymtInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.LOANAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String LoanAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.REPAYPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RepayPrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FiveCate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FiveCateAdjDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.RIEX
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RiEx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.COMPADVFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CompAdvFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARLTREPINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CloseDate;

	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.GUARRLTREPYMTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.GUARRLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuarRltRepymtInfSgmtSeqNo() {
		return GuarRltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.GUARRLTREPYMTINFSGMTSEQNO
	 * @param GuarRltRepymtInfSgmtSeqNo  the value for PBCRS_REPORT_GUARLTREPINFSGMT.GUARRLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuarRltRepymtInfSgmtSeqNo(String GuarRltRepymtInfSgmtSeqNo) {
		this.GuarRltRepymtInfSgmtSeqNo = GuarRltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.ACCTSTATUS
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctStatus() {
		return AcctStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.ACCTSTATUS
	 * @param AcctStatus  the value for PBCRS_REPORT_GUARLTREPINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctStatus(String AcctStatus) {
		this.AcctStatus = AcctStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.LOANAMT
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.LOANAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getLoanAmt() {
		return LoanAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.LOANAMT
	 * @param LoanAmt  the value for PBCRS_REPORT_GUARLTREPINFSGMT.LOANAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setLoanAmt(String LoanAmt) {
		this.LoanAmt = LoanAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.REPAYPRD
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.REPAYPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRepayPrd() {
		return RepayPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.REPAYPRD
	 * @param RepayPrd  the value for PBCRS_REPORT_GUARLTREPINFSGMT.REPAYPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRepayPrd(String RepayPrd) {
		this.RepayPrd = RepayPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATE
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFiveCate() {
		return FiveCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATE
	 * @param FiveCate  the value for PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFiveCate(String FiveCate) {
		this.FiveCate = FiveCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATEADJDATE
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFiveCateAdjDate() {
		return FiveCateAdjDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATEADJDATE
	 * @param FiveCateAdjDate  the value for PBCRS_REPORT_GUARLTREPINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFiveCateAdjDate(String FiveCateAdjDate) {
		this.FiveCateAdjDate = FiveCateAdjDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.RIEX
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.RIEX
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRiEx() {
		return RiEx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.RIEX
	 * @param RiEx  the value for PBCRS_REPORT_GUARLTREPINFSGMT.RIEX
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRiEx(String RiEx) {
		this.RiEx = RiEx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.COMPADVFLAG
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.COMPADVFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCompAdvFlag() {
		return CompAdvFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.COMPADVFLAG
	 * @param CompAdvFlag  the value for PBCRS_REPORT_GUARLTREPINFSGMT.COMPADVFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCompAdvFlag(String CompAdvFlag) {
		this.CompAdvFlag = CompAdvFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.CLOSEDATE
	 * @return  the value of PBCRS_REPORT_GUARLTREPINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCloseDate() {
		return CloseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARLTREPINFSGMT.CLOSEDATE
	 * @param CloseDate  the value for PBCRS_REPORT_GUARLTREPINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCloseDate(String CloseDate) {
		this.CloseDate = CloseDate;
	}
}