package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("MmbInf")
public class PbcrsReportEnbasinfmmbinf {
	private static final long serialVersionUID = 3480189331608785345L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFMMBINF.MNMMBINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
	@XStreamOmitField
    private String MnMmbInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFMMBINF.MMBINFSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
	@XStreamOmitField
    private String MmbInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFMMBINF.MMBALIAS
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String MmbAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFMMBINF.MMBIDTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String MmbIDType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFMMBINF.MMBIDNUM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String MmbIDNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFMMBINF.MMBPSTN
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String MmbPstn;
    
    private String MnMmbInfoUpDate;
    

    public String getMnMmbInfoUpDate() {
		return MnMmbInfoUpDate;
	}

	public void setMnMmbInfoUpDate(String mnMmbInfoUpDate) {
		MnMmbInfoUpDate = mnMmbInfoUpDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MNMMBINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENBASINFMMBINF.MNMMBINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    
    @XStreamOmitField
    private String ReportFlag;
    
    public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MNMMBINFSGMTSEQNO
     *
     * @param MnMmbInfSgmtSeqNo the value for PBCRS_REPORT_ENBASINFMMBINF.MNMMBINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */




	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ENBASINFMMBINF.MMBINFSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getMmbInfSeqNo() {
        return MmbInfSeqNo;
    }





	public String getMnMmbInfSgmtSeqNo() {
		return MnMmbInfSgmtSeqNo;
	}

	public void setMnMmbInfSgmtSeqNo(String mnMmbInfSgmtSeqNo) {
		MnMmbInfSgmtSeqNo = mnMmbInfSgmtSeqNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBINFSEQNO
     *
     * @param MmbInfSeqNo the value for PBCRS_REPORT_ENBASINFMMBINF.MMBINFSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setMmbInfSeqNo(String MmbInfSeqNo) {
        this.MmbInfSeqNo = MmbInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBALIAS
     *
     * @return the value of PBCRS_REPORT_ENBASINFMMBINF.MMBALIAS
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getMmbAlias() {
        return MmbAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBALIAS
     *
     * @param MmbAlias the value for PBCRS_REPORT_ENBASINFMMBINF.MMBALIAS
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setMmbAlias(String MmbAlias) {
        this.MmbAlias = MmbAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBIDTYPE
     *
     * @return the value of PBCRS_REPORT_ENBASINFMMBINF.MMBIDTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getMmbIDType() {
        return MmbIDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBIDTYPE
     *
     * @param MmbIDType the value for PBCRS_REPORT_ENBASINFMMBINF.MMBIDTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setMmbIDType(String MmbIDType) {
        this.MmbIDType = MmbIDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBIDNUM
     *
     * @return the value of PBCRS_REPORT_ENBASINFMMBINF.MMBIDNUM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getMmbIDNum() {
        return MmbIDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBIDNUM
     *
     * @param MmbIDNum the value for PBCRS_REPORT_ENBASINFMMBINF.MMBIDNUM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setMmbIDNum(String MmbIDNum) {
        this.MmbIDNum = MmbIDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBPSTN
     *
     * @return the value of PBCRS_REPORT_ENBASINFMMBINF.MMBPSTN
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getMmbPstn() {
        return MmbPstn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFMMBINF.MMBPSTN
     *
     * @param MmbPstn the value for PBCRS_REPORT_ENBASINFMMBINF.MMBPSTN
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setMmbPstn(String MmbPstn) {
        this.MmbPstn = MmbPstn;
    }
}