package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;


@XStreamAlias("InCtrctDel")
public class PbcrsReportInctrctdel implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4228224388054012506L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTDEL.INCTRCTDELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InCtrctDelSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTDEL.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTDEL.DELRECCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelRecCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTDEL.DELSGMTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelSgmtCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTDEL.DELSTARTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTDEL.DELENDDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelEndDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTDEL.INCTRCTDELSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRCTDEL.INCTRCTDELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInCtrctDelSeqNo() {
		return InCtrctDelSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTDEL.INCTRCTDELSEQNO
	 * @param InCtrctDelSeqNo  the value for PBCRS_REPORT_INCTRCTDEL.INCTRCTDELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInCtrctDelSeqNo(String InCtrctDelSeqNo) {
		this.InCtrctDelSeqNo = InCtrctDelSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTDEL.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INCTRCTDEL.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTDEL.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INCTRCTDEL.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTDEL.DELRECCODE
	 * @return  the value of PBCRS_REPORT_INCTRCTDEL.DELRECCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelRecCode() {
		return DelRecCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTDEL.DELRECCODE
	 * @param DelRecCode  the value for PBCRS_REPORT_INCTRCTDEL.DELRECCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelRecCode(String DelRecCode) {
		this.DelRecCode = DelRecCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTDEL.DELSGMTCODE
	 * @return  the value of PBCRS_REPORT_INCTRCTDEL.DELSGMTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelSgmtCode() {
		return DelSgmtCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTDEL.DELSGMTCODE
	 * @param DelSgmtCode  the value for PBCRS_REPORT_INCTRCTDEL.DELSGMTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelSgmtCode(String DelSgmtCode) {
		this.DelSgmtCode = DelSgmtCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTDEL.DELSTARTDATE
	 * @return  the value of PBCRS_REPORT_INCTRCTDEL.DELSTARTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelStartDate() {
		return DelStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTDEL.DELSTARTDATE
	 * @param DelStartDate  the value for PBCRS_REPORT_INCTRCTDEL.DELSTARTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelStartDate(String DelStartDate) {
		this.DelStartDate = DelStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTDEL.DELENDDATE
	 * @return  the value of PBCRS_REPORT_INCTRCTDEL.DELENDDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelEndDate() {
		return DelEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTDEL.DELENDDATE
	 * @param DelEndDate  the value for PBCRS_REPORT_INCTRCTDEL.DELENDDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelEndDate(String DelEndDate) {
		this.DelEndDate = DelEndDate;
	}
}