package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("RedncInfSgmt")
public class PbcrsReportIncinfsgmt implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCINFSGMT.INCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String IncInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCINFSGMT.ANNLINC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("AnnlInc")
	private String AnnlInc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCINFSGMT.TAXINCOME
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("TaxIncome")
	private String TaxIncome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCINFSGMT.INCINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("IncInfoUpDate")
	private String IncInfoUpDate;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCINFSGMT.INCINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INCINFSGMT.INCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getIncInfSgmtSeqNo() {
		return IncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCINFSGMT.INCINFSGMTSEQNO
	 * @param IncInfSgmtSeqNo  the value for PBCRS_REPORT_INCINFSGMT.INCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setIncInfSgmtSeqNo(String IncInfSgmtSeqNo) {
		this.IncInfSgmtSeqNo = IncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCINFSGMT.ANNLINC
	 * @return  the value of PBCRS_REPORT_INCINFSGMT.ANNLINC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getAnnlInc() {
		return AnnlInc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCINFSGMT.ANNLINC
	 * @param AnnlInc  the value for PBCRS_REPORT_INCINFSGMT.ANNLINC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setAnnlInc(String AnnlInc) {
		this.AnnlInc = AnnlInc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCINFSGMT.TAXINCOME
	 * @return  the value of PBCRS_REPORT_INCINFSGMT.TAXINCOME
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getTaxIncome() {
		return TaxIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCINFSGMT.TAXINCOME
	 * @param TaxIncome  the value for PBCRS_REPORT_INCINFSGMT.TAXINCOME
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setTaxIncome(String TaxIncome) {
		this.TaxIncome = TaxIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCINFSGMT.INCINFOUPDATE
	 * @return  the value of PBCRS_REPORT_INCINFSGMT.INCINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getIncInfoUpDate() {
		return IncInfoUpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCINFSGMT.INCINFOUPDATE
	 * @param IncInfoUpDate  the value for PBCRS_REPORT_INCINFSGMT.INCINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setIncInfoUpDate(String IncInfoUpDate) {
		this.IncInfoUpDate = IncInfoUpDate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 4876363399229212631L;
}