package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;


@XStreamAlias("InSecAcctMdfc")
public class PbcrsReportInsecacctmdfc implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5474700418658620859L;
	
	@XStreamAlias("BsSgmt")
	private PbcrsReportInsecaccmdfbssgmt InSecAccMdfBsSgmt;
	
	@XStreamAlias("MdfcSgmt")
	private PbcrsReportInsecaccmdfmdsgmt InSecAccMdfMdSgmt;

	public PbcrsReportInsecaccmdfbssgmt getInSecAccMdfBsSgmt() {
		return InSecAccMdfBsSgmt;
	}

	public void setInSecAccMdfBsSgmt(PbcrsReportInsecaccmdfbssgmt inSecAccMdfBsSgmt) {
		InSecAccMdfBsSgmt = inSecAccMdfBsSgmt;
	}

	public PbcrsReportInsecaccmdfmdsgmt getInSecAccMdfMdSgmt() {
		return InSecAccMdfMdSgmt;
	}

	public void setInSecAccMdfMdSgmt(PbcrsReportInsecaccmdfmdsgmt inSecAccMdfMdSgmt) {
		InSecAccMdfMdSgmt = inSecAccMdfMdSgmt;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTMDFC.INSECACCTMDFCSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InSecAcctMdfcSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTMDFC.BSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String BsSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTMDFC.MDFCSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String MdfcSgmtSeqNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTMDFC.INSECACCTMDFCSEQNO
	 * @return  the value of PBCRS_REPORT_INSECACCTMDFC.INSECACCTMDFCSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInSecAcctMdfcSeqNo() {
		return InSecAcctMdfcSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTMDFC.INSECACCTMDFCSEQNO
	 * @param InSecAcctMdfcSeqNo  the value for PBCRS_REPORT_INSECACCTMDFC.INSECACCTMDFCSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInSecAcctMdfcSeqNo(String InSecAcctMdfcSeqNo) {
		this.InSecAcctMdfcSeqNo = InSecAcctMdfcSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTMDFC.BSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INSECACCTMDFC.BSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getBsSgmtSeqNo() {
		return BsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTMDFC.BSSGMTSEQNO
	 * @param BsSgmtSeqNo  the value for PBCRS_REPORT_INSECACCTMDFC.BSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setBsSgmtSeqNo(String BsSgmtSeqNo) {
		this.BsSgmtSeqNo = BsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTMDFC.MDFCSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INSECACCTMDFC.MDFCSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMdfcSgmtSeqNo() {
		return MdfcSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTMDFC.MDFCSGMTSEQNO
	 * @param MdfcSgmtSeqNo  the value for PBCRS_REPORT_INSECACCTMDFC.MDFCSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMdfcSgmtSeqNo(String MdfcSgmtSeqNo) {
		this.MdfcSgmtSeqNo = MdfcSgmtSeqNo;
	}
}