package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("InAcctMdfc")
public class PbcrsReportInacctmdfc implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7541200524770637233L;
	
	@XStreamAlias("BsSgmt")
	private PbcrsReportInacctmdfcbssgmt InAcctMdfcBsSgmt;
	
	@XStreamAlias("MdfcSgmt")
	private PbcrsReportInaccmdfmdfsgmt InAccMdfMdfSgmt;

	public PbcrsReportInacctmdfcbssgmt getInAcctMdfcBsSgmt() {
		return InAcctMdfcBsSgmt;
	}

	public void setInAcctMdfcBsSgmt(PbcrsReportInacctmdfcbssgmt inAcctMdfcBsSgmt) {
		InAcctMdfcBsSgmt = inAcctMdfcBsSgmt;
	}

	public PbcrsReportInaccmdfmdfsgmt getInAccMdfMdfSgmt() {
		return InAccMdfMdfSgmt;
	}

	public void setInAccMdfMdfSgmt(PbcrsReportInaccmdfmdfsgmt inAccMdfMdfSgmt) {
		InAccMdfMdfSgmt = inAccMdfMdfSgmt;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTMDFC.INACCTMDFCSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String InAcctMdfcSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTMDFC.BSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String MdfcSgmtCode;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTMDFC.INACCTMDFCSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTMDFC.INACCTMDFCSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInAcctMdfcSeqNo() {
		return InAcctMdfcSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTMDFC.INACCTMDFCSEQNO
	 * @param InAcctMdfcSeqNo  the value for PBCRS_REPORT_INACCTMDFC.INACCTMDFCSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInAcctMdfcSeqNo(String InAcctMdfcSeqNo) {
		this.InAcctMdfcSeqNo = InAcctMdfcSeqNo;
	}

	public String getMdfcSgmtCode() {
		return MdfcSgmtCode;
	}

	public void setMdfcSgmtCode(String mdfcSgmtCode) {
		MdfcSgmtCode = mdfcSgmtCode;
	}

	
}