package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("MdfcSgmt")
public class PbcrsReportEnctrinfmdfsgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
	@XStreamOmitField
    private String MdfcSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
	@XStreamOmitField
    private String MdfcSgmtDetialSeqNo;
    /**
     * 根据实际需要更改的段传入
     */
    @XStreamImplicit
    private List<?> MdfSgmtList;
    
	@XStreamAlias("CtrctBsSgmt")
	private PbcrsReportEnctrctbssgmt CtrctBsSgmt;
//	@XStreamAlias("CtrctCertRelSgmt")
//	private PbcrsReportEnctrcerrelsgmt CtrctCertRelSgmt;
	@XStreamAlias("CreditLimSgmt")
	private PbcrsReportEncreditlimsgmt CreditLimSgmt;

    public PbcrsReportEnctrctbssgmt getCtrctBsSgmt() {
		return CtrctBsSgmt;
	}

	public void setCtrctBsSgmt(PbcrsReportEnctrctbssgmt ctrctBsSgmt) {
		CtrctBsSgmt = ctrctBsSgmt;
	}

	public PbcrsReportEncreditlimsgmt getCreditLimSgmt() {
		return CreditLimSgmt;
	}

	public void setCreditLimSgmt(PbcrsReportEncreditlimsgmt creditLimSgmt) {
		CreditLimSgmt = creditLimSgmt;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    public String getMdfcSgmtSeqNo() {
        return MdfcSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTSEQNO
     *
     * @param MdfcSgmtSeqNo the value for PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    public void setMdfcSgmtSeqNo(String MdfcSgmtSeqNo) {
        this.MdfcSgmtSeqNo = MdfcSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    public String getMdfcSgmtDetialSeqNo() {
        return MdfcSgmtDetialSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @param MdfcSgmtDetialSeqNo the value for PBCRS_REPORT_ENCTRINFMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    public void setMdfcSgmtDetialSeqNo(String MdfcSgmtDetialSeqNo) {
        this.MdfcSgmtDetialSeqNo = MdfcSgmtDetialSeqNo;
    }

	public List<?> getMdfSgmtList() {
		return MdfSgmtList;
	}

	public void setMdfSgmtList(List<?> mdfSgmtList) {
		MdfSgmtList = mdfSgmtList;
	}
    
}