package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("MdfcSgmt")
public class PbcrsReportEnsecaccmdfsgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:18:18 CST 2019
     */
	@XStreamOmitField
    private String MdfcSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @mbggenerated Fri Mar 15 11:18:18 CST 2019
     */
	@XStreamOmitField
    private String MdfcSgmtDetialSeqNo;
    
    /**
     * 企业授信协议更正请求记录信息 因为无法确定修改的段所以用一个通用的list集合接收
     */
   @XStreamImplicit
    private List<?> MdfcSgmtDetial;
   
	@XStreamAlias("GuarAcctBsSgmt")
	private PbcrsReportEnguaracctbssgmt GuarAcctBsSgmt;
	@XStreamAlias("GuarAcctBsInfSgmt")
	private PbcrsReportEnguaaccbsinfsgmt GuarAcctBsInfSgmt;
	@XStreamAlias("RltRepymtInfSgmt")
	private PbcrsReportGserltrepinfsgmt RltRepymtInfSgmt;
//	@XStreamAlias("GuarMotgaCltalCtrctInfSgmt")
//	private PbcrsReportGuamotcltctrsgmt GuarMotgaCltalCtrctInfSgmt;
	@XStreamAlias("GuarAcctCredSgmt")
	private PbcrsReportGuaracctcredsgmt GuarAcctCredSgmt;
	@XStreamAlias("GuarRltRepymtInfSgmt")
	private PbcrsReportGuarltrepinfsgmt GuarRltRepymtInfSgmt;
	
    public PbcrsReportEnguaracctbssgmt getGuarAcctBsSgmt() {
		return GuarAcctBsSgmt;
	}

	public void setGuarAcctBsSgmt(PbcrsReportEnguaracctbssgmt guarAcctBsSgmt) {
		GuarAcctBsSgmt = guarAcctBsSgmt;
	}

	public PbcrsReportEnguaaccbsinfsgmt getGuarAcctBsInfSgmt() {
		return GuarAcctBsInfSgmt;
	}

	public void setGuarAcctBsInfSgmt(PbcrsReportEnguaaccbsinfsgmt guarAcctBsInfSgmt) {
		GuarAcctBsInfSgmt = guarAcctBsInfSgmt;
	}

	public PbcrsReportGserltrepinfsgmt getRltRepymtInfSgmt() {
		return RltRepymtInfSgmt;
	}

	public void setRltRepymtInfSgmt(PbcrsReportGserltrepinfsgmt rltRepymtInfSgmt) {
		RltRepymtInfSgmt = rltRepymtInfSgmt;
	}

	public PbcrsReportGuaracctcredsgmt getGuarAcctCredSgmt() {
		return GuarAcctCredSgmt;
	}

	public void setGuarAcctCredSgmt(PbcrsReportGuaracctcredsgmt guarAcctCredSgmt) {
		GuarAcctCredSgmt = guarAcctCredSgmt;
	}

	public PbcrsReportGuarltrepinfsgmt getGuarRltRepymtInfSgmt() {
		return GuarRltRepymtInfSgmt;
	}

	public void setGuarRltRepymtInfSgmt(
			PbcrsReportGuarltrepinfsgmt guarRltRepymtInfSgmt) {
		GuarRltRepymtInfSgmt = guarRltRepymtInfSgmt;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:18:18 CST 2019
     */
    public String getMdfcSgmtSeqNo() {
        return MdfcSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTSEQNO
     *
     * @param MdfcSgmtSeqNo the value for PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:18:18 CST 2019
     */
    public void setMdfcSgmtSeqNo(String MdfcSgmtSeqNo) {
        this.MdfcSgmtSeqNo = MdfcSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @mbggenerated Fri Mar 15 11:18:18 CST 2019
     */
    public String getMdfcSgmtDetialSeqNo() {
        return MdfcSgmtDetialSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @param MdfcSgmtDetialSeqNo the value for PBCRS_REPORT_ENSECACCMDFSGMT.MDFCSGMTDETIALSEQNO
     *
     * @mbggenerated Fri Mar 15 11:18:18 CST 2019
     */
    public void setMdfcSgmtDetialSeqNo(String MdfcSgmtDetialSeqNo) {
        this.MdfcSgmtDetialSeqNo = MdfcSgmtDetialSeqNo;
    }

	public List<?> getMdfcSgmtDetial() {
		return MdfcSgmtDetial;
	}

	public void setMdfcSgmtDetial(List<?> mdfcSgmtDetial) {
		MdfcSgmtDetial = mdfcSgmtDetial;
	}
    
}