package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("RedncInfSgmt")
public class PbcrsReportRedncinfsgmt implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.REDNCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String RedncInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.RESISTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("ResiStatus")
	private String ResiStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.RESIADDR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("ResiAddr")
	private String ResiAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.RESIPC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("ResiPc")
	private String ResiPc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.RESIDIST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("ResiDist")
	private String ResiDist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.HOMETEL
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("HomeTel")
	private String HomeTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_REDNCINFSGMT.RESIINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("ResiInfoUpDate")
	private String ResiInfoUpDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.REDNCINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.REDNCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	public String getRedncInfSgmtSeqNo() {
		return RedncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.REDNCINFSGMTSEQNO
	 * @param RedncInfSgmtSeqNo  the value for PBCRS_REPORT_REDNCINFSGMT.REDNCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setRedncInfSgmtSeqNo(String RedncInfSgmtSeqNo) {
		this.RedncInfSgmtSeqNo = RedncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESISTATUS
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.RESISTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getResiStatus() {
		return ResiStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESISTATUS
	 * @param ResiStatus  the value for PBCRS_REPORT_REDNCINFSGMT.RESISTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setResiStatus(String ResiStatus) {
		this.ResiStatus = ResiStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIADDR
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.RESIADDR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getResiAddr() {
		return ResiAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIADDR
	 * @param ResiAddr  the value for PBCRS_REPORT_REDNCINFSGMT.RESIADDR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setResiAddr(String ResiAddr) {
		this.ResiAddr = ResiAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIPC
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.RESIPC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getResiPc() {
		return ResiPc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIPC
	 * @param ResiPc  the value for PBCRS_REPORT_REDNCINFSGMT.RESIPC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setResiPc(String ResiPc) {
		this.ResiPc = ResiPc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIDIST
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.RESIDIST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getResiDist() {
		return ResiDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIDIST
	 * @param ResiDist  the value for PBCRS_REPORT_REDNCINFSGMT.RESIDIST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setResiDist(String ResiDist) {
		this.ResiDist = ResiDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.HOMETEL
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.HOMETEL
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getHomeTel() {
		return HomeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.HOMETEL
	 * @param HomeTel  the value for PBCRS_REPORT_REDNCINFSGMT.HOMETEL
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setHomeTel(String HomeTel) {
		this.HomeTel = HomeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIINFOUPDATE
	 * @return  the value of PBCRS_REPORT_REDNCINFSGMT.RESIINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getResiInfoUpDate() {
		return ResiInfoUpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_REDNCINFSGMT.RESIINFOUPDATE
	 * @param ResiInfoUpDate  the value for PBCRS_REPORT_REDNCINFSGMT.RESIINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setResiInfoUpDate(String ResiInfoUpDate) {
		this.ResiInfoUpDate = ResiInfoUpDate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -7164061022375933703L;
}