package com.hkbank.pbcrs.model;

import java.util.Date;

public class PbcrsReportReceivefile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.SEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Short seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.RECEIVEFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String receivefilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.RECEIVEFILEPATH
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String receivefilepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.RECEIVETXTFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String receivetxtfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.SENDFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String sendfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.MSGCODE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String msgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.SUCCESSCOUNT
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Short successCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.FAILCOUNT
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Short failCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.CREATEDATE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_RECEIVEFILE.IMPORTDATE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Date importDate;
    
    private String reportSeqNo;
    
    private String reportDate;

    private String resultErrorReason;
    
    private String validateResult;

    private String importTime;

    public String getImportTime() {
        return importTime;
    }

    public void setImportTime(String importTime) {
        this.importTime = importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.SEQNO
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.SEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Short getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.SEQNO
     *
     * @param seqno the value for PBCRS_REPORT_RECEIVEFILE.SEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setSeqno(Short seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.RECEIVEFILENAME
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.RECEIVEFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getReceivefilename() {
        return receivefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.RECEIVEFILENAME
     *
     * @param receivefilename the value for PBCRS_REPORT_RECEIVEFILE.RECEIVEFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setReceivefilename(String receivefilename) {
        this.receivefilename = receivefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.RECEIVEFILEPATH
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.RECEIVEFILEPATH
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getReceivefilepath() {
        return receivefilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.RECEIVEFILEPATH
     *
     * @param receivefilepath the value for PBCRS_REPORT_RECEIVEFILE.RECEIVEFILEPATH
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setReceivefilepath(String receivefilepath) {
        this.receivefilepath = receivefilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.RECEIVETXTFILENAME
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.RECEIVETXTFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getReceivetxtfilename() {
        return receivetxtfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.RECEIVETXTFILENAME
     *
     * @param receivetxtfilename the value for PBCRS_REPORT_RECEIVEFILE.RECEIVETXTFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setReceivetxtfilename(String receivetxtfilename) {
        this.receivetxtfilename = receivetxtfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.SENDFILENAME
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.SENDFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getSendfilename() {
        return sendfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.SENDFILENAME
     *
     * @param sendfilename the value for PBCRS_REPORT_RECEIVEFILE.SENDFILENAME
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setSendfilename(String sendfilename) {
        this.sendfilename = sendfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.MSGCODE
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.MSGCODE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getMsgcode() {
        return msgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.MSGCODE
     *
     * @param msgcode the value for PBCRS_REPORT_RECEIVEFILE.MSGCODE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setMsgcode(String msgcode) {
        this.msgcode = msgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.SUCCESSCOUNT
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.SUCCESSCOUNT
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Short getSuccessCount() {
        return successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.SUCCESSCOUNT
     *
     * @param successCount the value for PBCRS_REPORT_RECEIVEFILE.SUCCESSCOUNT
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setSuccessCount(Short successCount) {
        this.successCount = successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.FAILCOUNT
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.FAILCOUNT
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Short getFailCount() {
        return failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.FAILCOUNT
     *
     * @param failCount the value for PBCRS_REPORT_RECEIVEFILE.FAILCOUNT
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setFailCount(Short failCount) {
        this.failCount = failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.CREATEDATE
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.CREATEDATE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.CREATEDATE
     *
     * @param createDate the value for PBCRS_REPORT_RECEIVEFILE.CREATEDATE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_RECEIVEFILE.IMPORTDATE
     *
     * @return the value of PBCRS_REPORT_RECEIVEFILE.IMPORTDATE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Date getImportDate() {
        return importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_RECEIVEFILE.IMPORTDATE
     *
     * @param importDate the value for PBCRS_REPORT_RECEIVEFILE.IMPORTDATE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */


    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }

	public String getReportSeqNo() {
		return reportSeqNo;
	}

	public void setReportSeqNo(String reportSeqNo) {
		this.reportSeqNo = reportSeqNo;
	}

	public String getReportDate() {
		return reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	public String getResultErrorReason() {
		return resultErrorReason;
	}

	public void setResultErrorReason(String resultErrorReason) {
		this.resultErrorReason = resultErrorReason;
	}

	public String getValidateResult() {
		return validateResult;
	}

	public void setValidateResult(String validateResult) {
		this.validateResult = validateResult;
	}
    
	
}