package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("BsSgmt")
public class PbcrsReportEnaccinfmdfbssgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.BSSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
	@XStreamOmitField
    private String BsSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.MODRECCODE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    private String ModRecCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.RPTDATE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    private String RptDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.ACCTTYPE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    private String AcctType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.MDFCSGMTCODE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    private String MdfcSgmtCode;
    
    private String orgCode;
    
    
    
    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getReportFlag() {
		return reportFlag;
	}

	public void setReportFlag(String reportFlag) {
		this.reportFlag = reportFlag;
	}

	@XStreamOmitField
    private String reportFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.BSSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENACCINFMDFBSSGMT.BSSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public String getBsSgmtSeqNo() {
        return BsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.BSSGMTSEQNO
     *
     * @param BsSgmtSeqNo the value for PBCRS_REPORT_ENACCINFMDFBSSGMT.BSSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public void setBsSgmtSeqNo(String BsSgmtSeqNo) {
        this.BsSgmtSeqNo = BsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENACCINFMDFBSSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENACCINFMDFBSSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.MODRECCODE
     *
     * @return the value of PBCRS_REPORT_ENACCINFMDFBSSGMT.MODRECCODE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public String getModRecCode() {
        return ModRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.MODRECCODE
     *
     * @param ModRecCode the value for PBCRS_REPORT_ENACCINFMDFBSSGMT.MODRECCODE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public void setModRecCode(String ModRecCode) {
        this.ModRecCode = ModRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.RPTDATE
     *
     * @return the value of PBCRS_REPORT_ENACCINFMDFBSSGMT.RPTDATE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public String getRptDate() {
        return RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.RPTDATE
     *
     * @param RptDate the value for PBCRS_REPORT_ENACCINFMDFBSSGMT.RPTDATE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public void setRptDate(String RptDate) {
        this.RptDate = RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.ACCTTYPE
     *
     * @return the value of PBCRS_REPORT_ENACCINFMDFBSSGMT.ACCTTYPE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public String getAcctType() {
        return AcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.ACCTTYPE
     *
     * @param AcctType the value for PBCRS_REPORT_ENACCINFMDFBSSGMT.ACCTTYPE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public void setAcctType(String AcctType) {
        this.AcctType = AcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.MDFCSGMTCODE
     *
     * @return the value of PBCRS_REPORT_ENACCINFMDFBSSGMT.MDFCSGMTCODE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public String getMdfcSgmtCode() {
        return MdfcSgmtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFMDFBSSGMT.MDFCSGMTCODE
     *
     * @param MdfcSgmtCode the value for PBCRS_REPORT_ENACCINFMDFBSSGMT.MDFCSGMTCODE
     *
     * @mbggenerated Fri Mar 15 09:06:17 CST 2019
     */
    public void setMdfcSgmtCode(String MdfcSgmtCode) {
        this.MdfcSgmtCode = MdfcSgmtCode;
    }
}