package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.Date;

import com.thoughtworks.xstream.annotations.XStreamAlias;


@XStreamAlias("InSpcEvtDscInf")
public class PbcrsReportInspcevtdscinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3869941077720343023L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.INSPCEVTDSCINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InSpcEvtDscInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.ACCTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.OPETNTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OpetnType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.MONTH
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.FLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSPCEVTDSCINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDate;
	
	private Date Etl_Date;
	
	private String  SourceSys;
	
	private String	ReportFlag;
	
	public Date getEtl_Date() {
		return Etl_Date;
	}

	public void setEtl_Date(Date etl_Date) {
		Etl_Date = etl_Date;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.INSPCEVTDSCINFSEQNO
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.INSPCEVTDSCINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInSpcEvtDscInfSeqNo() {
		return InSpcEvtDscInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.INSPCEVTDSCINFSEQNO
	 * @param InSpcEvtDscInfSeqNo  the value for PBCRS_REPORT_INSPCEVTDSCINF.INSPCEVTDSCINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInSpcEvtDscInfSeqNo(String InSpcEvtDscInfSeqNo) {
		this.InSpcEvtDscInfSeqNo = InSpcEvtDscInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INSPCEVTDSCINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.ACCTCODE
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.ACCTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctCode() {
		return AcctCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.ACCTCODE
	 * @param AcctCode  the value for PBCRS_REPORT_INSPCEVTDSCINF.ACCTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctCode(String AcctCode) {
		this.AcctCode = AcctCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.OPETNTYPE
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.OPETNTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOpetnType() {
		return OpetnType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.OPETNTYPE
	 * @param OpetnType  the value for PBCRS_REPORT_INSPCEVTDSCINF.OPETNTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOpetnType(String OpetnType) {
		this.OpetnType = OpetnType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.MONTH
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.MONTH
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMonth() {
		return Month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.MONTH
	 * @param Month  the value for PBCRS_REPORT_INSPCEVTDSCINF.MONTH
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMonth(String Month) {
		this.Month = Month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.FLAG
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.FLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFlag() {
		return Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.FLAG
	 * @param Flag  the value for PBCRS_REPORT_INSPCEVTDSCINF.FLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFlag(String Flag) {
		this.Flag = Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.RPTDATE
	 * @return  the value of PBCRS_REPORT_INSPCEVTDSCINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDate() {
		return RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSPCEVTDSCINF.RPTDATE
	 * @param RptDate  the value for PBCRS_REPORT_INSPCEVTDSCINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDate(String RptDate) {
		this.RptDate = RptDate;
	}
}