package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("MotgaProptInfSgmt")
public class PbcrsReportMotgaproptinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8894325614121542381L;
	
	@XStreamImplicit
    private List<PbcrsReportPleinf> PleInf;
	
	public List<PbcrsReportPleinf> getPleInf() {
		return PleInf;
	}

	public void setPleInf(List<PbcrsReportPleinf> pleInf) {
		PleInf = pleInf;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTGAPROPTINFSGMT.MOTGAPROPTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String MotgaProptInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTGAPROPTINFSGMT.PLENM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleNm;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTGAPROPTINFSGMT.MOTGAPROPTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTGAPROPTINFSGMT.MOTGAPROPTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMotgaProptInfSgmtSeqNo() {
		return MotgaProptInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTGAPROPTINFSGMT.MOTGAPROPTINFSGMTSEQNO
	 * @param MotgaProptInfSgmtSeqNo  the value for PBCRS_REPORT_MOTGAPROPTINFSGMT.MOTGAPROPTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMotgaProptInfSgmtSeqNo(String MotgaProptInfSgmtSeqNo) {
		this.MotgaProptInfSgmtSeqNo = MotgaProptInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTGAPROPTINFSGMT.PLENM
	 * @return  the value of PBCRS_REPORT_MOTGAPROPTINFSGMT.PLENM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleNm() {
		return PleNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTGAPROPTINFSGMT.PLENM
	 * @param PleNm  the value for PBCRS_REPORT_MOTGAPROPTINFSGMT.PLENM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleNm(String PleNm) {
		this.PleNm = PleNm;
	}
}