package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("OrigCreditorInfSgmt")
public class PbcrsReportOricreinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3143225770721683456L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ORICREINFSGMT.ORIGCREDITORINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String OrigCreditorInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ORICREINFSGMT.INITCREDNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InitCredName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ORICREINFSGMT.INITCREDORGNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InitCredOrgNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ORICREINFSGMT.ORIGDBTCATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OrigDbtCate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ORICREINFSGMT.INITRPYSTS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InitRpySts;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ORICREINFSGMT.ORIGCREDITORINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ORICREINFSGMT.ORIGCREDITORINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOrigCreditorInfSgmtSeqNo() {
		return OrigCreditorInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ORICREINFSGMT.ORIGCREDITORINFSGMTSEQNO
	 * @param OrigCreditorInfSgmtSeqNo  the value for PBCRS_REPORT_ORICREINFSGMT.ORIGCREDITORINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOrigCreditorInfSgmtSeqNo(String OrigCreditorInfSgmtSeqNo) {
		this.OrigCreditorInfSgmtSeqNo = OrigCreditorInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ORICREINFSGMT.INITCREDNAME
	 * @return  the value of PBCRS_REPORT_ORICREINFSGMT.INITCREDNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInitCredName() {
		return InitCredName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ORICREINFSGMT.INITCREDNAME
	 * @param InitCredName  the value for PBCRS_REPORT_ORICREINFSGMT.INITCREDNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInitCredName(String InitCredName) {
		this.InitCredName = InitCredName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ORICREINFSGMT.INITCREDORGNM
	 * @return  the value of PBCRS_REPORT_ORICREINFSGMT.INITCREDORGNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInitCredOrgNm() {
		return InitCredOrgNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ORICREINFSGMT.INITCREDORGNM
	 * @param InitCredOrgNm  the value for PBCRS_REPORT_ORICREINFSGMT.INITCREDORGNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInitCredOrgNm(String InitCredOrgNm) {
		this.InitCredOrgNm = InitCredOrgNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ORICREINFSGMT.ORIGDBTCATE
	 * @return  the value of PBCRS_REPORT_ORICREINFSGMT.ORIGDBTCATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOrigDbtCate() {
		return OrigDbtCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ORICREINFSGMT.ORIGDBTCATE
	 * @param OrigDbtCate  the value for PBCRS_REPORT_ORICREINFSGMT.ORIGDBTCATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOrigDbtCate(String OrigDbtCate) {
		this.OrigDbtCate = OrigDbtCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ORICREINFSGMT.INITRPYSTS
	 * @return  the value of PBCRS_REPORT_ORICREINFSGMT.INITRPYSTS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInitRpySts() {
		return InitRpySts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ORICREINFSGMT.INITRPYSTS
	 * @param InitRpySts  the value for PBCRS_REPORT_ORICREINFSGMT.INITRPYSTS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInitRpySts(String InitRpySts) {
		this.InitRpySts = InitRpySts;
	}
}