package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("AcctDbtInfSgmt")
public class PbcrsReportAcctdbtinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 5928528042267943851L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTDBTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctDbtInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctBal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FiveCate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FiveCateAdjDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.REMREPPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RemRepPrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.RPYSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RpyStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.OVERDPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OverdPrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.TOTOVERD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String TotOverd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String LatRpyAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String LatRpyDate;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	
	@XStreamOmitField
	private String ParagraphDel;
	
	
	 public String getParagraphDel() {
		return ParagraphDel;
	}

	public void setParagraphDel(String paragraphDel) {
		ParagraphDel = paragraphDel;
	}

	/**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTDBTINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CloseDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTDBTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.ACCTDBTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctDbtInfSgmtSeqNo() {
		return AcctDbtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTDBTINFSGMTSEQNO
	 * @param AcctDbtInfSgmtSeqNo  the value for PBCRS_REPORT_ACCTDBTINFSGMT.ACCTDBTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctDbtInfSgmtSeqNo(String AcctDbtInfSgmtSeqNo) {
		this.AcctDbtInfSgmtSeqNo = AcctDbtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTSTATUS
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctStatus() {
		return AcctStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTSTATUS
	 * @param AcctStatus  the value for PBCRS_REPORT_ACCTDBTINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctStatus(String AcctStatus) {
		this.AcctStatus = AcctStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTBAL
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.ACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctBal() {
		return AcctBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.ACCTBAL
	 * @param AcctBal  the value for PBCRS_REPORT_ACCTDBTINFSGMT.ACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctBal(String AcctBal) {
		this.AcctBal = AcctBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATE
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFiveCate() {
		return FiveCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATE
	 * @param FiveCate  the value for PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFiveCate(String FiveCate) {
		this.FiveCate = FiveCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATEADJDATE
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFiveCateAdjDate() {
		return FiveCateAdjDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATEADJDATE
	 * @param FiveCateAdjDate  the value for PBCRS_REPORT_ACCTDBTINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFiveCateAdjDate(String FiveCateAdjDate) {
		this.FiveCateAdjDate = FiveCateAdjDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.REMREPPRD
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.REMREPPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRemRepPrd() {
		return RemRepPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.REMREPPRD
	 * @param RemRepPrd  the value for PBCRS_REPORT_ACCTDBTINFSGMT.REMREPPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRemRepPrd(String RemRepPrd) {
		this.RemRepPrd = RemRepPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.RPYSTATUS
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.RPYSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRpyStatus() {
		return RpyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.RPYSTATUS
	 * @param RpyStatus  the value for PBCRS_REPORT_ACCTDBTINFSGMT.RPYSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRpyStatus(String RpyStatus) {
		this.RpyStatus = RpyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.OVERDPRD
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.OVERDPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOverdPrd() {
		return OverdPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.OVERDPRD
	 * @param OverdPrd  the value for PBCRS_REPORT_ACCTDBTINFSGMT.OVERDPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOverdPrd(String OverdPrd) {
		this.OverdPrd = OverdPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.TOTOVERD
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.TOTOVERD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getTotOverd() {
		return TotOverd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.TOTOVERD
	 * @param TotOverd  the value for PBCRS_REPORT_ACCTDBTINFSGMT.TOTOVERD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setTotOverd(String TotOverd) {
		this.TotOverd = TotOverd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYAMT
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getLatRpyAmt() {
		return LatRpyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYAMT
	 * @param LatRpyAmt  the value for PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setLatRpyAmt(String LatRpyAmt) {
		this.LatRpyAmt = LatRpyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYDATE
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getLatRpyDate() {
		return LatRpyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYDATE
	 * @param LatRpyDate  the value for PBCRS_REPORT_ACCTDBTINFSGMT.LATRPYDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setLatRpyDate(String LatRpyDate) {
		this.LatRpyDate = LatRpyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.CLOSEDATE
	 * @return  the value of PBCRS_REPORT_ACCTDBTINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCloseDate() {
		return CloseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTDBTINFSGMT.CLOSEDATE
	 * @param CloseDate  the value for PBCRS_REPORT_ACCTDBTINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCloseDate(String CloseDate) {
		this.CloseDate = CloseDate;
	}
}