package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("CccInf")
public class PbcrsReportEncccinf {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ENCCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	@XStreamOmitField
	private String MotgaCltalCtrctInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ENCCCINF.CCCINFSEQNO
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	@XStreamOmitField
	private String CccInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ENCCCINF.CCC
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	private String Ccc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ENCCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ENCCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	public String getMotgaCltalCtrctInfSgmtSeqNo() {
		return MotgaCltalCtrctInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ENCCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @param MotgaCltalCtrctInfSgmtSeqNo  the value for PBCRS_REPORT_ENCCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	public void setMotgaCltalCtrctInfSgmtSeqNo(
			String MotgaCltalCtrctInfSgmtSeqNo) {
		this.MotgaCltalCtrctInfSgmtSeqNo = MotgaCltalCtrctInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ENCCCINF.CCCINFSEQNO
	 * @return  the value of PBCRS_REPORT_ENCCCINF.CCCINFSEQNO
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	public String getCccInfSeqNo() {
		return CccInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ENCCCINF.CCCINFSEQNO
	 * @param CccInfSeqNo  the value for PBCRS_REPORT_ENCCCINF.CCCINFSEQNO
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	public void setCccInfSeqNo(String CccInfSeqNo) {
		this.CccInfSeqNo = CccInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ENCCCINF.CCC
	 * @return  the value of PBCRS_REPORT_ENCCCINF.CCC
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	public String getCcc() {
		return Ccc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ENCCCINF.CCC
	 * @param Ccc  the value for PBCRS_REPORT_ENCCCINF.CCC
	 * @mbggenerated  Mon Mar 25 09:14:29 CST 2019
	 */
	public void setCcc(String Ccc) {
		this.Ccc = Ccc;
	}
}