package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;


@XStreamAlias("InIDEfctInfDlt")
public class PbcrsReportInidefctinfdlt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -423176949828505344L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINFDLT.INIDEFCTINFDLTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InIDEfctInfDltSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINFDLT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINFDLT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINFDLT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINFDLT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINFDLT.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfSurcCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.INIDEFCTINFDLTSEQNO
	 * @return  the value of PBCRS_REPORT_INIDEFCTINFDLT.INIDEFCTINFDLTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInIDEfctInfDltSeqNo() {
		return InIDEfctInfDltSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.INIDEFCTINFDLTSEQNO
	 * @param InIDEfctInfDltSeqNo  the value for PBCRS_REPORT_INIDEFCTINFDLT.INIDEFCTINFDLTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInIDEfctInfDltSeqNo(String InIDEfctInfDltSeqNo) {
		this.InIDEfctInfDltSeqNo = InIDEfctInfDltSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINFDLT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INIDEFCTINFDLT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.NAME
	 * @return  the value of PBCRS_REPORT_INIDEFCTINFDLT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getName() {
		return Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.NAME
	 * @param Name  the value for PBCRS_REPORT_INIDEFCTINFDLT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setName(String Name) {
		this.Name = Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.IDTYPE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINFDLT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDType() {
		return IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.IDTYPE
	 * @param IDType  the value for PBCRS_REPORT_INIDEFCTINFDLT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDType(String IDType) {
		this.IDType = IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.IDNUM
	 * @return  the value of PBCRS_REPORT_INIDEFCTINFDLT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDNum() {
		return IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.IDNUM
	 * @param IDNum  the value for PBCRS_REPORT_INIDEFCTINFDLT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDNum(String IDNum) {
		this.IDNum = IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.INFSURCCODE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINFDLT.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfSurcCode() {
		return InfSurcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINFDLT.INFSURCCODE
	 * @param InfSurcCode  the value for PBCRS_REPORT_INIDEFCTINFDLT.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfSurcCode(String InfSurcCode) {
		this.InfSurcCode = InfSurcCode;
	}
}