package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("InCtrctInf")
public class PbcrsReportInctrctinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3106524728043590448L;
	
	@XStreamAlias("CtrctBsSgmt")
	private PbcrsReportCtrctbssgmt CtrctBsSgmt;
	
	@XStreamAlias("CtrctCertRelSgmt")
	private PbcrsReportCtrctcertrelsgmt CtrctCertRelSgmt;
	
	@XStreamAlias("CreditLimSgmt")
	private PbcrsReportCreditlimsgmt CreditLimSgmt;
	
	public PbcrsReportCtrctbssgmt getCtrctBsSgmt() {
		return CtrctBsSgmt;
	}

	public void setCtrctBsSgmt(PbcrsReportCtrctbssgmt ctrctBsSgmt) {
		CtrctBsSgmt = ctrctBsSgmt;
	}

	public PbcrsReportCtrctcertrelsgmt getCtrctCertRelSgmt() {
		return CtrctCertRelSgmt;
	}

	public void setCtrctCertRelSgmt(PbcrsReportCtrctcertrelsgmt ctrctCertRelSgmt) {
		CtrctCertRelSgmt = ctrctCertRelSgmt;
	}

	public PbcrsReportCreditlimsgmt getCreditLimSgmt() {
		return CreditLimSgmt;
	}

	public void setCreditLimSgmt(PbcrsReportCreditlimsgmt creditLimSgmt) {
		CreditLimSgmt = creditLimSgmt;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTINF.INCTRCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String InCtrctInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTINF.CTRCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CtrctBsSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTINF.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CtrctCertRelSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRCTINF.CREDITLIMSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CreditLimSgmtSeqNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTINF.INCTRCTINFSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRCTINF.INCTRCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInCtrctInfSeqNo() {
		return InCtrctInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTINF.INCTRCTINFSEQNO
	 * @param InCtrctInfSeqNo  the value for PBCRS_REPORT_INCTRCTINF.INCTRCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInCtrctInfSeqNo(String InCtrctInfSeqNo) {
		this.InCtrctInfSeqNo = InCtrctInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTINF.CTRCTBSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRCTINF.CTRCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCtrctBsSgmtSeqNo() {
		return CtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTINF.CTRCTBSSGMTSEQNO
	 * @param CtrctBsSgmtSeqNo  the value for PBCRS_REPORT_INCTRCTINF.CTRCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCtrctBsSgmtSeqNo(String CtrctBsSgmtSeqNo) {
		this.CtrctBsSgmtSeqNo = CtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTINF.CTRCTCERTRELSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRCTINF.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCtrctCertRelSgmtSeqNo() {
		return CtrctCertRelSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTINF.CTRCTCERTRELSGMTSEQNO
	 * @param CtrctCertRelSgmtSeqNo  the value for PBCRS_REPORT_INCTRCTINF.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCtrctCertRelSgmtSeqNo(String CtrctCertRelSgmtSeqNo) {
		this.CtrctCertRelSgmtSeqNo = CtrctCertRelSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRCTINF.CREDITLIMSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRCTINF.CREDITLIMSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCreditLimSgmtSeqNo() {
		return CreditLimSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRCTINF.CREDITLIMSGMTSEQNO
	 * @param CreditLimSgmtSeqNo  the value for PBCRS_REPORT_INCTRCTINF.CREDITLIMSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCreditLimSgmtSeqNo(String CreditLimSgmtSeqNo) {
		this.CreditLimSgmtSeqNo = CreditLimSgmtSeqNo;
	}
}