package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("CtrctCertRelSgmt")
public class PbcrsReportCtrctcertrelsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1401176038462589027L;
	
	@XStreamImplicit
    private List<PbcrsReportCtrctcertrel> CtrctCertRel;
	
	public List<PbcrsReportCtrctcertrel> getCtrctCertRel() {
		return CtrctCertRel;
	}

	public void setCtrctCertRel(List<PbcrsReportCtrctcertrel> ctrctCertRel) {
		CtrctCertRel = ctrctCertRel;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTRELSGMT.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CtrctCertRelSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTRELSGMT.BRERNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String BrerNm;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTRELSGMT.CTRCTCERTRELSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_CTRCTCERTRELSGMT.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCtrctCertRelSgmtSeqNo() {
		return CtrctCertRelSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTRELSGMT.CTRCTCERTRELSGMTSEQNO
	 * @param CtrctCertRelSgmtSeqNo  the value for PBCRS_REPORT_CTRCTCERTRELSGMT.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCtrctCertRelSgmtSeqNo(String CtrctCertRelSgmtSeqNo) {
		this.CtrctCertRelSgmtSeqNo = CtrctCertRelSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTRELSGMT.BRERNM
	 * @return  the value of PBCRS_REPORT_CTRCTCERTRELSGMT.BRERNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getBrerNm() {
		return BrerNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTRELSGMT.BRERNM
	 * @param BrerNm  the value for PBCRS_REPORT_CTRCTCERTRELSGMT.BRERNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setBrerNm(String BrerNm) {
		this.BrerNm = BrerNm;
	}
}