package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("RltRepymtInf")
public class PbcrsReportGserltrepymtinf implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8417981024995405772L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String RltRepymtInfSgmtSeqNo;
	
	@XStreamOmitField
	private String ReportFlag;

	 
	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String RltRepymtInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.INFOIDTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String InfoIDType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPNAME
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String ArlpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String ArlpCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTNUM
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String ArlpCertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String ArlpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPAMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String ArlpAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.WARTYSIGN
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String WartySign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GSERLTREPYMTINF.MAXGUARMCC
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String MaxGuarMcc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getRltRepymtInfSgmtSeqNo() {
        return RltRepymtInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @param RltRepymtInfSgmtSeqNo the value for PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setRltRepymtInfSgmtSeqNo(String RltRepymtInfSgmtSeqNo) {
        this.RltRepymtInfSgmtSeqNo = RltRepymtInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSEQNO
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getRltRepymtInfSeqNo() {
        return RltRepymtInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSEQNO
     *
     * @param RltRepymtInfSeqNo the value for PBCRS_REPORT_GSERLTREPYMTINF.RLTREPYMTINFSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setRltRepymtInfSeqNo(String RltRepymtInfSeqNo) {
        this.RltRepymtInfSeqNo = RltRepymtInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.INFOIDTYPE
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.INFOIDTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getInfoIDType() {
        return InfoIDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.INFOIDTYPE
     *
     * @param InfoIDType the value for PBCRS_REPORT_GSERLTREPYMTINF.INFOIDTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setInfoIDType(String InfoIDType) {
        this.InfoIDType = InfoIDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPNAME
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.ARLPNAME
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getArlpName() {
        return ArlpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPNAME
     *
     * @param ArlpName the value for PBCRS_REPORT_GSERLTREPYMTINF.ARLPNAME
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setArlpName(String ArlpName) {
        this.ArlpName = ArlpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTTYPE
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getArlpCertType() {
        return ArlpCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTTYPE
     *
     * @param ArlpCertType the value for PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setArlpCertType(String ArlpCertType) {
        this.ArlpCertType = ArlpCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTNUM
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTNUM
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getArlpCertNum() {
        return ArlpCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTNUM
     *
     * @param ArlpCertNum the value for PBCRS_REPORT_GSERLTREPYMTINF.ARLPCERTNUM
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setArlpCertNum(String ArlpCertNum) {
        this.ArlpCertNum = ArlpCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPTYPE
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.ARLPTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getArlpType() {
        return ArlpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPTYPE
     *
     * @param ArlpType the value for PBCRS_REPORT_GSERLTREPYMTINF.ARLPTYPE
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setArlpType(String ArlpType) {
        this.ArlpType = ArlpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPAMT
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.ARLPAMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getArlpAmt() {
        return ArlpAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.ARLPAMT
     *
     * @param ArlpAmt the value for PBCRS_REPORT_GSERLTREPYMTINF.ARLPAMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setArlpAmt(String ArlpAmt) {
        this.ArlpAmt = ArlpAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.WARTYSIGN
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.WARTYSIGN
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getWartySign() {
        return WartySign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.WARTYSIGN
     *
     * @param WartySign the value for PBCRS_REPORT_GSERLTREPYMTINF.WARTYSIGN
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setWartySign(String WartySign) {
        this.WartySign = WartySign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.MAXGUARMCC
     *
     * @return the value of PBCRS_REPORT_GSERLTREPYMTINF.MAXGUARMCC
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getMaxGuarMcc() {
        return MaxGuarMcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GSERLTREPYMTINF.MAXGUARMCC
     *
     * @param MaxGuarMcc the value for PBCRS_REPORT_GSERLTREPYMTINF.MAXGUARMCC
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setMaxGuarMcc(String MaxGuarMcc) {
        this.MaxGuarMcc = MaxGuarMcc;
    }
}