package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("MnShaHodInfSgmt")
public class PbcrsReportMnshahodinfsgmt {
	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFSGMTSEQNO
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	@XStreamOmitField
	private String MnShaHodInfSgmtSeqNo;

	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MNSHAHODINFSGMT.MNSHARHODNM
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	private String MnSharHodNm;

	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MNSHAHODINFSGMT.REGCAPCURRENCY
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	private String RegCapCurrency;

	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MNSHAHODINFSGMT.REGCAP
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	private String RegCap;

	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFOUPDATE
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	private String MnShaHodInfoUpDate;
	
	
	 @XStreamOmitField
	    private String ReportFlag;
	    
	    public String getReportFlag() {
			return ReportFlag;
		}

		public void setReportFlag(String reportFlag) {
			ReportFlag = reportFlag;
		}
	
	
	@XStreamImplicit
	private List<PbcrsReportEnbasinfshahodinf> shahodinfList;

	public List<PbcrsReportEnbasinfshahodinf> getShahodinfList() {
		return shahodinfList;
	}

	public void setShahodinfList(List<PbcrsReportEnbasinfshahodinf> shahodinfList) {
		this.shahodinfList = shahodinfList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFSGMTSEQNO
	 * 
	 * @return the value of PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFSGMTSEQNO
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public String getMnShaHodInfSgmtSeqNo() {
		return MnShaHodInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFSGMTSEQNO
	 * 
	 * @param MnShaHodInfSgmtSeqNo
	 *            the value for
	 *            PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFSGMTSEQNO
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public void setMnShaHodInfSgmtSeqNo(String MnShaHodInfSgmtSeqNo) {
		this.MnShaHodInfSgmtSeqNo = MnShaHodInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MNSHAHODINFSGMT.MNSHARHODNM
	 * 
	 * @return the value of PBCRS_REPORT_MNSHAHODINFSGMT.MNSHARHODNM
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public String getMnSharHodNm() {
		return MnSharHodNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MNSHAHODINFSGMT.MNSHARHODNM
	 * 
	 * @param MnSharHodNm
	 *            the value for PBCRS_REPORT_MNSHAHODINFSGMT.MNSHARHODNM
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public void setMnSharHodNm(String MnSharHodNm) {
		this.MnSharHodNm = MnSharHodNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MNSHAHODINFSGMT.REGCAPCURRENCY
	 * 
	 * @return the value of PBCRS_REPORT_MNSHAHODINFSGMT.REGCAPCURRENCY
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public String getRegCapCurrency() {
		return RegCapCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MNSHAHODINFSGMT.REGCAPCURRENCY
	 * 
	 * @param RegCapCurrency
	 *            the value for PBCRS_REPORT_MNSHAHODINFSGMT.REGCAPCURRENCY
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public void setRegCapCurrency(String RegCapCurrency) {
		this.RegCapCurrency = RegCapCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MNSHAHODINFSGMT.REGCAP
	 * 
	 * @return the value of PBCRS_REPORT_MNSHAHODINFSGMT.REGCAP
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public String getRegCap() {
		return RegCap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MNSHAHODINFSGMT.REGCAP
	 * 
	 * @param RegCap
	 *            the value for PBCRS_REPORT_MNSHAHODINFSGMT.REGCAP
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public void setRegCap(String RegCap) {
		this.RegCap = RegCap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFOUPDATE
	 * 
	 * @return the value of PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFOUPDATE
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public String getMnShaHodInfoUpDate() {
		return MnShaHodInfoUpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFOUPDATE
	 * 
	 * @param MnShaHodInfoUpDate
	 *            the value for PBCRS_REPORT_MNSHAHODINFSGMT.MNSHAHODINFOUPDATE
	 * 
	 * @mbggenerated Thu Mar 14 15:00:52 CST 2019
	 */
	public void setMnShaHodInfoUpDate(String MnShaHodInfoUpDate) {
		this.MnShaHodInfoUpDate = MnShaHodInfoUpDate;
	}
}