package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.Date;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnAcctInfDel")
public class PbcrsReportEnacctinfdel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8905097662882555204L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFDEL.ENACCTINFIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
	@XStreamOmitField
    private String EnAcctInfIDCagsInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFDEL.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    private String DelRecCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFDEL.DELSGMTCODE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    private String DelSgmtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFDEL.DELSTARTDATE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    private String DelStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFDEL.DELENDDATE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    private String DelEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFDEL.ENACCTINFIDCAGSINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ENACCTINFDEL.ENACCTINFIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    
    private String ReportFlag;
	
	private Date Etl_Date;
	
	private String SourceSys;
	
	private String orgCode;
	
	

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

	public Date getEtl_Date() {
		return Etl_Date;
	}

	public void setEtl_Date(Date etl_Date) {
		Etl_Date = etl_Date;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

    
    public String getEnAcctInfIDCagsInfSeqNo() {
        return EnAcctInfIDCagsInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFDEL.ENACCTINFIDCAGSINFSEQNO
     *
     * @param EnAcctInfIDCagsInfSeqNo the value for PBCRS_REPORT_ENACCTINFDEL.ENACCTINFIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public void setEnAcctInfIDCagsInfSeqNo(String EnAcctInfIDCagsInfSeqNo) {
        this.EnAcctInfIDCagsInfSeqNo = EnAcctInfIDCagsInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFDEL.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFDEL.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFDEL.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENACCTINFDEL.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELRECCODE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public String getDelRecCode() {
        return DelRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELRECCODE
     *
     * @param DelRecCode the value for PBCRS_REPORT_ENACCTINFDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public void setDelRecCode(String DelRecCode) {
        this.DelRecCode = DelRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELSGMTCODE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFDEL.DELSGMTCODE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public String getDelSgmtCode() {
        return DelSgmtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELSGMTCODE
     *
     * @param DelSgmtCode the value for PBCRS_REPORT_ENACCTINFDEL.DELSGMTCODE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public void setDelSgmtCode(String DelSgmtCode) {
        this.DelSgmtCode = DelSgmtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELSTARTDATE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFDEL.DELSTARTDATE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public String getDelStartDate() {
        return DelStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELSTARTDATE
     *
     * @param DelStartDate the value for PBCRS_REPORT_ENACCTINFDEL.DELSTARTDATE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public void setDelStartDate(String DelStartDate) {
        this.DelStartDate = DelStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELENDDATE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFDEL.DELENDDATE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public String getDelEndDate() {
        return DelEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFDEL.DELENDDATE
     *
     * @param DelEndDate the value for PBCRS_REPORT_ENACCTINFDEL.DELENDDATE
     *
     * @mbggenerated Fri Mar 15 09:47:19 CST 2019
     */
    public void setDelEndDate(String DelEndDate) {
        this.DelEndDate = DelEndDate;
    }
}