package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("MotgaCltalCtrctInf")
public class PbcrsReportMotcltctrinf implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTINFSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String MotgaCltalCtrctInfSeqNo;

	@XStreamOmitField
	private String MotgaCltalCtrctBsSgmtSeqNo;

	@XStreamOmitField
	private String MotgaCltalBsInfSgmtSeqNo;

	@XStreamOmitField
	private String ComRecInfSgmtSeqNo;

	@XStreamOmitField
	private String MotgaProptInfSgmtSeqNo;

	@XStreamOmitField
	private String CltalInfSgmtSeqNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTINFSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTINFSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMotgaCltalCtrctInfSeqNo() {
		return MotgaCltalCtrctInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTINFSEQNO
	 * @param MotgaCltalCtrctInfSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTINFSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMotgaCltalCtrctInfSeqNo(String MotgaCltalCtrctInfSeqNo) {
		this.MotgaCltalCtrctInfSeqNo = MotgaCltalCtrctInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTBSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTBSSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMotgaCltalCtrctBsSgmtSeqNo() {
		return MotgaCltalCtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTBSSGMTSEQNO
	 * @param MotgaCltalCtrctBsSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALCTRCTBSSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMotgaCltalCtrctBsSgmtSeqNo(String MotgaCltalCtrctBsSgmtSeqNo) {
		this.MotgaCltalCtrctBsSgmtSeqNo = MotgaCltalCtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALBSINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALBSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMotgaCltalBsInfSgmtSeqNo() {
		return MotgaCltalBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALBSINFSGMTSEQNO
	 * @param MotgaCltalBsInfSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINF.MOTGACLTALBSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMotgaCltalBsInfSgmtSeqNo(String MotgaCltalBsInfSgmtSeqNo) {
		this.MotgaCltalBsInfSgmtSeqNo = MotgaCltalBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINF.COMRECINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINF.COMRECINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getComRecInfSgmtSeqNo() {
		return ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINF.COMRECINFSGMTSEQNO
	 * @param ComRecInfSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINF.COMRECINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setComRecInfSgmtSeqNo(String ComRecInfSgmtSeqNo) {
		this.ComRecInfSgmtSeqNo = ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGAPROPTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINF.MOTGAPROPTINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMotgaProptInfSgmtSeqNo() {
		return MotgaProptInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINF.MOTGAPROPTINFSGMTSEQNO
	 * @param MotgaProptInfSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINF.MOTGAPROPTINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMotgaProptInfSgmtSeqNo(String MotgaProptInfSgmtSeqNo) {
		this.MotgaProptInfSgmtSeqNo = MotgaProptInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINF.CLTALINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINF.CLTALINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCltalInfSgmtSeqNo() {
		return CltalInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINF.CLTALINFSGMTSEQNO
	 * @param CltalInfSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINF.CLTALINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCltalInfSgmtSeqNo(String CltalInfSgmtSeqNo) {
		this.CltalInfSgmtSeqNo = CltalInfSgmtSeqNo;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 2054162853724230465L;
	
	@XStreamAlias("MotgaCltalCtrctBsSgmt")
	private PbcrsReportMotcltctrbssgmt MotCltCtrBsSgmt;
	
	@XStreamAlias("MotgaCltalBsInfSgmt")
	private PbcrsReportMotcltbsinfsgmt MotCltBsInfSgmt;
	
	@XStreamAlias("ComRecInfSgmt")
	private PbcrsReportComrecinfsgmt ComRecInfSgmt;
	
	@XStreamAlias("MotgaProptInfSgmt")
	private PbcrsReportMotgaproptinfsgmt MotgaProptInfSgmt;
	
	@XStreamAlias("CltalInfSgmt")
	private PbcrsReportCltalinfsgmt CltalInfSgmt;
	
	public PbcrsReportMotcltctrbssgmt getMotCltCtrBsSgmt() {
		return MotCltCtrBsSgmt;
	}

	public void setMotCltCtrBsSgmt(PbcrsReportMotcltctrbssgmt motCltCtrBsSgmt) {
		MotCltCtrBsSgmt = motCltCtrBsSgmt;
	}

	public PbcrsReportMotcltbsinfsgmt getMotCltBsInfSgmt() {
		return MotCltBsInfSgmt;
	}

	public void setMotCltBsInfSgmt(PbcrsReportMotcltbsinfsgmt motCltBsInfSgmt) {
		MotCltBsInfSgmt = motCltBsInfSgmt;
	}

	public PbcrsReportComrecinfsgmt getComRecInfSgmt() {
		return ComRecInfSgmt;
	}

	public void setComRecInfSgmt(PbcrsReportComrecinfsgmt comRecInfSgmt) {
		ComRecInfSgmt = comRecInfSgmt;
	}

	public PbcrsReportMotgaproptinfsgmt getMotgaProptInfSgmt() {
		return MotgaProptInfSgmt;
	}

	public void setMotgaProptInfSgmt(PbcrsReportMotgaproptinfsgmt motgaProptInfSgmt) {
		MotgaProptInfSgmt = motgaProptInfSgmt;
	}

	public PbcrsReportCltalinfsgmt getCltalInfSgmt() {
		return CltalInfSgmt;
	}

	public void setCltalInfSgmt(PbcrsReportCltalinfsgmt cltalInfSgmt) {
		CltalInfSgmt = cltalInfSgmt;
	}
}