package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("CccInf")
public class PbcrsReportCccinf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
	@XStreamOmitField
    private String MotgaCltalCtrctInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CCCINF.CCCINFSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
	@XStreamOmitField
    private String CccInfSeqNo;
	
	@XStreamOmitField
	private String ReportFlag;
	    
	    
	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CCCINF.CCC
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    private String Ccc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    @XStreamOmitField
    private String MotgaCltalCtrctInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFTYPE
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    @XStreamOmitField
    private String MotgaCltalCtrctInfType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public String getMotgaCltalCtrctInfSgmtSeqNo() {
        return MotgaCltalCtrctInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @param MotgaCltalCtrctInfSgmtSeqNo the value for PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public void setMotgaCltalCtrctInfSgmtSeqNo(String MotgaCltalCtrctInfSgmtSeqNo) {
        this.MotgaCltalCtrctInfSgmtSeqNo = MotgaCltalCtrctInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CCCINF.CCCINFSEQNO
     *
     * @return the value of PBCRS_REPORT_CCCINF.CCCINFSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public String getCccInfSeqNo() {
        return CccInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CCCINF.CCCINFSEQNO
     *
     * @param CccInfSeqNo the value for PBCRS_REPORT_CCCINF.CCCINFSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public void setCccInfSeqNo(String CccInfSeqNo) {
        this.CccInfSeqNo = CccInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CCCINF.CCC
     *
     * @return the value of PBCRS_REPORT_CCCINF.CCC
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public String getCcc() {
        return Ccc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CCCINF.CCC
     *
     * @param Ccc the value for PBCRS_REPORT_CCCINF.CCC
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public void setCcc(String Ccc) {
        this.Ccc = Ccc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSEQNO
     *
     * @return the value of PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public String getMotgaCltalCtrctInfSeqNo() {
        return MotgaCltalCtrctInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSEQNO
     *
     * @param MotgaCltalCtrctInfSeqNo the value for PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFSEQNO
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public void setMotgaCltalCtrctInfSeqNo(String MotgaCltalCtrctInfSeqNo) {
        this.MotgaCltalCtrctInfSeqNo = MotgaCltalCtrctInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFTYPE
     *
     * @return the value of PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFTYPE
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public String getMotgaCltalCtrctInfType() {
        return MotgaCltalCtrctInfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFTYPE
     *
     * @param MotgaCltalCtrctInfType the value for PBCRS_REPORT_CCCINF.MOTGACLTALCTRCTINFTYPE
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    public void setMotgaCltalCtrctInfType(String MotgaCltalCtrctInfType) {
        this.MotgaCltalCtrctInfType = MotgaCltalCtrctInfType;
    }
}