package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("AcctCredSgmt")
public class PbcrsReportAcctcredsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 434475154365916463L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTCREDSGMT.ACCTCREDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctCredSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTCREDSGMT.MCC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Mcc;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTCREDSGMT.ACCTCREDSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ACCTCREDSGMT.ACCTCREDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctCredSgmtSeqNo() {
		return AcctCredSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTCREDSGMT.ACCTCREDSGMTSEQNO
	 * @param AcctCredSgmtSeqNo  the value for PBCRS_REPORT_ACCTCREDSGMT.ACCTCREDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctCredSgmtSeqNo(String AcctCredSgmtSeqNo) {
		this.AcctCredSgmtSeqNo = AcctCredSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTCREDSGMT.MCC
	 * @return  the value of PBCRS_REPORT_ACCTCREDSGMT.MCC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMcc() {
		return Mcc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTCREDSGMT.MCC
	 * @param Mcc  the value for PBCRS_REPORT_ACCTCREDSGMT.MCC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMcc(String Mcc) {
		this.Mcc = Mcc;
	}
}