package com.hkbank.pbcrs.model;

public class PbcrsInvestigationType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_INVESTIGATION_TYPE.MAPPER_TYPE
     *
     * @mbggenerated Tue Apr 23 16:35:08 CST 2019
     */
    private String mapperType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_INVESTIGATION_TYPE.MAPPER_NAME
     *
     * @mbggenerated Tue Apr 23 16:35:08 CST 2019
     */
    private String mapperName;
    
    private String mapperTable;
    
    private String mapperPapagraph;
    
    private String mapperSeqId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_INVESTIGATION_TYPE.MAPPER_TYPE
     *
     * @return the value of PBCRS_INVESTIGATION_TYPE.MAPPER_TYPE
     *
     * @mbggenerated Tue Apr 23 16:35:08 CST 2019
     */
    public String getMapperType() {
        return mapperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_INVESTIGATION_TYPE.MAPPER_TYPE
     *
     * @param mapperType the value for PBCRS_INVESTIGATION_TYPE.MAPPER_TYPE
     *
     * @mbggenerated Tue Apr 23 16:35:08 CST 2019
     */
    public void setMapperType(String mapperType) {
        this.mapperType = mapperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_INVESTIGATION_TYPE.MAPPER_NAME
     *
     * @return the value of PBCRS_INVESTIGATION_TYPE.MAPPER_NAME
     *
     * @mbggenerated Tue Apr 23 16:35:08 CST 2019
     */
    public String getMapperName() {
        return mapperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_INVESTIGATION_TYPE.MAPPER_NAME
     *
     * @param mapperName the value for PBCRS_INVESTIGATION_TYPE.MAPPER_NAME
     *
     * @mbggenerated Tue Apr 23 16:35:08 CST 2019
     */
    public void setMapperName(String mapperName) {
        this.mapperName = mapperName;
    }

	public String getMapperTable() {
		return mapperTable;
	}

	public void setMapperTable(String mapperTable) {
		this.mapperTable = mapperTable;
	}

	public String getMapperPapagraph() {
		return mapperPapagraph;
	}

	public void setMapperPapagraph(String mapperPapagraph) {
		this.mapperPapagraph = mapperPapagraph;
	}

	public String getMapperSeqId() {
		return mapperSeqId;
	}

	public void setMapperSeqId(String mapperSeqId) {
		this.mapperSeqId = mapperSeqId;
	}


    
	
    
}