package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnSecAcctIDCagsInf")
public class PbcrsReportEnsecaccidcaginf implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3225419953634772851L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCIDCAGINF.ENSECACCTIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
	@XStreamOmitField
    private String EnSecAcctIDCagsInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCIDCAGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCIDCAGINF.ODBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    private String OdBnesCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCIDCAGINF.NWBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    private String NwBnesCode;
    
    @XStreamOmitField
    private String reportFlag; 
    
    @XStreamOmitField
    private String orgCode;
    
    

    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getReportFlag() {
		return reportFlag;
	}

	public void setReportFlag(String reportFlag) {
		this.reportFlag = reportFlag;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.ENSECACCTIDCAGSINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCIDCAGINF.ENSECACCTIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public String getEnSecAcctIDCagsInfSeqNo() {
        return EnSecAcctIDCagsInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.ENSECACCTIDCAGSINFSEQNO
     *
     * @param EnSecAcctIDCagsInfSeqNo the value for PBCRS_REPORT_ENSECACCIDCAGINF.ENSECACCTIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public void setEnSecAcctIDCagsInfSeqNo(String EnSecAcctIDCagsInfSeqNo) {
        this.EnSecAcctIDCagsInfSeqNo = EnSecAcctIDCagsInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENSECACCIDCAGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENSECACCIDCAGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.ODBNESCODE
     *
     * @return the value of PBCRS_REPORT_ENSECACCIDCAGINF.ODBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public String getOdBnesCode() {
        return OdBnesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.ODBNESCODE
     *
     * @param OdBnesCode the value for PBCRS_REPORT_ENSECACCIDCAGINF.ODBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public void setOdBnesCode(String OdBnesCode) {
        this.OdBnesCode = OdBnesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.NWBNESCODE
     *
     * @return the value of PBCRS_REPORT_ENSECACCIDCAGINF.NWBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public String getNwBnesCode() {
        return NwBnesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCIDCAGINF.NWBNESCODE
     *
     * @param NwBnesCode the value for PBCRS_REPORT_ENSECACCIDCAGINF.NWBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:27:35 CST 2019
     */
    public void setNwBnesCode(String NwBnesCode) {
        this.NwBnesCode = NwBnesCode;
    }
}