package com.hkbank.pbcrs.model;

public class PbcrsReportErrinf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ERRINF.FBINFSEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Short Fbinfseqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ERRINF.ERRINFSEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private Short ErrInfseqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ERRINF.FBCODE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String FbCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ERRINF.FBMSG
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    private String FbMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ERRINF.FBINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ERRINF.FBINFSEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Short getFbinfseqno() {
        return Fbinfseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ERRINF.FBINFSEQNO
     *
     * @param Fbinfseqno the value for PBCRS_REPORT_ERRINF.FBINFSEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setFbinfseqno(Short Fbinfseqno) {
        this.Fbinfseqno = Fbinfseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ERRINF.ERRINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ERRINF.ERRINFSEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public Short getErrInfseqno() {
        return ErrInfseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ERRINF.ERRINFSEQNO
     *
     * @param ErrInfseqno the value for PBCRS_REPORT_ERRINF.ERRINFSEQNO
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setErrInfseqno(Short ErrInfseqno) {
        this.ErrInfseqno = ErrInfseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ERRINF.FBCODE
     *
     * @return the value of PBCRS_REPORT_ERRINF.FBCODE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getFbCode() {
        return FbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ERRINF.FBCODE
     *
     * @param FbCode the value for PBCRS_REPORT_ERRINF.FBCODE
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setFbCode(String FbCode) {
        this.FbCode = FbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ERRINF.FBMSG
     *
     * @return the value of PBCRS_REPORT_ERRINF.FBMSG
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public String getFbMsg() {
        return FbMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ERRINF.FBMSG
     *
     * @param FbMsg the value for PBCRS_REPORT_ERRINF.FBMSG
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    public void setFbMsg(String FbMsg) {
        this.FbMsg = FbMsg;
    }
}