package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("SpvsgAthrtyInfSgmt")
public class PbcrsReportSpvathinfsgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_SPVATHINFSGMT.SPVSGATHRTYINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
	@XStreamOmitField
    private String SpvsgAthrtyInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String SupOrgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGNAME
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String SupOrgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String SupOrgCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTNUM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String SupOrgCertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String SupOrgInfoUpDate;
    
    @XStreamOmitField
    private String ReportFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SPVSGATHRTYINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_SPVATHINFSGMT.SPVSGATHRTYINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getSpvsgAthrtyInfSgmtSeqNo() {
        return SpvsgAthrtyInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SPVSGATHRTYINFSGMTSEQNO
     *
     * @param SpvsgAthrtyInfSgmtSeqNo the value for PBCRS_REPORT_SPVATHINFSGMT.SPVSGATHRTYINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setSpvsgAthrtyInfSgmtSeqNo(String SpvsgAthrtyInfSgmtSeqNo) {
        this.SpvsgAthrtyInfSgmtSeqNo = SpvsgAthrtyInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGTYPE
     *
     * @return the value of PBCRS_REPORT_SPVATHINFSGMT.SUPORGTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getSupOrgType() {
        return SupOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGTYPE
     *
     * @param SupOrgType the value for PBCRS_REPORT_SPVATHINFSGMT.SUPORGTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setSupOrgType(String SupOrgType) {
        this.SupOrgType = SupOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGNAME
     *
     * @return the value of PBCRS_REPORT_SPVATHINFSGMT.SUPORGNAME
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getSupOrgName() {
        return SupOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGNAME
     *
     * @param SupOrgName the value for PBCRS_REPORT_SPVATHINFSGMT.SUPORGNAME
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setSupOrgName(String SupOrgName) {
        this.SupOrgName = SupOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTTYPE
     *
     * @return the value of PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getSupOrgCertType() {
        return SupOrgCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTTYPE
     *
     * @param SupOrgCertType the value for PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTTYPE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setSupOrgCertType(String SupOrgCertType) {
        this.SupOrgCertType = SupOrgCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTNUM
     *
     * @return the value of PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTNUM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getSupOrgCertNum() {
        return SupOrgCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTNUM
     *
     * @param SupOrgCertNum the value for PBCRS_REPORT_SPVATHINFSGMT.SUPORGCERTNUM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setSupOrgCertNum(String SupOrgCertNum) {
        this.SupOrgCertNum = SupOrgCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGINFOUPDATE
     *
     * @return the value of PBCRS_REPORT_SPVATHINFSGMT.SUPORGINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getSupOrgInfoUpDate() {
        return SupOrgInfoUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_SPVATHINFSGMT.SUPORGINFOUPDATE
     *
     * @param SupOrgInfoUpDate the value for PBCRS_REPORT_SPVATHINFSGMT.SUPORGINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setSupOrgInfoUpDate(String SupOrgInfoUpDate) {
        this.SupOrgInfoUpDate = SupOrgInfoUpDate;
    }

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
}