package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("GuarAcctBsSgmt")
public class PbcrsReportGuaracctbssgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4722119572686975742L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String GuarAcctBsSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.ACCTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.ACCTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.RPTDATECODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDateCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GUARACCTBSSGMT.MNGMTORGCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String MngmtOrgCode;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuarAcctBsSgmtSeqNo() {
		return GuarAcctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
	 * @param GuarAcctBsSgmtSeqNo  the value for PBCRS_REPORT_GUARACCTBSSGMT.GUARACCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuarAcctBsSgmtSeqNo(String GuarAcctBsSgmtSeqNo) {
		this.GuarAcctBsSgmtSeqNo = GuarAcctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_GUARACCTBSSGMT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.ACCTTYPE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.ACCTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctType() {
		return AcctType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.ACCTTYPE
	 * @param AcctType  the value for PBCRS_REPORT_GUARACCTBSSGMT.ACCTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctType(String AcctType) {
		this.AcctType = AcctType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.ACCTCODE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.ACCTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctCode() {
		return AcctCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.ACCTCODE
	 * @param AcctCode  the value for PBCRS_REPORT_GUARACCTBSSGMT.ACCTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctCode(String AcctCode) {
		this.AcctCode = AcctCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.RPTDATE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDate() {
		return RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.RPTDATE
	 * @param RptDate  the value for PBCRS_REPORT_GUARACCTBSSGMT.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDate(String RptDate) {
		this.RptDate = RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.RPTDATECODE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.RPTDATECODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDateCode() {
		return RptDateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.RPTDATECODE
	 * @param RptDateCode  the value for PBCRS_REPORT_GUARACCTBSSGMT.RPTDATECODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDateCode(String RptDateCode) {
		this.RptDateCode = RptDateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.NAME
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getName() {
		return Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.NAME
	 * @param Name  the value for PBCRS_REPORT_GUARACCTBSSGMT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setName(String Name) {
		this.Name = Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.IDTYPE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDType() {
		return IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.IDTYPE
	 * @param IDType  the value for PBCRS_REPORT_GUARACCTBSSGMT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDType(String IDType) {
		this.IDType = IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.IDNUM
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDNum() {
		return IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.IDNUM
	 * @param IDNum  the value for PBCRS_REPORT_GUARACCTBSSGMT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDNum(String IDNum) {
		this.IDNum = IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.MNGMTORGCODE
	 * @return  the value of PBCRS_REPORT_GUARACCTBSSGMT.MNGMTORGCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMngmtOrgCode() {
		return MngmtOrgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GUARACCTBSSGMT.MNGMTORGCODE
	 * @param MngmtOrgCode  the value for PBCRS_REPORT_GUARACCTBSSGMT.MNGMTORGCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMngmtOrgCode(String MngmtOrgCode) {
		this.MngmtOrgCode = MngmtOrgCode;
	}

	@Override
	public String toString() {
		return "PbcrsReportGuaracctbssgmt [InfRecType=" + InfRecType + ", AcctType=" + AcctType + ", AcctCode=" + AcctCode + ", RptDateCode=" + RptDateCode + ", Name=" + Name + ", IDType=" + IDType
				+ ", IDNum=" + IDNum + ", MngmtOrgCode=" + MngmtOrgCode + ", reportflag=" + reportflag + "]";
	}

	

	
	
}