package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("InIDEfctInf")
public class PbcrsReportInidefctinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8466538076089486516L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.INIDEFCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String InIDEfctInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfSurcCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.IDEFCTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDEfctDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.IDDUEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDDueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.IDORGNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDOrgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.IDDIST
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDDist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.CIMOC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Cimoc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INIDEFCTINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.INIDEFCTINFSEQNO
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.INIDEFCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInIDEfctInfSeqNo() {
		return InIDEfctInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.INIDEFCTINFSEQNO
	 * @param InIDEfctInfSeqNo  the value for PBCRS_REPORT_INIDEFCTINF.INIDEFCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInIDEfctInfSeqNo(String InIDEfctInfSeqNo) {
		this.InIDEfctInfSeqNo = InIDEfctInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INIDEFCTINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.NAME
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getName() {
		return Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.NAME
	 * @param Name  the value for PBCRS_REPORT_INIDEFCTINF.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setName(String Name) {
		this.Name = Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.IDTYPE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDType() {
		return IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.IDTYPE
	 * @param IDType  the value for PBCRS_REPORT_INIDEFCTINF.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDType(String IDType) {
		this.IDType = IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.IDNUM
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDNum() {
		return IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.IDNUM
	 * @param IDNum  the value for PBCRS_REPORT_INIDEFCTINF.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDNum(String IDNum) {
		this.IDNum = IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.INFSURCCODE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfSurcCode() {
		return InfSurcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.INFSURCCODE
	 * @param InfSurcCode  the value for PBCRS_REPORT_INIDEFCTINF.INFSURCCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfSurcCode(String InfSurcCode) {
		this.InfSurcCode = InfSurcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.IDEFCTDATE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.IDEFCTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDEfctDate() {
		return IDEfctDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.IDEFCTDATE
	 * @param IDEfctDate  the value for PBCRS_REPORT_INIDEFCTINF.IDEFCTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDEfctDate(String IDEfctDate) {
		this.IDEfctDate = IDEfctDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.IDDUEDATE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.IDDUEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDDueDate() {
		return IDDueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.IDDUEDATE
	 * @param IDDueDate  the value for PBCRS_REPORT_INIDEFCTINF.IDDUEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDDueDate(String IDDueDate) {
		this.IDDueDate = IDDueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.IDORGNAME
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.IDORGNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDOrgName() {
		return IDOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.IDORGNAME
	 * @param IDOrgName  the value for PBCRS_REPORT_INIDEFCTINF.IDORGNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDOrgName(String IDOrgName) {
		this.IDOrgName = IDOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.IDDIST
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.IDDIST
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDDist() {
		return IDDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.IDDIST
	 * @param IDDist  the value for PBCRS_REPORT_INIDEFCTINF.IDDIST
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDDist(String IDDist) {
		this.IDDist = IDDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.CIMOC
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.CIMOC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCimoc() {
		return Cimoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.CIMOC
	 * @param Cimoc  the value for PBCRS_REPORT_INIDEFCTINF.CIMOC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCimoc(String Cimoc) {
		this.Cimoc = Cimoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INIDEFCTINF.RPTDATE
	 * @return  the value of PBCRS_REPORT_INIDEFCTINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDate() {
		return RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INIDEFCTINF.RPTDATE
	 * @param RptDate  the value for PBCRS_REPORT_INIDEFCTINF.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDate(String RptDate) {
		this.RptDate = RptDate;
	}
}