package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamOmitField;

public class PbcrsReportEncreditlimsgmt implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2855731136825092569L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
	@XStreamOmitField
    private String CreditLimSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMTYPE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String CreditLimType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.LIMLOOPFLG
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String LimLoopFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIM
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String CreditLim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CY
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String Cy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONEFFDATE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String ConEffDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONEXPDATE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String ConExpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONSTATUS
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String ConStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITRESTCODE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String CreditRestCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITREST
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    private String CreditRest;
    
    @XStreamOmitField
    private String ReportFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getCreditLimSgmtSeqNo() {
        return CreditLimSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMSGMTSEQNO
     *
     * @param CreditLimSgmtSeqNo the value for PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setCreditLimSgmtSeqNo(String CreditLimSgmtSeqNo) {
        this.CreditLimSgmtSeqNo = CreditLimSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMTYPE
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMTYPE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getCreditLimType() {
        return CreditLimType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMTYPE
     *
     * @param CreditLimType the value for PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIMTYPE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setCreditLimType(String CreditLimType) {
        this.CreditLimType = CreditLimType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.LIMLOOPFLG
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.LIMLOOPFLG
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getLimLoopFlg() {
        return LimLoopFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.LIMLOOPFLG
     *
     * @param LimLoopFlg the value for PBCRS_REPORT_ENCREDITLIMSGMT.LIMLOOPFLG
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setLimLoopFlg(String LimLoopFlg) {
        this.LimLoopFlg = LimLoopFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIM
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIM
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getCreditLim() {
        return CreditLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIM
     *
     * @param CreditLim the value for PBCRS_REPORT_ENCREDITLIMSGMT.CREDITLIM
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setCreditLim(String CreditLim) {
        this.CreditLim = CreditLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CY
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CY
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getCy() {
        return Cy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CY
     *
     * @param Cy the value for PBCRS_REPORT_ENCREDITLIMSGMT.CY
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setCy(String Cy) {
        this.Cy = Cy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONEFFDATE
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CONEFFDATE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getConEffDate() {
        return ConEffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONEFFDATE
     *
     * @param ConEffDate the value for PBCRS_REPORT_ENCREDITLIMSGMT.CONEFFDATE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setConEffDate(String ConEffDate) {
        this.ConEffDate = ConEffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONEXPDATE
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CONEXPDATE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getConExpDate() {
        return ConExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONEXPDATE
     *
     * @param ConExpDate the value for PBCRS_REPORT_ENCREDITLIMSGMT.CONEXPDATE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setConExpDate(String ConExpDate) {
        this.ConExpDate = ConExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONSTATUS
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CONSTATUS
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getConStatus() {
        return ConStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CONSTATUS
     *
     * @param ConStatus the value for PBCRS_REPORT_ENCREDITLIMSGMT.CONSTATUS
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setConStatus(String ConStatus) {
        this.ConStatus = ConStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITRESTCODE
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CREDITRESTCODE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getCreditRestCode() {
        return CreditRestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITRESTCODE
     *
     * @param CreditRestCode the value for PBCRS_REPORT_ENCREDITLIMSGMT.CREDITRESTCODE
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setCreditRestCode(String CreditRestCode) {
        this.CreditRestCode = CreditRestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITREST
     *
     * @return the value of PBCRS_REPORT_ENCREDITLIMSGMT.CREDITREST
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public String getCreditRest() {
        return CreditRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCREDITLIMSGMT.CREDITREST
     *
     * @param CreditRest the value for PBCRS_REPORT_ENCREDITLIMSGMT.CREDITREST
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    public void setCreditRest(String CreditRest) {
        this.CreditRest = CreditRest;
    }

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
    
}