package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("IDRec")
public class PbcrsReportIdrec implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IDREC.IDSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String IDSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IDREC.IDSGMTLISTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String IDSgmtListSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IDREC.ALIAS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("Alias")
	private String Alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IDREC.OTHIDTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("OthIDType")
	private String OthIDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IDREC.OTHIDNUM
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("OthIDNum")
	private String OthIDNum;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IDREC.IDSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_IDREC.IDSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getIDSgmtSeqNo() {
		return IDSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IDREC.IDSGMTSEQNO
	 * @param IDSgmtSeqNo  the value for PBCRS_REPORT_IDREC.IDSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setIDSgmtSeqNo(String IDSgmtSeqNo) {
		this.IDSgmtSeqNo = IDSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IDREC.IDSGMTLISTSEQNO
	 * @return  the value of PBCRS_REPORT_IDREC.IDSGMTLISTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getIDSgmtListSeqNo() {
		return IDSgmtListSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IDREC.IDSGMTLISTSEQNO
	 * @param IDSgmtListSeqNo  the value for PBCRS_REPORT_IDREC.IDSGMTLISTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setIDSgmtListSeqNo(String IDSgmtListSeqNo) {
		this.IDSgmtListSeqNo = IDSgmtListSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IDREC.ALIAS
	 * @return  the value of PBCRS_REPORT_IDREC.ALIAS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getAlias() {
		return Alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IDREC.ALIAS
	 * @param Alias  the value for PBCRS_REPORT_IDREC.ALIAS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setAlias(String Alias) {
		this.Alias = Alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IDREC.OTHIDTYPE
	 * @return  the value of PBCRS_REPORT_IDREC.OTHIDTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getOthIDType() {
		return OthIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IDREC.OTHIDTYPE
	 * @param OthIDType  the value for PBCRS_REPORT_IDREC.OTHIDTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setOthIDType(String OthIDType) {
		this.OthIDType = OthIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IDREC.OTHIDNUM
	 * @return  the value of PBCRS_REPORT_IDREC.OTHIDNUM
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getOthIDNum() {
		return OthIDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IDREC.OTHIDNUM
	 * @param OthIDNum  the value for PBCRS_REPORT_IDREC.OTHIDNUM
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setOthIDNum(String OthIDNum) {
		this.OthIDNum = OthIDNum;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -3003926272953494944L;
}