package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("MlgInfSgmt")
public class PbcrsReportMlginfsgmt implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MLGINFSGMT.MLGINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String MlgInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MLGINFSGMT.MAILADDR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("MailAddr")
	private String MailAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MLGINFSGMT.MAILPC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("MailPc")
	private String MailPc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MLGINFSGMT.MAILDIST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("MailDist")
	private String MailDist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MLGINFSGMT.MLGINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamAlias("MlgInfoUpDate")
	private String MlgInfoUpDate;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MLGINFSGMT.MLGINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MLGINFSGMT.MLGINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMlgInfSgmtSeqNo() {
		return MlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MLGINFSGMT.MLGINFSGMTSEQNO
	 * @param MlgInfSgmtSeqNo  the value for PBCRS_REPORT_MLGINFSGMT.MLGINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMlgInfSgmtSeqNo(String MlgInfSgmtSeqNo) {
		this.MlgInfSgmtSeqNo = MlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MLGINFSGMT.MAILADDR
	 * @return  the value of PBCRS_REPORT_MLGINFSGMT.MAILADDR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMailAddr() {
		return MailAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MLGINFSGMT.MAILADDR
	 * @param MailAddr  the value for PBCRS_REPORT_MLGINFSGMT.MAILADDR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMailAddr(String MailAddr) {
		this.MailAddr = MailAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MLGINFSGMT.MAILPC
	 * @return  the value of PBCRS_REPORT_MLGINFSGMT.MAILPC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMailPc() {
		return MailPc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MLGINFSGMT.MAILPC
	 * @param MailPc  the value for PBCRS_REPORT_MLGINFSGMT.MAILPC
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMailPc(String MailPc) {
		this.MailPc = MailPc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MLGINFSGMT.MAILDIST
	 * @return  the value of PBCRS_REPORT_MLGINFSGMT.MAILDIST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMailDist() {
		return MailDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MLGINFSGMT.MAILDIST
	 * @param MailDist  the value for PBCRS_REPORT_MLGINFSGMT.MAILDIST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMailDist(String MailDist) {
		this.MailDist = MailDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MLGINFSGMT.MLGINFOUPDATE
	 * @return  the value of PBCRS_REPORT_MLGINFSGMT.MLGINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMlgInfoUpDate() {
		return MlgInfoUpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MLGINFSGMT.MLGINFOUPDATE
	 * @param MlgInfoUpDate  the value for PBCRS_REPORT_MLGINFSGMT.MLGINFOUPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMlgInfoUpDate(String MlgInfoUpDate) {
		this.MlgInfoUpDate = MlgInfoUpDate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 3176275517021187083L;
}