package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("AcctMthlyBlgInfSgmt")
public class PbcrsReportAccmthblginfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -6311389377098116219L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTMTHLYBLGINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctMthlyBlgInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.MONTH
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.SETTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String SettDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctBal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.PRIDACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PridAcctBal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.USEDAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String UsedAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.NOTISUBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String NotIsuBal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.REMREPPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RemRepPrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FiveCate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FiveCateAdjDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RpyStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYPRCT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RpyPrct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OverdPrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.TOTOVERD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String TotOverd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OverdPrinc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED31_60PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Oved31_60Princ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED61_90PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Oved61_90Princ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED91_180PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Oved91_180Princ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDPRINC180
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OvedPrinc180;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDRAWBAOVE180
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OvedrawBaOve180;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.CURRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CurRpyAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACTRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ActRpyAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.LATRPYDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String LatRpyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CloseDate;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	
	@XStreamOmitField
	private String ParagraphDel;
	
	
	 public String getParagraphDel() {
		return ParagraphDel;
	}

	public void setParagraphDel(String paragraphDel) {
		ParagraphDel = paragraphDel;
	}

	/**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTMTHLYBLGINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTMTHLYBLGINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctMthlyBlgInfSgmtSeqNo() {
		return AcctMthlyBlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTMTHLYBLGINFSGMTSEQNO
	 * @param AcctMthlyBlgInfSgmtSeqNo  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTMTHLYBLGINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctMthlyBlgInfSgmtSeqNo(String AcctMthlyBlgInfSgmtSeqNo) {
		this.AcctMthlyBlgInfSgmtSeqNo = AcctMthlyBlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.MONTH
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.MONTH
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMonth() {
		return Month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.MONTH
	 * @param Month  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.MONTH
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMonth(String Month) {
		this.Month = Month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.SETTDATE
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.SETTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getSettDate() {
		return SettDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.SETTDATE
	 * @param SettDate  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.SETTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setSettDate(String SettDate) {
		this.SettDate = SettDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTSTATUS
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctStatus() {
		return AcctStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTSTATUS
	 * @param AcctStatus  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctStatus(String AcctStatus) {
		this.AcctStatus = AcctStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTBAL
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctBal() {
		return AcctBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTBAL
	 * @param AcctBal  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.ACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctBal(String AcctBal) {
		this.AcctBal = AcctBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.PRIDACCTBAL
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.PRIDACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPridAcctBal() {
		return PridAcctBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.PRIDACCTBAL
	 * @param PridAcctBal  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.PRIDACCTBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPridAcctBal(String PridAcctBal) {
		this.PridAcctBal = PridAcctBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.USEDAMT
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.USEDAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getUsedAmt() {
		return UsedAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.USEDAMT
	 * @param UsedAmt  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.USEDAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setUsedAmt(String UsedAmt) {
		this.UsedAmt = UsedAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.NOTISUBAL
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.NOTISUBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getNotIsuBal() {
		return NotIsuBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.NOTISUBAL
	 * @param NotIsuBal  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.NOTISUBAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setNotIsuBal(String NotIsuBal) {
		this.NotIsuBal = NotIsuBal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.REMREPPRD
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.REMREPPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRemRepPrd() {
		return RemRepPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.REMREPPRD
	 * @param RemRepPrd  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.REMREPPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRemRepPrd(String RemRepPrd) {
		this.RemRepPrd = RemRepPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATE
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFiveCate() {
		return FiveCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATE
	 * @param FiveCate  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFiveCate(String FiveCate) {
		this.FiveCate = FiveCate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATEADJDATE
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFiveCateAdjDate() {
		return FiveCateAdjDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATEADJDATE
	 * @param FiveCateAdjDate  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.FIVECATEADJDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFiveCateAdjDate(String FiveCateAdjDate) {
		this.FiveCateAdjDate = FiveCateAdjDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYSTATUS
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRpyStatus() {
		return RpyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYSTATUS
	 * @param RpyStatus  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYSTATUS
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRpyStatus(String RpyStatus) {
		this.RpyStatus = RpyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYPRCT
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYPRCT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRpyPrct() {
		return RpyPrct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYPRCT
	 * @param RpyPrct  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.RPYPRCT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRpyPrct(String RpyPrct) {
		this.RpyPrct = RpyPrct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRD
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOverdPrd() {
		return OverdPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRD
	 * @param OverdPrd  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOverdPrd(String OverdPrd) {
		this.OverdPrd = OverdPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.TOTOVERD
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.TOTOVERD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getTotOverd() {
		return TotOverd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.TOTOVERD
	 * @param TotOverd  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.TOTOVERD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setTotOverd(String TotOverd) {
		this.TotOverd = TotOverd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRINC
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOverdPrinc() {
		return OverdPrinc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRINC
	 * @param OverdPrinc  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVERDPRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOverdPrinc(String OverdPrinc) {
		this.OverdPrinc = OverdPrinc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED31_60PRINC
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED31_60PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOved31_60Princ() {
		return Oved31_60Princ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED31_60PRINC
	 * @param Oved31_60Princ  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED31_60PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOved31_60Princ(String Oved31_60Princ) {
		this.Oved31_60Princ = Oved31_60Princ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED61_90PRINC
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED61_90PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOved61_90Princ() {
		return Oved61_90Princ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED61_90PRINC
	 * @param Oved61_90Princ  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED61_90PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOved61_90Princ(String Oved61_90Princ) {
		this.Oved61_90Princ = Oved61_90Princ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED91_180PRINC
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED91_180PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOved91_180Princ() {
		return Oved91_180Princ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED91_180PRINC
	 * @param Oved91_180Princ  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVED91_180PRINC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOved91_180Princ(String Oved91_180Princ) {
		this.Oved91_180Princ = Oved91_180Princ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDPRINC180
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDPRINC180
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOvedPrinc180() {
		return OvedPrinc180;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDPRINC180
	 * @param OvedPrinc180  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDPRINC180
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOvedPrinc180(String OvedPrinc180) {
		this.OvedPrinc180 = OvedPrinc180;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDRAWBAOVE180
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDRAWBAOVE180
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOvedrawBaOve180() {
		return OvedrawBaOve180;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDRAWBAOVE180
	 * @param OvedrawBaOve180  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.OVEDRAWBAOVE180
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOvedrawBaOve180(String OvedrawBaOve180) {
		this.OvedrawBaOve180 = OvedrawBaOve180;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.CURRPYAMT
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.CURRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCurRpyAmt() {
		return CurRpyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.CURRPYAMT
	 * @param CurRpyAmt  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.CURRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCurRpyAmt(String CurRpyAmt) {
		this.CurRpyAmt = CurRpyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACTRPYAMT
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.ACTRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getActRpyAmt() {
		return ActRpyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.ACTRPYAMT
	 * @param ActRpyAmt  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.ACTRPYAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setActRpyAmt(String ActRpyAmt) {
		this.ActRpyAmt = ActRpyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.LATRPYDATE
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.LATRPYDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getLatRpyDate() {
		return LatRpyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.LATRPYDATE
	 * @param LatRpyDate  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.LATRPYDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setLatRpyDate(String LatRpyDate) {
		this.LatRpyDate = LatRpyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.CLOSEDATE
	 * @return  the value of PBCRS_REPORT_ACCMTHBLGINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCloseDate() {
		return CloseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCMTHBLGINFSGMT.CLOSEDATE
	 * @param CloseDate  the value for PBCRS_REPORT_ACCMTHBLGINFSGMT.CLOSEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCloseDate(String CloseDate) {
		this.CloseDate = CloseDate;
	}
}