package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("OtrRec")
public class PbcrsReportOtrrec implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7827874838025481728L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_OTRREC.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String ComRecInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_OTRREC.OTRRECSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String OtrRecSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_OTRREC.INFOIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfoIDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_OTRREC.GUARNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String GuarName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_OTRREC.GUARCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String GuarCertType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_OTRREC.GUARCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String GuarCertNum;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_OTRREC.COMRECINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_OTRREC.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getComRecInfSgmtSeqNo() {
		return ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_OTRREC.COMRECINFSGMTSEQNO
	 * @param ComRecInfSgmtSeqNo  the value for PBCRS_REPORT_OTRREC.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setComRecInfSgmtSeqNo(String ComRecInfSgmtSeqNo) {
		this.ComRecInfSgmtSeqNo = ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_OTRREC.OTRRECSEQNO
	 * @return  the value of PBCRS_REPORT_OTRREC.OTRRECSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOtrRecSeqNo() {
		return OtrRecSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_OTRREC.OTRRECSEQNO
	 * @param OtrRecSeqNo  the value for PBCRS_REPORT_OTRREC.OTRRECSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOtrRecSeqNo(String OtrRecSeqNo) {
		this.OtrRecSeqNo = OtrRecSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_OTRREC.INFOIDTYPE
	 * @return  the value of PBCRS_REPORT_OTRREC.INFOIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfoIDType() {
		return InfoIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_OTRREC.INFOIDTYPE
	 * @param InfoIDType  the value for PBCRS_REPORT_OTRREC.INFOIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfoIDType(String InfoIDType) {
		this.InfoIDType = InfoIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_OTRREC.GUARNAME
	 * @return  the value of PBCRS_REPORT_OTRREC.GUARNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuarName() {
		return GuarName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_OTRREC.GUARNAME
	 * @param GuarName  the value for PBCRS_REPORT_OTRREC.GUARNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuarName(String GuarName) {
		this.GuarName = GuarName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_OTRREC.GUARCERTTYPE
	 * @return  the value of PBCRS_REPORT_OTRREC.GUARCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuarCertType() {
		return GuarCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_OTRREC.GUARCERTTYPE
	 * @param GuarCertType  the value for PBCRS_REPORT_OTRREC.GUARCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuarCertType(String GuarCertType) {
		this.GuarCertType = GuarCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_OTRREC.GUARCERTNUM
	 * @return  the value of PBCRS_REPORT_OTRREC.GUARCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuarCertNum() {
		return GuarCertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_OTRREC.GUARCERTNUM
	 * @param GuarCertNum  the value for PBCRS_REPORT_OTRREC.GUARCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuarCertNum(String GuarCertNum) {
		this.GuarCertNum = GuarCertNum;
	}
}