package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("RltRepymtInfSgmt")
public class PbcrsReportGsrltrepinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5004770035283581701L;
	
	@XStreamImplicit
    private List<PbcrsReportGsrltrepymtinf> GsRltRepymtInf;
	
	public List<PbcrsReportGsrltrepymtinf> getGsRltRepymtInf() {
		return GsRltRepymtInf;
	}

	public void setGsRltRepymtInf(List<PbcrsReportGsrltrepymtinf> gsRltRepymtInf) {
		GsRltRepymtInf = gsRltRepymtInf;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String RltRepymtInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RltRepymtNm;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRltRepymtInfSgmtSeqNo() {
		return RltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @param RltRepymtInfSgmtSeqNo  the value for PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRltRepymtInfSgmtSeqNo(String RltRepymtInfSgmtSeqNo) {
		this.RltRepymtInfSgmtSeqNo = RltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTNM
	 * @return  the value of PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRltRepymtNm() {
		return RltRepymtNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTNM
	 * @param RltRepymtNm  the value for PBCRS_REPORT_GSRLTREPINFSGMT.RLTREPYMTNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRltRepymtNm(String RltRepymtNm) {
		this.RltRepymtNm = RltRepymtNm;
	}
}