package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("GuarAcctCredSgmt")
public class PbcrsReportGuaracctcredsgmt implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6077650132041186006L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GUARACCTCREDSGMT.GUARACCTCREDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuarAcctCredSgmtSeqNo;
	
	@XStreamOmitField
	private String ReportFlag;

	 
	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_GUARACCTCREDSGMT.MCC
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    private String Mcc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GUARACCTCREDSGMT.GUARACCTCREDSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_GUARACCTCREDSGMT.GUARACCTCREDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuarAcctCredSgmtSeqNo() {
        return GuarAcctCredSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GUARACCTCREDSGMT.GUARACCTCREDSGMTSEQNO
     *
     * @param GuarAcctCredSgmtSeqNo the value for PBCRS_REPORT_GUARACCTCREDSGMT.GUARACCTCREDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuarAcctCredSgmtSeqNo(String GuarAcctCredSgmtSeqNo) {
        this.GuarAcctCredSgmtSeqNo = GuarAcctCredSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_GUARACCTCREDSGMT.MCC
     *
     * @return the value of PBCRS_REPORT_GUARACCTCREDSGMT.MCC
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getMcc() {
        return Mcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_GUARACCTCREDSGMT.MCC
     *
     * @param Mcc the value for PBCRS_REPORT_GUARACCTCREDSGMT.MCC
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setMcc(String Mcc) {
        this.Mcc = Mcc;
    }
}