package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("InBasInf")
public class PbcrsReportInbasinfo implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.INBASINFOSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String SeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.BSSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String BsSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.IDSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String IDSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.FCSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String FcsInfSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.SPSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String SpsInfSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.EDUINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String EduInfSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.OCTPNINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String OctpnInfSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.REDNCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String RedncInfSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.MLGINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String MlgInfSgmtSeqNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INBASINFO.INCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String IncInfSgmtSeqNo;

	

	public String getSeqNo() {
		return SeqNo;
	}

	public void setSeqNo(String seqNo) {
		SeqNo = seqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.BSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.BSSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getBsSgmtSeqNo() {
		return BsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.BSSGMTSEQNO
	 * @param BsSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.BSSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setBsSgmtSeqNo(String BsSgmtSeqNo) {
		this.BsSgmtSeqNo = BsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.IDSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.IDSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getIDSgmtSeqNo() {
		return IDSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.IDSGMTSEQNO
	 * @param IDSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.IDSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setIDSgmtSeqNo(String IDSgmtSeqNo) {
		this.IDSgmtSeqNo = IDSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.FCSINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.FCSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getFcsInfSgmtSeqNo() {
		return FcsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.FCSINFSGMTSEQNO
	 * @param FcsInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.FCSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setFcsInfSgmtSeqNo(String FcsInfSgmtSeqNo) {
		this.FcsInfSgmtSeqNo = FcsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.SPSINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.SPSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getSpsInfSgmtSeqNo() {
		return SpsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.SPSINFSGMTSEQNO
	 * @param SpsInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.SPSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setSpsInfSgmtSeqNo(String SpsInfSgmtSeqNo) {
		this.SpsInfSgmtSeqNo = SpsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.EDUINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.EDUINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getEduInfSgmtSeqNo() {
		return EduInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.EDUINFSGMTSEQNO
	 * @param EduInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.EDUINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setEduInfSgmtSeqNo(String EduInfSgmtSeqNo) {
		this.EduInfSgmtSeqNo = EduInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.OCTPNINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.OCTPNINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getOctpnInfSgmtSeqNo() {
		return OctpnInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.OCTPNINFSGMTSEQNO
	 * @param OctpnInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.OCTPNINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setOctpnInfSgmtSeqNo(String OctpnInfSgmtSeqNo) {
		this.OctpnInfSgmtSeqNo = OctpnInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.REDNCINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.REDNCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getRedncInfSgmtSeqNo() {
		return RedncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.REDNCINFSGMTSEQNO
	 * @param RedncInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.REDNCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setRedncInfSgmtSeqNo(String RedncInfSgmtSeqNo) {
		this.RedncInfSgmtSeqNo = RedncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.MLGINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.MLGINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMlgInfSgmtSeqNo() {
		return MlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.MLGINFSGMTSEQNO
	 * @param MlgInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.MLGINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMlgInfSgmtSeqNo(String MlgInfSgmtSeqNo) {
		this.MlgInfSgmtSeqNo = MlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INBASINFO.INCINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INBASINFO.INCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getIncInfSgmtSeqNo() {
		return IncInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INBASINFO.INCINFSGMTSEQNO
	 * @param IncInfSgmtSeqNo  the value for PBCRS_REPORT_INBASINFO.INCINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setIncInfSgmtSeqNo(String IncInfSgmtSeqNo) {
		this.IncInfSgmtSeqNo = IncInfSgmtSeqNo;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 3981227528616784938L;

	@XStreamAlias("BsSgmt")
    private PbcrsReportBssgmt BsSgmt;
    
    @XStreamAlias("IDSgmt")
    private PbcrsReportIdsgmt IDSgmt;
    
    @XStreamAlias("FcsInfSgmt")
    private PbcrsReportFcsinfsgmt FcsInfSgmt;
    
    @XStreamAlias("SpsInfSgmt")
    private PbcrsReportSpsinfsgmt SpsInfSgmt;
    
    @XStreamAlias("EduInfSgmt")
    private PbcrsReportEduinfsgmt EduInfSgmt;
    
    @XStreamAlias("OctpnInfSgmt")
    private PbcrsReportOctpninfsgmt OctpnInfSgmt;
    
    @XStreamAlias("RedncInfSgmt")
    private PbcrsReportRedncinfsgmt RedncInfSgmt;
    
    @XStreamAlias("MlgInfSgmt")
    private PbcrsReportMlginfsgmt MlgInfSgmt;
    
    @XStreamAlias("IncInfSgmt")
    private PbcrsReportIncinfsgmt IncInfSgmt;

    public PbcrsReportBssgmt getBsSgmt() {
		return BsSgmt;
	}

	public void setBsSgmt(PbcrsReportBssgmt bsSgmt) {
		BsSgmt = bsSgmt;
	}

	public PbcrsReportIdsgmt getIDSgmt() {
		return IDSgmt;
	}

	public void setIDSgmt(PbcrsReportIdsgmt iDSgmt) {
		IDSgmt = iDSgmt;
	}

	public PbcrsReportFcsinfsgmt getFcsInfSgmt() {
		return FcsInfSgmt;
	}

	public void setFcsInfSgmt(PbcrsReportFcsinfsgmt fcsInfSgmt) {
		FcsInfSgmt = fcsInfSgmt;
	}

	public PbcrsReportSpsinfsgmt getSpsInfSgmt() {
		return SpsInfSgmt;
	}

	public void setSpsInfSgmt(PbcrsReportSpsinfsgmt spsInfSgmt) {
		SpsInfSgmt = spsInfSgmt;
	}

	public PbcrsReportEduinfsgmt getEduInfSgmt() {
		return EduInfSgmt;
	}

	public void setEduInfSgmt(PbcrsReportEduinfsgmt eduInfSgmt) {
		EduInfSgmt = eduInfSgmt;
	}

	public PbcrsReportOctpninfsgmt getOctpnInfSgmt() {
		return OctpnInfSgmt;
	}

	public void setOctpnInfSgmt(PbcrsReportOctpninfsgmt octpnInfSgmt) {
		OctpnInfSgmt = octpnInfSgmt;
	}

	public PbcrsReportRedncinfsgmt getRedncInfSgmt() {
		return RedncInfSgmt;
	}

	public void setRedncInfSgmt(PbcrsReportRedncinfsgmt redncInfSgmt) {
		RedncInfSgmt = redncInfSgmt;
	}

	public PbcrsReportMlginfsgmt getMlgInfSgmt() {
		return MlgInfSgmt;
	}

	public void setMlgInfSgmt(PbcrsReportMlginfsgmt mlgInfSgmt) {
		MlgInfSgmt = mlgInfSgmt;
	}

	
	public PbcrsReportIncinfsgmt getIncInfSgmt() {
		return IncInfSgmt;
	}

	public void setIncInfSgmt(PbcrsReportIncinfsgmt incInfSgmt) {
		IncInfSgmt = incInfSgmt;
	}
}