package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;


@XStreamAlias("InSecAcctIDCagsInf")
public class PbcrsReportInsecaccidcaginf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -6067936119660896398L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCIDCAGINF.INSECACCTIDCAGSINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InSecAcctIDCagsInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCIDCAGINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCIDCAGINF.ODBNESCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OdBnesCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCIDCAGINF.NWBNESCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String NwBnesCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.INSECACCTIDCAGSINFSEQNO
	 * @return  the value of PBCRS_REPORT_INSECACCIDCAGINF.INSECACCTIDCAGSINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInSecAcctIDCagsInfSeqNo() {
		return InSecAcctIDCagsInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.INSECACCTIDCAGSINFSEQNO
	 * @param InSecAcctIDCagsInfSeqNo  the value for PBCRS_REPORT_INSECACCIDCAGINF.INSECACCTIDCAGSINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInSecAcctIDCagsInfSeqNo(String InSecAcctIDCagsInfSeqNo) {
		this.InSecAcctIDCagsInfSeqNo = InSecAcctIDCagsInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INSECACCIDCAGINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INSECACCIDCAGINF.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.ODBNESCODE
	 * @return  the value of PBCRS_REPORT_INSECACCIDCAGINF.ODBNESCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOdBnesCode() {
		return OdBnesCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.ODBNESCODE
	 * @param OdBnesCode  the value for PBCRS_REPORT_INSECACCIDCAGINF.ODBNESCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOdBnesCode(String OdBnesCode) {
		this.OdBnesCode = OdBnesCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.NWBNESCODE
	 * @return  the value of PBCRS_REPORT_INSECACCIDCAGINF.NWBNESCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getNwBnesCode() {
		return NwBnesCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCIDCAGINF.NWBNESCODE
	 * @param NwBnesCode  the value for PBCRS_REPORT_INSECACCIDCAGINF.NWBNESCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setNwBnesCode(String NwBnesCode) {
		this.NwBnesCode = NwBnesCode;
	}
}