package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("RltRepymtInfSgmt")
public class PbcrsReportEnrltrepinfsgmt {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	@XStreamOmitField
	private String RltRepymtInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTNM
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	private String RltRepymtNm;
	
    @XStreamOmitField
	private String ReportFlag;
	    
	    
	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	
	@XStreamImplicit
	private List<PbcrsReportEnrltrepymtinf> RltRepymtInf;
	public String getRltRepymtInfSgmtSeqNo() {
		return RltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @param RltRepymtInfSgmtSeqNo  the value for PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	public void setRltRepymtInfSgmtSeqNo(String RltRepymtInfSgmtSeqNo) {
		this.RltRepymtInfSgmtSeqNo = RltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTNM
	 * @return  the value of PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTNM
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	public String getRltRepymtNm() {
		return RltRepymtNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTNM
	 * @param RltRepymtNm  the value for PBCRS_REPORT_ENRLTREPINFSGMT.RLTREPYMTNM
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	public void setRltRepymtNm(String RltRepymtNm) {
		this.RltRepymtNm = RltRepymtNm;
	}

	public List<PbcrsReportEnrltrepymtinf> getRltRepymtInf() {
		return RltRepymtInf;
	}

	public void setRltRepymtInf(List<PbcrsReportEnrltrepymtinf> rltRepymtInf) {
		RltRepymtInf = rltRepymtInf;
	}

	
    
}