package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
/**
 * 企业利润及利润分配整笔删除
 */
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("IncomeStatementProfitAppropriationDlt")
public class PbcrsReportIncstaproappdlt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.INCSTAPROAPPDLTSEQNO
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
	@XStreamOmitField
    private String IncStaProAppDltSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.INFRECTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTNAME
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String EntName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String EntCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTNUM
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String EntCertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETYEAR
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String SheetYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String SheetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPEDIVIDE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    private String SheetTypeDivide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCSTAPROAPPDLT.RPTDATE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    @XStreamOmitField
    private String RptDate;
    
    @XStreamOmitField
    private String  SourceSys;
    @XStreamOmitField
    private String ReportFlag;
    
    @XStreamOmitField
    private String orgCode;
    
    

    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.INCSTAPROAPPDLTSEQNO
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.INCSTAPROAPPDLTSEQNO
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getIncStaProAppDltSeqNo() {
        return IncStaProAppDltSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.INCSTAPROAPPDLTSEQNO
     *
     * @param IncStaProAppDltSeqNo the value for PBCRS_REPORT_INCSTAPROAPPDLT.INCSTAPROAPPDLTSEQNO
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setIncStaProAppDltSeqNo(String IncStaProAppDltSeqNo) {
        this.IncStaProAppDltSeqNo = IncStaProAppDltSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.INFRECTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_INCSTAPROAPPDLT.INFRECTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTNAME
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.ENTNAME
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getEntName() {
        return EntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTNAME
     *
     * @param EntName the value for PBCRS_REPORT_INCSTAPROAPPDLT.ENTNAME
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setEntName(String EntName) {
        this.EntName = EntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTTYPE
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getEntCertType() {
        return EntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTTYPE
     *
     * @param EntCertType the value for PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setEntCertType(String EntCertType) {
        this.EntCertType = EntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTNUM
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTNUM
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getEntCertNum() {
        return EntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTNUM
     *
     * @param EntCertNum the value for PBCRS_REPORT_INCSTAPROAPPDLT.ENTCERTNUM
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setEntCertNum(String EntCertNum) {
        this.EntCertNum = EntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETYEAR
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.SHEETYEAR
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getSheetYear() {
        return SheetYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETYEAR
     *
     * @param SheetYear the value for PBCRS_REPORT_INCSTAPROAPPDLT.SHEETYEAR
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setSheetYear(String SheetYear) {
        this.SheetYear = SheetYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPE
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getSheetType() {
        return SheetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPE
     *
     * @param SheetType the value for PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setSheetType(String SheetType) {
        this.SheetType = SheetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPEDIVIDE
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPEDIVIDE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getSheetTypeDivide() {
        return SheetTypeDivide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPEDIVIDE
     *
     * @param SheetTypeDivide the value for PBCRS_REPORT_INCSTAPROAPPDLT.SHEETTYPEDIVIDE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setSheetTypeDivide(String SheetTypeDivide) {
        this.SheetTypeDivide = SheetTypeDivide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.RPTDATE
     *
     * @return the value of PBCRS_REPORT_INCSTAPROAPPDLT.RPTDATE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public String getRptDate() {
        return RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCSTAPROAPPDLT.RPTDATE
     *
     * @param RptDate the value for PBCRS_REPORT_INCSTAPROAPPDLT.RPTDATE
     *
     * @mbggenerated Tue Mar 26 13:52:05 CST 2019
     */
    public void setRptDate(String RptDate) {
        this.RptDate = RptDate;
    }

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
    
}