package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnSecAcctEntDelSgmt")
public class PbcrsReportEnsecaccdelsgmt implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3382011383890392246L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCDELSGMT.ENSECACCTENTDELSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
	@XStreamOmitField
    private String EnSecAcctEntDelSgmtSeqNo;
	
    @XStreamOmitField
    private String  SourceSys;
    @XStreamOmitField
    private String ReportFlag;

    @XStreamOmitField
    private String orgCode;
    
    
    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCDELSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCDELSGMT.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    private String DelRecCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCDELSGMT.ENSECACCTENTDELSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCDELSGMT.ENSECACCTENTDELSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    public String getEnSecAcctEntDelSgmtSeqNo() {
        return EnSecAcctEntDelSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCDELSGMT.ENSECACCTENTDELSGMTSEQNO
     *
     * @param EnSecAcctEntDelSgmtSeqNo the value for PBCRS_REPORT_ENSECACCDELSGMT.ENSECACCTENTDELSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    public void setEnSecAcctEntDelSgmtSeqNo(String EnSecAcctEntDelSgmtSeqNo) {
        this.EnSecAcctEntDelSgmtSeqNo = EnSecAcctEntDelSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCDELSGMT.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENSECACCDELSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCDELSGMT.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENSECACCDELSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCDELSGMT.DELRECCODE
     *
     * @return the value of PBCRS_REPORT_ENSECACCDELSGMT.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    public String getDelRecCode() {
        return DelRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCDELSGMT.DELRECCODE
     *
     * @param DelRecCode the value for PBCRS_REPORT_ENSECACCDELSGMT.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 11:29:16 CST 2019
     */
    public void setDelRecCode(String DelRecCode) {
        this.DelRecCode = DelRecCode;
    }

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
}