package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("MotgaCltalCtrctInfSgmt")
public class PbcrsReportMotcltctrinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2290907161775110293L;
	
	@XStreamImplicit
    private List<PbcrsReportCccinf> CccInf;
	
	public List<PbcrsReportCccinf> getCccInf() {
		return CccInf;
	}

	@XStreamOmitField
	private String ReportFlag;
	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
	public void setCccInf(List<PbcrsReportCccinf> cccInf) {
		CccInf = cccInf;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTCTRINFSGMT.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String MotgaCltalCtrctInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTCTRINFSGMT.CCNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CcNm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINFSGMT.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINFSGMT.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMotgaCltalCtrctInfSgmtSeqNo() {
		return MotgaCltalCtrctInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINFSGMT.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @param MotgaCltalCtrctInfSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTCTRINFSGMT.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMotgaCltalCtrctInfSgmtSeqNo(String MotgaCltalCtrctInfSgmtSeqNo) {
		this.MotgaCltalCtrctInfSgmtSeqNo = MotgaCltalCtrctInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTCTRINFSGMT.CCNM
	 * @return  the value of PBCRS_REPORT_MOTCLTCTRINFSGMT.CCNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCcNm() {
		return CcNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTCTRINFSGMT.CCNM
	 * @param CcNm  the value for PBCRS_REPORT_MOTCLTCTRINFSGMT.CCNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCcNm(String CcNm) {
		this.CcNm = CcNm;
	}
}