package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("EnCtfItgInf")
public class PbcrsReportEnctfitginf implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8953120875207220145L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.ENCTFITGINFSEQNO
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
	@XStreamOmitField
    private String EnCtfItgInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.ENTNAME
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String EntName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.ENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String EntCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.ENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String EntCertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.OTHENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String OthEntCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.OTHENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String OthEntCertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.CERTASSFLG
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String CertAssFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTFITGINF.RPTDATE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    private String RptDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.ENCTFITGINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.ENCTFITGINFSEQNO
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getEnCtfItgInfSeqNo() {
        return EnCtfItgInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.ENCTFITGINFSEQNO
     *
     * @param EnCtfItgInfSeqNo the value for PBCRS_REPORT_ENCTFITGINF.ENCTFITGINFSEQNO
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setEnCtfItgInfSeqNo(String EnCtfItgInfSeqNo) {
        this.EnCtfItgInfSeqNo = EnCtfItgInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENCTFITGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.ENTNAME
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.ENTNAME
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getEntName() {
        return EntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.ENTNAME
     *
     * @param EntName the value for PBCRS_REPORT_ENCTFITGINF.ENTNAME
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setEntName(String EntName) {
        this.EntName = EntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.ENTCERTTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.ENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getEntCertType() {
        return EntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.ENTCERTTYPE
     *
     * @param EntCertType the value for PBCRS_REPORT_ENCTFITGINF.ENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setEntCertType(String EntCertType) {
        this.EntCertType = EntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.ENTCERTNUM
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.ENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getEntCertNum() {
        return EntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.ENTCERTNUM
     *
     * @param EntCertNum the value for PBCRS_REPORT_ENCTFITGINF.ENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setEntCertNum(String EntCertNum) {
        this.EntCertNum = EntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.OTHENTCERTTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.OTHENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getOthEntCertType() {
        return OthEntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.OTHENTCERTTYPE
     *
     * @param OthEntCertType the value for PBCRS_REPORT_ENCTFITGINF.OTHENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setOthEntCertType(String OthEntCertType) {
        this.OthEntCertType = OthEntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.OTHENTCERTNUM
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.OTHENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getOthEntCertNum() {
        return OthEntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.OTHENTCERTNUM
     *
     * @param OthEntCertNum the value for PBCRS_REPORT_ENCTFITGINF.OTHENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setOthEntCertNum(String OthEntCertNum) {
        this.OthEntCertNum = OthEntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.CERTASSFLG
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.CERTASSFLG
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getCertAssFlg() {
        return CertAssFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.CERTASSFLG
     *
     * @param CertAssFlg the value for PBCRS_REPORT_ENCTFITGINF.CERTASSFLG
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setCertAssFlg(String CertAssFlg) {
        this.CertAssFlg = CertAssFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTFITGINF.RPTDATE
     *
     * @return the value of PBCRS_REPORT_ENCTFITGINF.RPTDATE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public String getRptDate() {
        return RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTFITGINF.RPTDATE
     *
     * @param RptDate the value for PBCRS_REPORT_ENCTFITGINF.RPTDATE
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    public void setRptDate(String RptDate) {
        this.RptDate = RptDate;
    }
}