package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("GuarMotgaCltalCtrctInfSgmt")
public class PbcrsReportGuamotcltctrsgmt implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7739140823227094024L;
	
	@XStreamImplicit
    private List<PbcrsReportGuacccinf> GuaCccInf;
	
	public List<PbcrsReportGuacccinf> getGuaCccInf() {
		return GuaCccInf;
	}

	public void setGuaCccInf(List<PbcrsReportGuacccinf> guaCccInf) {
		GuaCccInf = guaCccInf;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column
	 * PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * 
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String GuarMotgaCltalCtrctInfSgmtSeqN;
	             
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * 
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	private String CcNm;
	
	@XStreamImplicit
	private List<PbcrsReportCccinf> CccInf;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * 
	 * @return the value of
	 *         PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * 
	 * @return the value of PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCcNm() {
		return CcNm;
	}

	public String getGuarMotgaCltalCtrctInfSgmtSeqN() {
		return GuarMotgaCltalCtrctInfSgmtSeqN;
	}

	public void setGuarMotgaCltalCtrctInfSgmtSeqN(String guarMotgaCltalCtrctInfSgmtSeqN) {
		GuarMotgaCltalCtrctInfSgmtSeqN = guarMotgaCltalCtrctInfSgmtSeqN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * 
	 * @param CcNm
	 *            the value for PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCcNm(String CcNm) {
		this.CcNm = CcNm;
	}

	public List<PbcrsReportCccinf> getCccInf() {
		return CccInf;
	}

	public void setCccInf(List<PbcrsReportCccinf> cccInf) {
		CccInf = cccInf;
	}

}