package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("ComRecInfSgmt")
public class PbcrsReportComrecinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4812871425113866375L;
	
	@XStreamImplicit
    private List<PbcrsReportOtrrec> OtrRec;
	
	public List<PbcrsReportOtrrec> getOtrRec() {
		return OtrRec;
	}

	public void setOtrRec(List<PbcrsReportOtrrec> otrRec) {
		OtrRec = otrRec;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_COMRECINFSGMT.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String ComRecInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_COMRECINFSGMT.GRTDNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String GrtdNm;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_COMRECINFSGMT.COMRECINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_COMRECINFSGMT.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getComRecInfSgmtSeqNo() {
		return ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_COMRECINFSGMT.COMRECINFSGMTSEQNO
	 * @param ComRecInfSgmtSeqNo  the value for PBCRS_REPORT_COMRECINFSGMT.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setComRecInfSgmtSeqNo(String ComRecInfSgmtSeqNo) {
		this.ComRecInfSgmtSeqNo = ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_COMRECINFSGMT.GRTDNM
	 * @return  the value of PBCRS_REPORT_COMRECINFSGMT.GRTDNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGrtdNm() {
		return GrtdNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_COMRECINFSGMT.GRTDNM
	 * @param GrtdNm  the value for PBCRS_REPORT_COMRECINFSGMT.GRTDNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGrtdNm(String GrtdNm) {
		this.GrtdNm = GrtdNm;
	}
}