package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("CtrctCertRel")
public class PbcrsReportCtrctcertrel implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -4769567086380273999L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CtrctCertRelSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CtrctCertRelSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTREL.BRERTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String BrerType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CertRelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CertRelIDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELIDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CertRelIDNum;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCtrctCertRelSgmtSeqNo() {
		return CtrctCertRelSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
	 * @param CtrctCertRelSgmtSeqNo  the value for PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCtrctCertRelSgmtSeqNo(String CtrctCertRelSgmtSeqNo) {
		this.CtrctCertRelSgmtSeqNo = CtrctCertRelSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSEQNO
	 * @return  the value of PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCtrctCertRelSeqNo() {
		return CtrctCertRelSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSEQNO
	 * @param CtrctCertRelSeqNo  the value for PBCRS_REPORT_CTRCTCERTREL.CTRCTCERTRELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCtrctCertRelSeqNo(String CtrctCertRelSeqNo) {
		this.CtrctCertRelSeqNo = CtrctCertRelSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTREL.BRERTYPE
	 * @return  the value of PBCRS_REPORT_CTRCTCERTREL.BRERTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getBrerType() {
		return BrerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTREL.BRERTYPE
	 * @param BrerType  the value for PBCRS_REPORT_CTRCTCERTREL.BRERTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setBrerType(String BrerType) {
		this.BrerType = BrerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELNAME
	 * @return  the value of PBCRS_REPORT_CTRCTCERTREL.CERTRELNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCertRelName() {
		return CertRelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELNAME
	 * @param CertRelName  the value for PBCRS_REPORT_CTRCTCERTREL.CERTRELNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCertRelName(String CertRelName) {
		this.CertRelName = CertRelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELIDTYPE
	 * @return  the value of PBCRS_REPORT_CTRCTCERTREL.CERTRELIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCertRelIDType() {
		return CertRelIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELIDTYPE
	 * @param CertRelIDType  the value for PBCRS_REPORT_CTRCTCERTREL.CERTRELIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCertRelIDType(String CertRelIDType) {
		this.CertRelIDType = CertRelIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELIDNUM
	 * @return  the value of PBCRS_REPORT_CTRCTCERTREL.CERTRELIDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCertRelIDNum() {
		return CertRelIDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTCERTREL.CERTRELIDNUM
	 * @param CertRelIDNum  the value for PBCRS_REPORT_CTRCTCERTREL.CERTRELIDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCertRelIDNum(String CertRelIDNum) {
		this.CertRelIDNum = CertRelIDNum;
	}
}