package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnSecAcctInf")
public class PbcrsReportEnsecacctinf implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 197416680568019638L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.ENSECACCTINFSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String EnSecAcctInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTBSSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuarAcctBsSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTBSINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuarAcctBsInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String RltRepymtInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTCREDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuarAcctCredSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.GUAMOTCLTLCTRINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuaMotCltlCtrInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTINF.GUARRLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamOmitField
    private String GuarRltRepymtInfSgmtSeqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.ENSECACCTINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.ENSECACCTINFSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
	@XStreamAlias("GuarAcctBsSgmt")
	private PbcrsReportEnguaracctbssgmt GuarAcctBsSgmt;
	@XStreamAlias("GuarAcctBsInfSgmt")
	private PbcrsReportEnguaaccbsinfsgmt GuarAcctBsInfSgmt;
	@XStreamAlias("RltRepymtInfSgmt")
	private PbcrsReportGserltrepinfsgmt RltRepymtInfSgmt;
	@XStreamAlias("GuarMotgaCltalCtrctInfSgmt")
	private PbcrsReportGuamotcltctrsgmt GuarMotgaCltalCtrctInfSgmt;
	@XStreamAlias("GuarAcctCredSgmt")
	private PbcrsReportGuaracctcredsgmt GuarAcctCredSgmt;
	@XStreamAlias("GuarRltRepymtInfSgmt")
	private PbcrsReportGuarltrepinfsgmt GuarRltRepymtInfSgmt;

	
    public String getEnSecAcctInfSeqNo() {
        return EnSecAcctInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.ENSECACCTINFSEQNO
     *
     * @param EnSecAcctInfSeqNo the value for PBCRS_REPORT_ENSECACCTINF.ENSECACCTINFSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setEnSecAcctInfSeqNo(String EnSecAcctInfSeqNo) {
        this.EnSecAcctInfSeqNo = EnSecAcctInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTBSSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.GUARACCTBSSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuarAcctBsSgmtSeqNo() {
        return GuarAcctBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTBSSGMTSEQNO
     *
     * @param GuarAcctBsSgmtSeqNo the value for PBCRS_REPORT_ENSECACCTINF.GUARACCTBSSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuarAcctBsSgmtSeqNo(String GuarAcctBsSgmtSeqNo) {
        this.GuarAcctBsSgmtSeqNo = GuarAcctBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTBSINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.GUARACCTBSINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuarAcctBsInfSgmtSeqNo() {
        return GuarAcctBsInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTBSINFSGMTSEQNO
     *
     * @param GuarAcctBsInfSgmtSeqNo the value for PBCRS_REPORT_ENSECACCTINF.GUARACCTBSINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuarAcctBsInfSgmtSeqNo(String GuarAcctBsInfSgmtSeqNo) {
        this.GuarAcctBsInfSgmtSeqNo = GuarAcctBsInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getRltRepymtInfSgmtSeqNo() {
        return RltRepymtInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @param RltRepymtInfSgmtSeqNo the value for PBCRS_REPORT_ENSECACCTINF.RLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setRltRepymtInfSgmtSeqNo(String RltRepymtInfSgmtSeqNo) {
        this.RltRepymtInfSgmtSeqNo = RltRepymtInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTCREDSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.GUARACCTCREDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuarAcctCredSgmtSeqNo() {
        return GuarAcctCredSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARACCTCREDSGMTSEQNO
     *
     * @param GuarAcctCredSgmtSeqNo the value for PBCRS_REPORT_ENSECACCTINF.GUARACCTCREDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuarAcctCredSgmtSeqNo(String GuarAcctCredSgmtSeqNo) {
        this.GuarAcctCredSgmtSeqNo = GuarAcctCredSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.GUAMOTCLTLCTRINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.GUAMOTCLTLCTRINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuaMotCltlCtrInfSgmtSeqNo() {
        return GuaMotCltlCtrInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.GUAMOTCLTLCTRINFSGMTSEQNO
     *
     * @param GuaMotCltlCtrInfSgmtSeqNo the value for PBCRS_REPORT_ENSECACCTINF.GUAMOTCLTLCTRINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuaMotCltlCtrInfSgmtSeqNo(String GuaMotCltlCtrInfSgmtSeqNo) {
        this.GuaMotCltlCtrInfSgmtSeqNo = GuaMotCltlCtrInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARRLTREPYMTINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTINF.GUARRLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public String getGuarRltRepymtInfSgmtSeqNo() {
        return GuarRltRepymtInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTINF.GUARRLTREPYMTINFSGMTSEQNO
     *
     * @param GuarRltRepymtInfSgmtSeqNo the value for PBCRS_REPORT_ENSECACCTINF.GUARRLTREPYMTINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    public void setGuarRltRepymtInfSgmtSeqNo(String GuarRltRepymtInfSgmtSeqNo) {
        this.GuarRltRepymtInfSgmtSeqNo = GuarRltRepymtInfSgmtSeqNo;
    }

	public PbcrsReportEnguaracctbssgmt getGuarAcctBsSgmt() {
		return GuarAcctBsSgmt;
	}

	public void setGuarAcctBsSgmt(PbcrsReportEnguaracctbssgmt guarAcctBsSgmt) {
		GuarAcctBsSgmt = guarAcctBsSgmt;
	}

	public PbcrsReportEnguaaccbsinfsgmt getGuarAcctBsInfSgmt() {
		return GuarAcctBsInfSgmt;
	}

	public void setGuarAcctBsInfSgmt(PbcrsReportEnguaaccbsinfsgmt guarAcctBsInfSgmt) {
		GuarAcctBsInfSgmt = guarAcctBsInfSgmt;
	}

	public PbcrsReportGserltrepinfsgmt getRltRepymtInfSgmt() {
		return RltRepymtInfSgmt;
	}

	public void setRltRepymtInfSgmt(PbcrsReportGserltrepinfsgmt rltRepymtInfSgmt) {
		RltRepymtInfSgmt = rltRepymtInfSgmt;
	}

	public PbcrsReportGuamotcltctrsgmt getGuarMotgaCltalCtrctInfSgmt() {
		return GuarMotgaCltalCtrctInfSgmt;
	}

	public void setGuarMotgaCltalCtrctInfSgmt(
			PbcrsReportGuamotcltctrsgmt guarMotgaCltalCtrctInfSgmt) {
		GuarMotgaCltalCtrctInfSgmt = guarMotgaCltalCtrctInfSgmt;
	}

	public PbcrsReportGuaracctcredsgmt getGuarAcctCredSgmt() {
		return GuarAcctCredSgmt;
	}

	public void setGuarAcctCredSgmt(PbcrsReportGuaracctcredsgmt guarAcctCredSgmt) {
		GuarAcctCredSgmt = guarAcctCredSgmt;
	}

	public PbcrsReportGuarltrepinfsgmt getGuarRltRepymtInfSgmt() {
		return GuarRltRepymtInfSgmt;
	}

	public void setGuarRltRepymtInfSgmt(
			PbcrsReportGuarltrepinfsgmt guarRltRepymtInfSgmt) {
		GuarRltRepymtInfSgmt = guarRltRepymtInfSgmt;
	}
    
}
