package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("IDSgmt")
public class PbcrsReportEnbasinfidsgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFIDSGMT.IDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
	@XStreamOmitField
    private String IDSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFIDSGMT.IDNM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String IDNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBASINFIDSGMT.IDINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String IDInfoUpDate;
    
    @XStreamOmitField
    private String ReportFlag;
    
    public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFIDSGMT.IDSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENBASINFIDSGMT.IDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    @XStreamImplicit
    private List<PbcrsReportEnbasinfidrec> fidrecList;
    
    public List<PbcrsReportEnbasinfidrec> getFidrecList() {
		return fidrecList;
	}

	public void setFidrecList(List<PbcrsReportEnbasinfidrec> fidrecList) {
		this.fidrecList = fidrecList;
	}

	public String getIDSgmtSeqNo() {
        return IDSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFIDSGMT.IDSGMTSEQNO
     *
     * @param IDSgmtSeqNo the value for PBCRS_REPORT_ENBASINFIDSGMT.IDSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setIDSgmtSeqNo(String IDSgmtSeqNo) {
        this.IDSgmtSeqNo = IDSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFIDSGMT.IDNM
     *
     * @return the value of PBCRS_REPORT_ENBASINFIDSGMT.IDNM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getIDNm() {
        return IDNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFIDSGMT.IDNM
     *
     * @param IDNm the value for PBCRS_REPORT_ENBASINFIDSGMT.IDNM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setIDNm(String IDNm) {
        this.IDNm = IDNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBASINFIDSGMT.IDINFOUPDATE
     *
     * @return the value of PBCRS_REPORT_ENBASINFIDSGMT.IDINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getIDInfoUpDate() {
        return IDInfoUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBASINFIDSGMT.IDINFOUPDATE
     *
     * @param IDInfoUpDate the value for PBCRS_REPORT_ENBASINFIDSGMT.IDINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setIDInfoUpDate(String IDInfoUpDate) {
        this.IDInfoUpDate = IDInfoUpDate;
    }

	
}