package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnAcctInfIDCagsInf")
public class PbcrsReportEnaccinfidcaginf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFIDCAGINF.ENACCTINFIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
	@XStreamOmitField
    private String EnAcctInfIDCagsInfSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFIDCAGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFIDCAGINF.ODBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    private String OdBnesCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCINFIDCAGINF.NWBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    private String NwBnesCode;
    
    @XStreamOmitField
    private String reportFlag;
    
    @XStreamOmitField
    private String orgCode;
    
    
    
    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getReportFlag() {
		return reportFlag;
	}

	public void setReportFlag(String reportFlag) {
		this.reportFlag = reportFlag;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.ENACCTINFIDCAGSINFSEQNO
     *
     * @return the value of PBCRS_REPORT_ENACCINFIDCAGINF.ENACCTINFIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public String getEnAcctInfIDCagsInfSeqNo() {
        return EnAcctInfIDCagsInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.ENACCTINFIDCAGSINFSEQNO
     *
     * @param EnAcctInfIDCagsInfSeqNo the value for PBCRS_REPORT_ENACCINFIDCAGINF.ENACCTINFIDCAGSINFSEQNO
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public void setEnAcctInfIDCagsInfSeqNo(String EnAcctInfIDCagsInfSeqNo) {
        this.EnAcctInfIDCagsInfSeqNo = EnAcctInfIDCagsInfSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENACCINFIDCAGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENACCINFIDCAGINF.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.ODBNESCODE
     *
     * @return the value of PBCRS_REPORT_ENACCINFIDCAGINF.ODBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public String getOdBnesCode() {
        return OdBnesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.ODBNESCODE
     *
     * @param OdBnesCode the value for PBCRS_REPORT_ENACCINFIDCAGINF.ODBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public void setOdBnesCode(String OdBnesCode) {
        this.OdBnesCode = OdBnesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.NWBNESCODE
     *
     * @return the value of PBCRS_REPORT_ENACCINFIDCAGINF.NWBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public String getNwBnesCode() {
        return NwBnesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCINFIDCAGINF.NWBNESCODE
     *
     * @param NwBnesCode the value for PBCRS_REPORT_ENACCINFIDCAGINF.NWBNESCODE
     *
     * @mbggenerated Fri Mar 15 11:11:26 CST 2019
     */
    public void setNwBnesCode(String NwBnesCode) {
        this.NwBnesCode = NwBnesCode;
    }
}