package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("ActuCotrlInfSgmt")
public class PbcrsReportActucotrlinfsgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
	@XStreamOmitField
    private String ActuCotrlInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLNM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String ActuCotrlNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    private String ActuCotrlInfoUpDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    
    @XStreamOmitField
    private String ReportFlag;
    
    public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
    
    @XStreamImplicit
    private List<PbcrsReportEnbasinfactcotinf> actcotinfList;
    
    public List<PbcrsReportEnbasinfactcotinf> getActcotinfList() {
		return actcotinfList;
	}

	public void setActcotinfList(List<PbcrsReportEnbasinfactcotinf> actcotinfList) {
		this.actcotinfList = actcotinfList;
	}

	public String getActuCotrlInfSgmtSeqNo() {
        return ActuCotrlInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFSGMTSEQNO
     *
     * @param ActuCotrlInfSgmtSeqNo the value for PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFSGMTSEQNO
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setActuCotrlInfSgmtSeqNo(String ActuCotrlInfSgmtSeqNo) {
        this.ActuCotrlInfSgmtSeqNo = ActuCotrlInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLNM
     *
     * @return the value of PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLNM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getActuCotrlNm() {
        return ActuCotrlNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLNM
     *
     * @param ActuCotrlNm the value for PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLNM
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setActuCotrlNm(String ActuCotrlNm) {
        this.ActuCotrlNm = ActuCotrlNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFOUPDATE
     *
     * @return the value of PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public String getActuCotrlInfoUpDate() {
        return ActuCotrlInfoUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFOUPDATE
     *
     * @param ActuCotrlInfoUpDate the value for PBCRS_REPORT_ACTUCOTRLINFSGMT.ACTUCOTRLINFOUPDATE
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    public void setActuCotrlInfoUpDate(String ActuCotrlInfoUpDate) {
        this.ActuCotrlInfoUpDate = ActuCotrlInfoUpDate;
    }
}