package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("MdfcSgmt")
public class PbcrsReportInctrmdfmdfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8345840085205780611L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTREFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String MdfcSgmtRefSeqNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTSEQNO
	 * @param MdfcSgmtSeqNo  the value for PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	
	@XStreamAlias("CtrctBsSgmt")
	private PbcrsReportCtrctbssgmt PbcrsReportCtrctbssgmtList;
	@XStreamAlias("CreditLimSgmt")
	private PbcrsReportCreditlimsgmt PbcrsReportCreditLimSgmtList;
	
	
	
	
	public PbcrsReportCtrctbssgmt getPbcrsReportCtrctbssgmtList() {
		return PbcrsReportCtrctbssgmtList;
	}

	public void setPbcrsReportCtrctbssgmtList(PbcrsReportCtrctbssgmt pbcrsReportCtrctbssgmtList) {
		PbcrsReportCtrctbssgmtList = pbcrsReportCtrctbssgmtList;
	}

	public PbcrsReportCreditlimsgmt getPbcrsReportCreditLimSgmtList() {
		return PbcrsReportCreditLimSgmtList;
	}

	public void setPbcrsReportCreditLimSgmtList(PbcrsReportCreditlimsgmt pbcrsReportCreditLimSgmtList) {
		PbcrsReportCreditLimSgmtList = pbcrsReportCreditLimSgmtList;
	}

	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTREFSEQNO
	 * @return  the value of PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTREFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMdfcSgmtRefSeqNo() {
		return MdfcSgmtRefSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTREFSEQNO
	 * @param MdfcSgmtRefSeqNo  the value for PBCRS_REPORT_INCTRMDFMDFSGMT.MDFCSGMTREFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMdfcSgmtRefSeqNo(String MdfcSgmtRefSeqNo) {
		this.MdfcSgmtRefSeqNo = MdfcSgmtRefSeqNo;
	}
}