package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.Date;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
@XStreamAlias("EnBsInfDlt")
public class PbcrsReportEnbsinfdlt implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8433488500587358484L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBSINFDLT.ENBSINFDLTSEQNO
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
	@XStreamOmitField
    private String EnBsInfDltSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBSINFDLT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBSINFDLT.INFSURCCODE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    private String InfSurcCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBSINFDLT.ENTNAME
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    private String EntName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBSINFDLT.ENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    private String EntCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENBSINFDLT.ENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    private String EntCertNum;
    @XStreamOmitField
    private Date EtlDate;
    @XStreamOmitField
    private String  SourceSys;
    @XStreamOmitField
    private String ReportFlag;

    @XStreamOmitField
    private String orgCode;


    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBSINFDLT.ENBSINFDLTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENBSINFDLT.ENBSINFDLTSEQNO
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public String getEnBsInfDltSeqNo() {
        return EnBsInfDltSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBSINFDLT.ENBSINFDLTSEQNO
     *
     * @param EnBsInfDltSeqNo the value for PBCRS_REPORT_ENBSINFDLT.ENBSINFDLTSEQNO
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public void setEnBsInfDltSeqNo(String EnBsInfDltSeqNo) {
        this.EnBsInfDltSeqNo = EnBsInfDltSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBSINFDLT.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENBSINFDLT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBSINFDLT.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENBSINFDLT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBSINFDLT.INFSURCCODE
     *
     * @return the value of PBCRS_REPORT_ENBSINFDLT.INFSURCCODE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public String getInfSurcCode() {
        return InfSurcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBSINFDLT.INFSURCCODE
     *
     * @param InfSurcCode the value for PBCRS_REPORT_ENBSINFDLT.INFSURCCODE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public void setInfSurcCode(String InfSurcCode) {
        this.InfSurcCode = InfSurcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBSINFDLT.ENTNAME
     *
     * @return the value of PBCRS_REPORT_ENBSINFDLT.ENTNAME
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public String getEntName() {
        return EntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBSINFDLT.ENTNAME
     *
     * @param EntName the value for PBCRS_REPORT_ENBSINFDLT.ENTNAME
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public void setEntName(String EntName) {
        this.EntName = EntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBSINFDLT.ENTCERTTYPE
     *
     * @return the value of PBCRS_REPORT_ENBSINFDLT.ENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public String getEntCertType() {
        return EntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBSINFDLT.ENTCERTTYPE
     *
     * @param EntCertType the value for PBCRS_REPORT_ENBSINFDLT.ENTCERTTYPE
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public void setEntCertType(String EntCertType) {
        this.EntCertType = EntCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENBSINFDLT.ENTCERTNUM
     *
     * @return the value of PBCRS_REPORT_ENBSINFDLT.ENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public String getEntCertNum() {
        return EntCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENBSINFDLT.ENTCERTNUM
     *
     * @param EntCertNum the value for PBCRS_REPORT_ENBSINFDLT.ENTCERTNUM
     *
     * @mbggenerated Fri Mar 15 08:59:15 CST 2019
     */
    public void setEntCertNum(String EntCertNum) {
        this.EntCertNum = EntCertNum;
    }

	public Date getEtlDate() {
		return EtlDate;
	}

	public void setEtlDate(Date etlDate) {
		EtlDate = etlDate;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
    
}