package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("CltalInfSgmt")
public class PbcrsReportCltalinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 348012233165087833L;
	
	@XStreamImplicit
    private List<PbcrsReportImpinf> ImpInf;
	
	public List<PbcrsReportImpinf> getImpInf() {
		return ImpInf;
	}

	public void setImpInf(List<PbcrsReportImpinf> impInf) {
		ImpInf = impInf;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CLTALINFSGMT.CLTALINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CltalInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CLTALINFSGMT.IMPNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ImpNm;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CLTALINFSGMT.CLTALINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_CLTALINFSGMT.CLTALINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCltalInfSgmtSeqNo() {
		return CltalInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CLTALINFSGMT.CLTALINFSGMTSEQNO
	 * @param CltalInfSgmtSeqNo  the value for PBCRS_REPORT_CLTALINFSGMT.CLTALINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCltalInfSgmtSeqNo(String CltalInfSgmtSeqNo) {
		this.CltalInfSgmtSeqNo = CltalInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CLTALINFSGMT.IMPNM
	 * @return  the value of PBCRS_REPORT_CLTALINFSGMT.IMPNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getImpNm() {
		return ImpNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CLTALINFSGMT.IMPNM
	 * @param ImpNm  the value for PBCRS_REPORT_CLTALINFSGMT.IMPNM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setImpNm(String ImpNm) {
		this.ImpNm = ImpNm;
	}
}