package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("IncomeAndExpenseStatement")
public class PbcrsReportIncandexpsta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
	@XStreamOmitField
    private String IncomeAndESSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESBSSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
	@XStreamOmitField
    private String IncomeAndESBsSgmtSeqNo;

	@XStreamAlias("IncomeAndExpenseStatementBsSgmt")
	private PbcrsReportIncandexpstbssgmt IncomeAndExpenseStatementBsSgmt;
	@XStreamAlias("IncomeAndExpenseStatementSgmt")
	private PbcrsReportIncandexpstasgmt IncomeAndExpenseStatementSgmt;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
	@XStreamOmitField
    private String IncomeAndESSgmtSeqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSEQNO
     *
     * @return the value of PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    public String getIncomeAndESSeqNo() {
        return IncomeAndESSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSEQNO
     *
     * @param IncomeAndESSeqNo the value for PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    public void setIncomeAndESSeqNo(String IncomeAndESSeqNo) {
        this.IncomeAndESSeqNo = IncomeAndESSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESBSSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESBSSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    public String getIncomeAndESBsSgmtSeqNo() {
        return IncomeAndESBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESBSSGMTSEQNO
     *
     * @param IncomeAndESBsSgmtSeqNo the value for PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESBSSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    public void setIncomeAndESBsSgmtSeqNo(String IncomeAndESBsSgmtSeqNo) {
        this.IncomeAndESBsSgmtSeqNo = IncomeAndESBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    public String getIncomeAndESSgmtSeqNo() {
        return IncomeAndESSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSGMTSEQNO
     *
     * @param IncomeAndESSgmtSeqNo the value for PBCRS_REPORT_INCANDEXPSTA.INCOMEANDESSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    public void setIncomeAndESSgmtSeqNo(String IncomeAndESSgmtSeqNo) {
        this.IncomeAndESSgmtSeqNo = IncomeAndESSgmtSeqNo;
    }

	public PbcrsReportIncandexpstbssgmt getIncomeAndExpenseStatementBsSgmt() {
		return IncomeAndExpenseStatementBsSgmt;
	}

	public void setIncomeAndExpenseStatementBsSgmt(
			PbcrsReportIncandexpstbssgmt incomeAndExpenseStatementBsSgmt) {
		IncomeAndExpenseStatementBsSgmt = incomeAndExpenseStatementBsSgmt;
	}

	public PbcrsReportIncandexpstasgmt getIncomeAndExpenseStatementSgmt() {
		return IncomeAndExpenseStatementSgmt;
	}

	public void setIncomeAndExpenseStatementSgmt(
			PbcrsReportIncandexpstasgmt incomeAndExpenseStatementSgmt) {
		IncomeAndExpenseStatementSgmt = incomeAndExpenseStatementSgmt;
	}
    
}