package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("CtrctBsSgmt")
public class PbcrsReportCtrctbssgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1367587653747310554L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.CTRCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CtrctBsSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.CONTRACTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ContractCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.RPTDATECODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RptDateCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String IDNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CTRCTBSSGMT.MNGMTORGCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String MngmtOrgCode;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
	private String IsDel;
	
	@XStreamOmitField
	private String SourceSys;
	
	@XStreamOmitField
	private String orgCode;
	
	
	
   public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

public String getIsDel() {
		return IsDel;
	}

	public void setIsDel(String isDel) {
		IsDel = isDel;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.CTRCTBSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.CTRCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCtrctBsSgmtSeqNo() {
		return CtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.CTRCTBSSGMTSEQNO
	 * @param CtrctBsSgmtSeqNo  the value for PBCRS_REPORT_CTRCTBSSGMT.CTRCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCtrctBsSgmtSeqNo(String CtrctBsSgmtSeqNo) {
		this.CtrctBsSgmtSeqNo = CtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_CTRCTBSSGMT.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.CONTRACTCODE
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.CONTRACTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getContractCode() {
		return ContractCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.CONTRACTCODE
	 * @param ContractCode  the value for PBCRS_REPORT_CTRCTBSSGMT.CONTRACTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setContractCode(String ContractCode) {
		this.ContractCode = ContractCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.RPTDATE
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDate() {
		return RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.RPTDATE
	 * @param RptDate  the value for PBCRS_REPORT_CTRCTBSSGMT.RPTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDate(String RptDate) {
		this.RptDate = RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.RPTDATECODE
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.RPTDATECODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRptDateCode() {
		return RptDateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.RPTDATECODE
	 * @param RptDateCode  the value for PBCRS_REPORT_CTRCTBSSGMT.RPTDATECODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRptDateCode(String RptDateCode) {
		this.RptDateCode = RptDateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.NAME
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getName() {
		return Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.NAME
	 * @param Name  the value for PBCRS_REPORT_CTRCTBSSGMT.NAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setName(String Name) {
		this.Name = Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.IDTYPE
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDType() {
		return IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.IDTYPE
	 * @param IDType  the value for PBCRS_REPORT_CTRCTBSSGMT.IDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDType(String IDType) {
		this.IDType = IDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.IDNUM
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIDNum() {
		return IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.IDNUM
	 * @param IDNum  the value for PBCRS_REPORT_CTRCTBSSGMT.IDNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIDNum(String IDNum) {
		this.IDNum = IDNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CTRCTBSSGMT.MNGMTORGCODE
	 * @return  the value of PBCRS_REPORT_CTRCTBSSGMT.MNGMTORGCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMngmtOrgCode() {
		return MngmtOrgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CTRCTBSSGMT.MNGMTORGCODE
	 * @param MngmtOrgCode  the value for PBCRS_REPORT_CTRCTBSSGMT.MNGMTORGCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMngmtOrgCode(String MngmtOrgCode) {
		this.MngmtOrgCode = MngmtOrgCode;
	}

	@Override
	public String toString() {
		return "PbcrsReportCtrctbssgmt [InfRecType=" + InfRecType
				+ ", RptDate=" + RptDate + ", RptDateCode=" + RptDateCode
				+ ", Name=" + Name + ", IDType=" + IDType + ", IDNum=" + IDNum
				+ ", MngmtOrgCode=" + MngmtOrgCode + "]";
	}
	
	
}