package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnAcctInfEntDel")
public class PbcrsReportEnacctinfentdel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8608212242096066494L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFENTDEL.ENACCTINFENTDELSEQNO
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
	@XStreamOmitField
    private String EnAcctInfEntDelSeqNo;
	
    @XStreamOmitField
    private String  SourceSys;
    @XStreamOmitField
    private String ReportFlag;
    
    @XStreamOmitField
    private String orgCode;
    
    
    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFENTDEL.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENACCTINFENTDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    private String DelRecCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFENTDEL.ENACCTINFENTDELSEQNO
     *
     * @return the value of PBCRS_REPORT_ENACCTINFENTDEL.ENACCTINFENTDELSEQNO
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    public String getEnAcctInfEntDelSeqNo() {
        return EnAcctInfEntDelSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFENTDEL.ENACCTINFENTDELSEQNO
     *
     * @param EnAcctInfEntDelSeqNo the value for PBCRS_REPORT_ENACCTINFENTDEL.ENACCTINFENTDELSEQNO
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    public void setEnAcctInfEntDelSeqNo(String EnAcctInfEntDelSeqNo) {
        this.EnAcctInfEntDelSeqNo = EnAcctInfEntDelSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFENTDEL.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFENTDEL.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFENTDEL.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENACCTINFENTDEL.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENACCTINFENTDEL.DELRECCODE
     *
     * @return the value of PBCRS_REPORT_ENACCTINFENTDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    public String getDelRecCode() {
        return DelRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENACCTINFENTDEL.DELRECCODE
     *
     * @param DelRecCode the value for PBCRS_REPORT_ENACCTINFENTDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 09:48:59 CST 2019
     */
    public void setDelRecCode(String DelRecCode) {
        this.DelRecCode = DelRecCode;
    }

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
    
}