package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("ImpInf")
public class PbcrsReportImpinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8002394788190298054L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.CLTALINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String CltalInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.IMPINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String ImpInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.IMPTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ImpType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.IMPVAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ImpVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.IMPCY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ImpCy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.IPPC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Ippc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.PAWNNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PawnName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.PAWNCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PawnCertType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_IMPINF.PAWNCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PawnCertNum;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.CLTALINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_IMPINF.CLTALINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.IMPINFSEQNO
	 * @return  the value of PBCRS_REPORT_IMPINF.IMPINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getImpInfSeqNo() {
		return ImpInfSeqNo;
	}

	public String getCltalInfSgmtSeqNo() {
		return CltalInfSgmtSeqNo;
	}

	public void setCltalInfSgmtSeqNo(String cltalInfSgmtSeqNo) {
		CltalInfSgmtSeqNo = cltalInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.IMPINFSEQNO
	 * @param ImpInfSeqNo  the value for PBCRS_REPORT_IMPINF.IMPINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setImpInfSeqNo(String ImpInfSeqNo) {
		this.ImpInfSeqNo = ImpInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.IMPTYPE
	 * @return  the value of PBCRS_REPORT_IMPINF.IMPTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getImpType() {
		return ImpType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.IMPTYPE
	 * @param ImpType  the value for PBCRS_REPORT_IMPINF.IMPTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setImpType(String ImpType) {
		this.ImpType = ImpType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.IMPVAL
	 * @return  the value of PBCRS_REPORT_IMPINF.IMPVAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getImpVal() {
		return ImpVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.IMPVAL
	 * @param ImpVal  the value for PBCRS_REPORT_IMPINF.IMPVAL
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setImpVal(String ImpVal) {
		this.ImpVal = ImpVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.IMPCY
	 * @return  the value of PBCRS_REPORT_IMPINF.IMPCY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getImpCy() {
		return ImpCy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.IMPCY
	 * @param ImpCy  the value for PBCRS_REPORT_IMPINF.IMPCY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setImpCy(String ImpCy) {
		this.ImpCy = ImpCy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.IPPC
	 * @return  the value of PBCRS_REPORT_IMPINF.IPPC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getIppc() {
		return Ippc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.IPPC
	 * @param Ippc  the value for PBCRS_REPORT_IMPINF.IPPC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setIppc(String Ippc) {
		this.Ippc = Ippc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.PAWNNAME
	 * @return  the value of PBCRS_REPORT_IMPINF.PAWNNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPawnName() {
		return PawnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.PAWNNAME
	 * @param PawnName  the value for PBCRS_REPORT_IMPINF.PAWNNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPawnName(String PawnName) {
		this.PawnName = PawnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.PAWNCERTTYPE
	 * @return  the value of PBCRS_REPORT_IMPINF.PAWNCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPawnCertType() {
		return PawnCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.PAWNCERTTYPE
	 * @param PawnCertType  the value for PBCRS_REPORT_IMPINF.PAWNCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPawnCertType(String PawnCertType) {
		this.PawnCertType = PawnCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_IMPINF.PAWNCERTNUM
	 * @return  the value of PBCRS_REPORT_IMPINF.PAWNCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPawnCertNum() {
		return PawnCertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_IMPINF.PAWNCERTNUM
	 * @param PawnCertNum  the value for PBCRS_REPORT_IMPINF.PAWNCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPawnCertNum(String PawnCertNum) {
		this.PawnCertNum = PawnCertNum;
	}
}