package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("InAcctInf")
public class PbcrsReportInacctinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3943229079307238932L;
	
	@XStreamAlias("AcctBsSgmt")
	private PbcrsReportAcctbssgmt AcctBsSgmt;
	
	@XStreamAlias("AcctBsInfSgmt")
	private PbcrsReportAcctbsinfsgmt AcctBsInfSgmt;
	
	@XStreamAlias("RltRepymtInfSgmt")
	private PbcrsReportRltrepymtinfsgmt RltRepymtInfSgmt;
	
	@XStreamAlias("MotgaCltalCtrctInfSgmt")
	private PbcrsReportMotcltctrinfsgmt MotCltCtrInfSgmt;
	
	@XStreamAlias("AcctCredSgmt")
	private PbcrsReportAcctcredsgmt AcctCredSgmt;
	
	@XStreamAlias("OrigCreditorInfSgmt")
	private PbcrsReportOricreinfsgmt OriCreInfSgmt;
	
	@XStreamAlias("AcctMthlyBlgInfSgmt")
	private PbcrsReportAccmthblginfsgmt AccMthBlgInfSgmt;
	
	@XStreamAlias("SpecPrdSgmt")
	private PbcrsReportSpecprdsgmt SpecPrdSgmt;
	
	@XStreamAlias("AcctDbtInfSgmt")
	private PbcrsReportAcctdbtinfsgmt AcctDbtInfSgmt;
	
	@XStreamAlias("AcctSpecTrstDspnSgmt")
	private PbcrsReportAccspetrsdspsgmt AccSpeTrsDspSgmt;
	
	public PbcrsReportAcctbssgmt getAcctBsSgmt() {
		return AcctBsSgmt;
	}

	public void setAcctBsSgmt(PbcrsReportAcctbssgmt acctBsSgmt) {
		AcctBsSgmt = acctBsSgmt;
	}

	public PbcrsReportAcctbsinfsgmt getAcctBsInfSgmt() {
		return AcctBsInfSgmt;
	}

	public void setAcctBsInfSgmt(PbcrsReportAcctbsinfsgmt acctBsInfSgmt) {
		AcctBsInfSgmt = acctBsInfSgmt;
	}

	public PbcrsReportRltrepymtinfsgmt getRltRepymtInfSgmt() {
		return RltRepymtInfSgmt;
	}

	public void setRltRepymtInfSgmt(PbcrsReportRltrepymtinfsgmt rltRepymtInfSgmt) {
		RltRepymtInfSgmt = rltRepymtInfSgmt;
	}

	public PbcrsReportMotcltctrinfsgmt getMotCltCtrInfSgmt() {
		return MotCltCtrInfSgmt;
	}

	public void setMotCltCtrInfSgmt(PbcrsReportMotcltctrinfsgmt motCltCtrInfSgmt) {
		MotCltCtrInfSgmt = motCltCtrInfSgmt;
	}

	public PbcrsReportAcctcredsgmt getAcctCredSgmt() {
		return AcctCredSgmt;
	}

	public void setAcctCredSgmt(PbcrsReportAcctcredsgmt acctCredSgmt) {
		AcctCredSgmt = acctCredSgmt;
	}

	public PbcrsReportOricreinfsgmt getOriCreInfSgmt() {
		return OriCreInfSgmt;
	}

	public void setOriCreInfSgmt(PbcrsReportOricreinfsgmt oriCreInfSgmt) {
		OriCreInfSgmt = oriCreInfSgmt;
	}

	public PbcrsReportAccmthblginfsgmt getAccMthBlgInfSgmt() {
		return AccMthBlgInfSgmt;
	}

	public void setAccMthBlgInfSgmt(PbcrsReportAccmthblginfsgmt accMthBlgInfSgmt) {
		AccMthBlgInfSgmt = accMthBlgInfSgmt;
	}

	public PbcrsReportSpecprdsgmt getSpecPrdSgmt() {
		return SpecPrdSgmt;
	}

	public void setSpecPrdSgmt(PbcrsReportSpecprdsgmt specPrdSgmt) {
		SpecPrdSgmt = specPrdSgmt;
	}

	public PbcrsReportAcctdbtinfsgmt getAcctDbtInfSgmt() {
		return AcctDbtInfSgmt;
	}

	public void setAcctDbtInfSgmt(PbcrsReportAcctdbtinfsgmt acctDbtInfSgmt) {
		AcctDbtInfSgmt = acctDbtInfSgmt;
	}

	public PbcrsReportAccspetrsdspsgmt getAccSpeTrsDspSgmt() {
		return AccSpeTrsDspSgmt;
	}

	public void setAccSpeTrsDspSgmt(PbcrsReportAccspetrsdspsgmt accSpeTrsDspSgmt) {
		AccSpeTrsDspSgmt = accSpeTrsDspSgmt;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.INACCTINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String SeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ACCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctBsSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ACCTBSINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctBsInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String RltRepymtInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String MotgaCltalCtrctInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ACCTCREDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctCredSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ORIGCREDITORINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String OrigCreditorInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ACCTMTHLYBLGINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctMthlyBlgInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.SPECPRDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String SpecPrdSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ACCTDBTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctDbtInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INACCTINF.ACCTSPECTRSTDSPNSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctSpecTrstDspnSgmtSeqno;

	
	

	public String getSeqNo() {
		return SeqNo;
	}

	public void setSeqNo(String seqNo) {
		SeqNo = seqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ACCTBSSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ACCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctBsSgmtSeqNo() {
		return AcctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ACCTBSSGMTSEQNO
	 * @param AcctBsSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.ACCTBSSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctBsSgmtSeqNo(String AcctBsSgmtSeqNo) {
		this.AcctBsSgmtSeqNo = AcctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ACCTBSINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ACCTBSINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctBsInfSgmtSeqNo() {
		return AcctBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ACCTBSINFSGMTSEQNO
	 * @param AcctBsInfSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.ACCTBSINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctBsInfSgmtSeqNo(String AcctBsInfSgmtSeqNo) {
		this.AcctBsInfSgmtSeqNo = AcctBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.RLTREPYMTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRltRepymtInfSgmtSeqNo() {
		return RltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.RLTREPYMTINFSGMTSEQNO
	 * @param RltRepymtInfSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.RLTREPYMTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRltRepymtInfSgmtSeqNo(String RltRepymtInfSgmtSeqNo) {
		this.RltRepymtInfSgmtSeqNo = RltRepymtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMotgaCltalCtrctInfSgmtSeqNo() {
		return MotgaCltalCtrctInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @param MotgaCltalCtrctInfSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.MOTGACLTALCTRCTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMotgaCltalCtrctInfSgmtSeqNo(String MotgaCltalCtrctInfSgmtSeqNo) {
		this.MotgaCltalCtrctInfSgmtSeqNo = MotgaCltalCtrctInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ACCTCREDSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ACCTCREDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctCredSgmtSeqNo() {
		return AcctCredSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ACCTCREDSGMTSEQNO
	 * @param AcctCredSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.ACCTCREDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctCredSgmtSeqNo(String AcctCredSgmtSeqNo) {
		this.AcctCredSgmtSeqNo = AcctCredSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ORIGCREDITORINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ORIGCREDITORINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOrigCreditorInfSgmtSeqNo() {
		return OrigCreditorInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ORIGCREDITORINFSGMTSEQNO
	 * @param OrigCreditorInfSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.ORIGCREDITORINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOrigCreditorInfSgmtSeqNo(String OrigCreditorInfSgmtSeqNo) {
		this.OrigCreditorInfSgmtSeqNo = OrigCreditorInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ACCTMTHLYBLGINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ACCTMTHLYBLGINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctMthlyBlgInfSgmtSeqNo() {
		return AcctMthlyBlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ACCTMTHLYBLGINFSGMTSEQNO
	 * @param AcctMthlyBlgInfSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.ACCTMTHLYBLGINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctMthlyBlgInfSgmtSeqNo(String AcctMthlyBlgInfSgmtSeqNo) {
		this.AcctMthlyBlgInfSgmtSeqNo = AcctMthlyBlgInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.SPECPRDSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.SPECPRDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getSpecPrdSgmtSeqNo() {
		return SpecPrdSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.SPECPRDSGMTSEQNO
	 * @param SpecPrdSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.SPECPRDSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setSpecPrdSgmtSeqNo(String SpecPrdSgmtSeqNo) {
		this.SpecPrdSgmtSeqNo = SpecPrdSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ACCTDBTINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ACCTDBTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctDbtInfSgmtSeqNo() {
		return AcctDbtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ACCTDBTINFSGMTSEQNO
	 * @param AcctDbtInfSgmtSeqNo  the value for PBCRS_REPORT_INACCTINF.ACCTDBTINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctDbtInfSgmtSeqNo(String AcctDbtInfSgmtSeqNo) {
		this.AcctDbtInfSgmtSeqNo = AcctDbtInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INACCTINF.ACCTSPECTRSTDSPNSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_INACCTINF.ACCTSPECTRSTDSPNSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctSpecTrstDspnSgmtSeqno() {
		return AcctSpecTrstDspnSgmtSeqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INACCTINF.ACCTSPECTRSTDSPNSGMTSEQNO
	 * @param AcctSpecTrstDspnSgmtSeqno  the value for PBCRS_REPORT_INACCTINF.ACCTSPECTRSTDSPNSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctSpecTrstDspnSgmtSeqno(String AcctSpecTrstDspnSgmtSeqno) {
		this.AcctSpecTrstDspnSgmtSeqno = AcctSpecTrstDspnSgmtSeqno;
	}
}