package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("AcctBsInfSgmt")
public class PbcrsReportAcctbsinfsgmt implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1176838331695791405L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.ACCTBSINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String AcctBsInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.BUSILINES
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String BusiLines;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.BUSIDTLLINES
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String BusiDtlLines;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.OPENDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OpenDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.CY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Cy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.ACCTCREDLINE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AcctCredLine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.LOANAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String LoanAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.FLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String Flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.DUEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYMODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RepayMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYFREQCY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RepayFreqcy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String RepayPrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.APPLYBUSIDIST
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ApplyBusiDist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.GUARMODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String GuarMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.OTHREPYGUARWAY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String OthRepyGuarWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.ASSETTRANDFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String AssetTrandFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.FUNDSOU
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String FundSou;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.LOANFORM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String LoanForm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_ACCTBSINFSGMT.CREDITID
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String CreditID;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	
	private String LoanConCode;
	
	private String FirstHouLoanFlag;
	
	@XStreamOmitField
	private String ParagraphDel;
	
	
	
   public String getParagraphDel() {
		return ParagraphDel;
	}

	public void setParagraphDel(String paragraphDel) {
		ParagraphDel = paragraphDel;
	}

	public String getLoanConCode() {
		return LoanConCode;
	}

	public void setLoanConCode(String loanConCode) {
		LoanConCode = loanConCode;
	}

	public String getFirstHouLoanFlag() {
		return FirstHouLoanFlag;
	}

	public void setFirstHouLoanFlag(String firstHouLoanFlag) {
		FirstHouLoanFlag = firstHouLoanFlag;
	}

public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.ACCTBSINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.ACCTBSINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctBsInfSgmtSeqNo() {
		return AcctBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.ACCTBSINFSGMTSEQNO
	 * @param AcctBsInfSgmtSeqNo  the value for PBCRS_REPORT_ACCTBSINFSGMT.ACCTBSINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctBsInfSgmtSeqNo(String AcctBsInfSgmtSeqNo) {
		this.AcctBsInfSgmtSeqNo = AcctBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.BUSILINES
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.BUSILINES
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getBusiLines() {
		return BusiLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.BUSILINES
	 * @param BusiLines  the value for PBCRS_REPORT_ACCTBSINFSGMT.BUSILINES
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setBusiLines(String BusiLines) {
		this.BusiLines = BusiLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.BUSIDTLLINES
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.BUSIDTLLINES
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getBusiDtlLines() {
		return BusiDtlLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.BUSIDTLLINES
	 * @param BusiDtlLines  the value for PBCRS_REPORT_ACCTBSINFSGMT.BUSIDTLLINES
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setBusiDtlLines(String BusiDtlLines) {
		this.BusiDtlLines = BusiDtlLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.OPENDATE
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.OPENDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOpenDate() {
		return OpenDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.OPENDATE
	 * @param OpenDate  the value for PBCRS_REPORT_ACCTBSINFSGMT.OPENDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOpenDate(String OpenDate) {
		this.OpenDate = OpenDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.CY
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.CY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCy() {
		return Cy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.CY
	 * @param Cy  the value for PBCRS_REPORT_ACCTBSINFSGMT.CY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCy(String Cy) {
		this.Cy = Cy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.ACCTCREDLINE
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.ACCTCREDLINE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAcctCredLine() {
		return AcctCredLine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.ACCTCREDLINE
	 * @param AcctCredLine  the value for PBCRS_REPORT_ACCTBSINFSGMT.ACCTCREDLINE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAcctCredLine(String AcctCredLine) {
		this.AcctCredLine = AcctCredLine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.LOANAMT
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.LOANAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getLoanAmt() {
		return LoanAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.LOANAMT
	 * @param LoanAmt  the value for PBCRS_REPORT_ACCTBSINFSGMT.LOANAMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setLoanAmt(String LoanAmt) {
		this.LoanAmt = LoanAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.FLAG
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.FLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFlag() {
		return Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.FLAG
	 * @param Flag  the value for PBCRS_REPORT_ACCTBSINFSGMT.FLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFlag(String Flag) {
		this.Flag = Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.DUEDATE
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.DUEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDueDate() {
		return DueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.DUEDATE
	 * @param DueDate  the value for PBCRS_REPORT_ACCTBSINFSGMT.DUEDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDueDate(String DueDate) {
		this.DueDate = DueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYMODE
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.REPAYMODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRepayMode() {
		return RepayMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYMODE
	 * @param RepayMode  the value for PBCRS_REPORT_ACCTBSINFSGMT.REPAYMODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRepayMode(String RepayMode) {
		this.RepayMode = RepayMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYFREQCY
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.REPAYFREQCY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRepayFreqcy() {
		return RepayFreqcy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYFREQCY
	 * @param RepayFreqcy  the value for PBCRS_REPORT_ACCTBSINFSGMT.REPAYFREQCY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRepayFreqcy(String RepayFreqcy) {
		this.RepayFreqcy = RepayFreqcy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYPRD
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.REPAYPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getRepayPrd() {
		return RepayPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.REPAYPRD
	 * @param RepayPrd  the value for PBCRS_REPORT_ACCTBSINFSGMT.REPAYPRD
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setRepayPrd(String RepayPrd) {
		this.RepayPrd = RepayPrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.APPLYBUSIDIST
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.APPLYBUSIDIST
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getApplyBusiDist() {
		return ApplyBusiDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.APPLYBUSIDIST
	 * @param ApplyBusiDist  the value for PBCRS_REPORT_ACCTBSINFSGMT.APPLYBUSIDIST
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setApplyBusiDist(String ApplyBusiDist) {
		this.ApplyBusiDist = ApplyBusiDist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.GUARMODE
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.GUARMODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuarMode() {
		return GuarMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.GUARMODE
	 * @param GuarMode  the value for PBCRS_REPORT_ACCTBSINFSGMT.GUARMODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuarMode(String GuarMode) {
		this.GuarMode = GuarMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.OTHREPYGUARWAY
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.OTHREPYGUARWAY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getOthRepyGuarWay() {
		return OthRepyGuarWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.OTHREPYGUARWAY
	 * @param OthRepyGuarWay  the value for PBCRS_REPORT_ACCTBSINFSGMT.OTHREPYGUARWAY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setOthRepyGuarWay(String OthRepyGuarWay) {
		this.OthRepyGuarWay = OthRepyGuarWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.ASSETTRANDFLAG
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.ASSETTRANDFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getAssetTrandFlag() {
		return AssetTrandFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.ASSETTRANDFLAG
	 * @param AssetTrandFlag  the value for PBCRS_REPORT_ACCTBSINFSGMT.ASSETTRANDFLAG
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setAssetTrandFlag(String AssetTrandFlag) {
		this.AssetTrandFlag = AssetTrandFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.FUNDSOU
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.FUNDSOU
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getFundSou() {
		return FundSou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.FUNDSOU
	 * @param FundSou  the value for PBCRS_REPORT_ACCTBSINFSGMT.FUNDSOU
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setFundSou(String FundSou) {
		this.FundSou = FundSou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.LOANFORM
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.LOANFORM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getLoanForm() {
		return LoanForm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.LOANFORM
	 * @param LoanForm  the value for PBCRS_REPORT_ACCTBSINFSGMT.LOANFORM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setLoanForm(String LoanForm) {
		this.LoanForm = LoanForm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.CREDITID
	 * @return  the value of PBCRS_REPORT_ACCTBSINFSGMT.CREDITID
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCreditID() {
		return CreditID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_ACCTBSINFSGMT.CREDITID
	 * @param CreditID  the value for PBCRS_REPORT_ACCTBSINFSGMT.CREDITID
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCreditID(String CreditID) {
		this.CreditID = CreditID;
	}
}