package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("MotgaCltalBsInfSgmt")
public class PbcrsReportMotcltbsinfsgmt implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.MOTGACLTALBSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String MotgaCltalBsInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.GUARTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String GuarType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCAMT
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CcAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CY
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String Cy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCVALDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CcValDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCEXPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CcExpDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.MAXGUAR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String MaxGuar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCSTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CcStatus;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.MOTGACLTALBSINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.MOTGACLTALBSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMotgaCltalBsInfSgmtSeqNo() {
		return MotgaCltalBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.MOTGACLTALBSINFSGMTSEQNO
	 * @param MotgaCltalBsInfSgmtSeqNo  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.MOTGACLTALBSINFSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMotgaCltalBsInfSgmtSeqNo(String MotgaCltalBsInfSgmtSeqNo) {
		this.MotgaCltalBsInfSgmtSeqNo = MotgaCltalBsInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.GUARTYPE
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.GUARTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getGuarType() {
		return GuarType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.GUARTYPE
	 * @param GuarType  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.GUARTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setGuarType(String GuarType) {
		this.GuarType = GuarType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCAMT
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.CCAMT
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCcAmt() {
		return CcAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCAMT
	 * @param CcAmt  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.CCAMT
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCcAmt(String CcAmt) {
		this.CcAmt = CcAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CY
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.CY
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCy() {
		return Cy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CY
	 * @param Cy  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.CY
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCy(String Cy) {
		this.Cy = Cy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCVALDATE
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.CCVALDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCcValDate() {
		return CcValDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCVALDATE
	 * @param CcValDate  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.CCVALDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCcValDate(String CcValDate) {
		this.CcValDate = CcValDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCEXPDATE
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.CCEXPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCcExpDate() {
		return CcExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCEXPDATE
	 * @param CcExpDate  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.CCEXPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCcExpDate(String CcExpDate) {
		this.CcExpDate = CcExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.MAXGUAR
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.MAXGUAR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMaxGuar() {
		return MaxGuar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.MAXGUAR
	 * @param MaxGuar  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.MAXGUAR
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMaxGuar(String MaxGuar) {
		this.MaxGuar = MaxGuar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCSTATUS
	 * @return  the value of PBCRS_REPORT_MOTCLTBSINFSGMT.CCSTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCcStatus() {
		return CcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_MOTCLTBSINFSGMT.CCSTATUS
	 * @param CcStatus  the value for PBCRS_REPORT_MOTCLTBSINFSGMT.CCSTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCcStatus(String CcStatus) {
		this.CcStatus = CcStatus;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -6226993043330203250L;
}