package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("CreditLimSgmt")
public class PbcrsReportCreditlimsgmt implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String CreditLimSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CreditLimType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.LIMLOOPFLG
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String LimLoopFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIM
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CreditLim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CY
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String Cy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CONEFFDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String ConEffDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CONEXPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String ConExpDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CONSTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String ConStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITREST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CreditRest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITRESTCODE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	private String CreditRestCode;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCreditLimSgmtSeqNo() {
		return CreditLimSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMSGMTSEQNO
	 * @param CreditLimSgmtSeqNo  the value for PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMSGMTSEQNO
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCreditLimSgmtSeqNo(String CreditLimSgmtSeqNo) {
		this.CreditLimSgmtSeqNo = CreditLimSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMTYPE
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCreditLimType() {
		return CreditLimType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMTYPE
	 * @param CreditLimType  the value for PBCRS_REPORT_CREDITLIMSGMT.CREDITLIMTYPE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCreditLimType(String CreditLimType) {
		this.CreditLimType = CreditLimType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.LIMLOOPFLG
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.LIMLOOPFLG
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getLimLoopFlg() {
		return LimLoopFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.LIMLOOPFLG
	 * @param LimLoopFlg  the value for PBCRS_REPORT_CREDITLIMSGMT.LIMLOOPFLG
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setLimLoopFlg(String LimLoopFlg) {
		this.LimLoopFlg = LimLoopFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIM
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CREDITLIM
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCreditLim() {
		return CreditLim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITLIM
	 * @param CreditLim  the value for PBCRS_REPORT_CREDITLIMSGMT.CREDITLIM
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCreditLim(String CreditLim) {
		this.CreditLim = CreditLim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CY
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CY
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCy() {
		return Cy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CY
	 * @param Cy  the value for PBCRS_REPORT_CREDITLIMSGMT.CY
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCy(String Cy) {
		this.Cy = Cy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CONEFFDATE
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CONEFFDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getConEffDate() {
		return ConEffDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CONEFFDATE
	 * @param ConEffDate  the value for PBCRS_REPORT_CREDITLIMSGMT.CONEFFDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setConEffDate(String ConEffDate) {
		this.ConEffDate = ConEffDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CONEXPDATE
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CONEXPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getConExpDate() {
		return ConExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CONEXPDATE
	 * @param ConExpDate  the value for PBCRS_REPORT_CREDITLIMSGMT.CONEXPDATE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setConExpDate(String ConExpDate) {
		this.ConExpDate = ConExpDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CONSTATUS
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CONSTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getConStatus() {
		return ConStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CONSTATUS
	 * @param ConStatus  the value for PBCRS_REPORT_CREDITLIMSGMT.CONSTATUS
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setConStatus(String ConStatus) {
		this.ConStatus = ConStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITREST
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CREDITREST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCreditRest() {
		return CreditRest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITREST
	 * @param CreditRest  the value for PBCRS_REPORT_CREDITLIMSGMT.CREDITREST
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCreditRest(String CreditRest) {
		this.CreditRest = CreditRest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITRESTCODE
	 * @return  the value of PBCRS_REPORT_CREDITLIMSGMT.CREDITRESTCODE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCreditRestCode() {
		return CreditRestCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_CREDITLIMSGMT.CREDITRESTCODE
	 * @param CreditRestCode  the value for PBCRS_REPORT_CREDITLIMSGMT.CREDITRESTCODE
	 * @mbggenerated  Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCreditRestCode(String CreditRestCode) {
		this.CreditRestCode = CreditRestCode;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -4157466487895457038L;
}