package com.hkbank.pbcrs.model;

import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("MotgaCltalCtrctInfSgmt")
public class PbcrsReportEnmotcltctrinfsgm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENMOTCLTCTRINFSGM.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @mbggenerated Mon Mar 25 09:14:29 CST 2019
     */


	@XStreamOmitField
    private String MotgaCltalCtrctInfSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENMOTCLTCTRINFSGM.CCNM
     *
     * @mbggenerated Mon Mar 25 09:14:29 CST 2019
     */
	
    private String CcNm;
	@XStreamImplicit
    private List<PbcrsReportCccinf> CccInf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENMOTCLTCTRINFSGM.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENMOTCLTCTRINFSGM.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @mbggenerated Mon Mar 25 09:14:29 CST 2019
     */
    public String getMotgaCltalCtrctInfSgmtSeqNo() {
        return MotgaCltalCtrctInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENMOTCLTCTRINFSGM.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @param MotgaCltalCtrctInfSgmtSeqNo the value for PBCRS_REPORT_ENMOTCLTCTRINFSGM.MOTGACLTALCTRCTINFSGMTSEQNO
     *
     * @mbggenerated Mon Mar 25 09:14:29 CST 2019
     */
    public void setMotgaCltalCtrctInfSgmtSeqNo(String MotgaCltalCtrctInfSgmtSeqNo) {
        this.MotgaCltalCtrctInfSgmtSeqNo = MotgaCltalCtrctInfSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENMOTCLTCTRINFSGM.CCNM
     *
     * @return the value of PBCRS_REPORT_ENMOTCLTCTRINFSGM.CCNM
     *
     * @mbggenerated Mon Mar 25 09:14:29 CST 2019
     */
    public String getCcNm() {
        return CcNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENMOTCLTCTRINFSGM.CCNM
     *
     * @param CcNm the value for PBCRS_REPORT_ENMOTCLTCTRINFSGM.CCNM
     *
     * @mbggenerated Mon Mar 25 09:14:29 CST 2019
     */
    public void setCcNm(String CcNm) {
        this.CcNm = CcNm;
    }

	public List<PbcrsReportCccinf> getCccInf() {
		return CccInf;
	}

	public void setCccInf(List<PbcrsReportCccinf> cccInf) {
		CccInf = cccInf;
	}
    
}