package com.hkbank.pbcrs.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("CashFlows")
public class PbcrsReportCashflows {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWSSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
	@XStreamOmitField
    private String CashFlowsSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWSBSSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
	@XStreamOmitField
    private String CashFlowsBsSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWS2007SGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
	@XStreamOmitField
    private String CashFlows2007SgmtSeqNo;
	@XStreamAlias("CashFlowsBsSgmt")
	private PbcrsReportCashflowsbssgmt CashFlowsBsSgmt;
	@XStreamAlias("CashFlows2007Sgmt")
	private PbcrsReportCashflows2007sgmt CashFlows2007Sgmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWSSEQNO
     *
     * @return the value of PBCRS_REPORT_CASHFLOWS.CASHFLOWSSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    public String getCashFlowsSeqNo() {
        return CashFlowsSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWSSEQNO
     *
     * @param CashFlowsSeqNo the value for PBCRS_REPORT_CASHFLOWS.CASHFLOWSSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    public void setCashFlowsSeqNo(String CashFlowsSeqNo) {
        this.CashFlowsSeqNo = CashFlowsSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWSBSSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_CASHFLOWS.CASHFLOWSBSSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    public String getCashFlowsBsSgmtSeqNo() {
        return CashFlowsBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWSBSSGMTSEQNO
     *
     * @param CashFlowsBsSgmtSeqNo the value for PBCRS_REPORT_CASHFLOWS.CASHFLOWSBSSGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    public void setCashFlowsBsSgmtSeqNo(String CashFlowsBsSgmtSeqNo) {
        this.CashFlowsBsSgmtSeqNo = CashFlowsBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWS2007SGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_CASHFLOWS.CASHFLOWS2007SGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    public String getCashFlows2007SgmtSeqNo() {
        return CashFlows2007SgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_CASHFLOWS.CASHFLOWS2007SGMTSEQNO
     *
     * @param CashFlows2007SgmtSeqNo the value for PBCRS_REPORT_CASHFLOWS.CASHFLOWS2007SGMTSEQNO
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    public void setCashFlows2007SgmtSeqNo(String CashFlows2007SgmtSeqNo) {
        this.CashFlows2007SgmtSeqNo = CashFlows2007SgmtSeqNo;
    }

	public PbcrsReportCashflowsbssgmt getCashFlowsBsSgmt() {
		return CashFlowsBsSgmt;
	}

	public void setCashFlowsBsSgmt(PbcrsReportCashflowsbssgmt cashFlowsBsSgmt) {
		CashFlowsBsSgmt = cashFlowsBsSgmt;
	}

	public PbcrsReportCashflows2007sgmt getCashFlows2007Sgmt() {
		return CashFlows2007Sgmt;
	}

	public void setCashFlows2007Sgmt(PbcrsReportCashflows2007sgmt cashFlows2007Sgmt) {
		CashFlows2007Sgmt = cashFlows2007Sgmt;
	}
    
}