package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("CtrctBsSgmt")
public class PbcrsReportEnctrctbssgmt implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2115240305986771149L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.CTRCTBSSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
	@XStreamOmitField
    private String CtrctBsSgmtSeqNo;
	@XStreamOmitField
	private String IsDel;
	@XStreamOmitField
	private String SourceSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String InfRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.CONTRACTCODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String ContractCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String RptDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATECODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String RptDateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.NAME
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.IDTYPE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String IDType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.IDNUM
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String IDNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTBSSGMT.MNGMTORGCODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    private String MngmtOrgCode;
    
    @XStreamOmitField
    private String ReportFlag;

    @XStreamOmitField
    private String orgCode;
    
    public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.CTRCTBSSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.CTRCTBSSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getCtrctBsSgmtSeqNo() {
        return CtrctBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.CTRCTBSSGMTSEQNO
     *
     * @param CtrctBsSgmtSeqNo the value for PBCRS_REPORT_ENCTRCTBSSGMT.CTRCTBSSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setCtrctBsSgmtSeqNo(String CtrctBsSgmtSeqNo) {
        this.CtrctBsSgmtSeqNo = CtrctBsSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.INFRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getInfRecType() {
        return InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.INFRECTYPE
     *
     * @param InfRecType the value for PBCRS_REPORT_ENCTRCTBSSGMT.INFRECTYPE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setInfRecType(String InfRecType) {
        this.InfRecType = InfRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.CONTRACTCODE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.CONTRACTCODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getContractCode() {
        return ContractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.CONTRACTCODE
     *
     * @param ContractCode the value for PBCRS_REPORT_ENCTRCTBSSGMT.CONTRACTCODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setContractCode(String ContractCode) {
        this.ContractCode = ContractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getRptDate() {
        return RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATE
     *
     * @param RptDate the value for PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setRptDate(String RptDate) {
        this.RptDate = RptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATECODE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATECODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getRptDateCode() {
        return RptDateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATECODE
     *
     * @param RptDateCode the value for PBCRS_REPORT_ENCTRCTBSSGMT.RPTDATECODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setRptDateCode(String RptDateCode) {
        this.RptDateCode = RptDateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.NAME
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.NAME
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getName() {
        return Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.NAME
     *
     * @param Name the value for PBCRS_REPORT_ENCTRCTBSSGMT.NAME
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.IDTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.IDTYPE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getIDType() {
        return IDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.IDTYPE
     *
     * @param IDType the value for PBCRS_REPORT_ENCTRCTBSSGMT.IDTYPE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setIDType(String IDType) {
        this.IDType = IDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.IDNUM
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.IDNUM
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getIDNum() {
        return IDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.IDNUM
     *
     * @param IDNum the value for PBCRS_REPORT_ENCTRCTBSSGMT.IDNUM
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setIDNum(String IDNum) {
        this.IDNum = IDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.MNGMTORGCODE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTBSSGMT.MNGMTORGCODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public String getMngmtOrgCode() {
        return MngmtOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTBSSGMT.MNGMTORGCODE
     *
     * @param MngmtOrgCode the value for PBCRS_REPORT_ENCTRCTBSSGMT.MNGMTORGCODE
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    public void setMngmtOrgCode(String MngmtOrgCode) {
        this.MngmtOrgCode = MngmtOrgCode;
    }

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

	public String getIsDel() {
		return IsDel;
	}

	public void setIsDel(String isDel) {
		IsDel = isDel;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}
    
    
}