package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.Date;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("EnSecAcctDel")
public class PbcrsReportEnsecacctdel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5900740355898800794L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTDEL.ENSECACCTDELSEQNO
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
	@XStreamOmitField
    private String EnSecAcctDelSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTDEL.DELRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
	@XStreamAlias("InfRecType")
    private String DelRecType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    private String DelRecCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTDEL.DELSGMTCODE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    private String DelSgmtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTDEL.DELSTARTDATE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    private String DelStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENSECACCTDEL.DELENDDATE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    private String DelEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTDEL.ENSECACCTDELSEQNO
     *
     * @return the value of PBCRS_REPORT_ENSECACCTDEL.ENSECACCTDELSEQNO
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     * 
     * 
     * 
     * 
     */
    
    private String ReportFlag;
	
	private Date Etl_Date;
	
	private String SourceSys;
	
	private String orgCode;
	
	

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}

	public Date getEtl_Date() {
		return Etl_Date;
	}

	public void setEtl_Date(Date etl_Date) {
		Etl_Date = etl_Date;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}
    
    
    
    
    public String getEnSecAcctDelSeqNo() {
        return EnSecAcctDelSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTDEL.ENSECACCTDELSEQNO
     *
     * @param EnSecAcctDelSeqNo the value for PBCRS_REPORT_ENSECACCTDEL.ENSECACCTDELSEQNO
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public void setEnSecAcctDelSeqNo(String EnSecAcctDelSeqNo) {
        this.EnSecAcctDelSeqNo = EnSecAcctDelSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELRECTYPE
     *
     * @return the value of PBCRS_REPORT_ENSECACCTDEL.DELRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public String getDelRecType() {
        return DelRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELRECTYPE
     *
     * @param DelRecType the value for PBCRS_REPORT_ENSECACCTDEL.DELRECTYPE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public void setDelRecType(String DelRecType) {
        this.DelRecType = DelRecType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELRECCODE
     *
     * @return the value of PBCRS_REPORT_ENSECACCTDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public String getDelRecCode() {
        return DelRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELRECCODE
     *
     * @param DelRecCode the value for PBCRS_REPORT_ENSECACCTDEL.DELRECCODE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public void setDelRecCode(String DelRecCode) {
        this.DelRecCode = DelRecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELSGMTCODE
     *
     * @return the value of PBCRS_REPORT_ENSECACCTDEL.DELSGMTCODE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public String getDelSgmtCode() {
        return DelSgmtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELSGMTCODE
     *
     * @param DelSgmtCode the value for PBCRS_REPORT_ENSECACCTDEL.DELSGMTCODE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public void setDelSgmtCode(String DelSgmtCode) {
        this.DelSgmtCode = DelSgmtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELSTARTDATE
     *
     * @return the value of PBCRS_REPORT_ENSECACCTDEL.DELSTARTDATE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public String getDelStartDate() {
        return DelStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELSTARTDATE
     *
     * @param DelStartDate the value for PBCRS_REPORT_ENSECACCTDEL.DELSTARTDATE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public void setDelStartDate(String DelStartDate) {
        this.DelStartDate = DelStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELENDDATE
     *
     * @return the value of PBCRS_REPORT_ENSECACCTDEL.DELENDDATE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public String getDelEndDate() {
        return DelEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENSECACCTDEL.DELENDDATE
     *
     * @param DelEndDate the value for PBCRS_REPORT_ENSECACCTDEL.DELENDDATE
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    public void setDelEndDate(String DelEndDate) {
        this.DelEndDate = DelEndDate;
    }
}