package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;


@XStreamAlias("InSecAcctDel")
public class PbcrsReportInsecacctdel implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1731683845566685458L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTDEL.INSECACCTDELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InSecAcctDelSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTDEL.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTDEL.DELRECCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelRecCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTDEL.DELSGMTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelSgmtCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTDEL.DELSTARTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_INSECACCTDEL.DELENDDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String DelEndDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTDEL.INSECACCTDELSEQNO
	 * @return  the value of PBCRS_REPORT_INSECACCTDEL.INSECACCTDELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInSecAcctDelSeqNo() {
		return InSecAcctDelSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTDEL.INSECACCTDELSEQNO
	 * @param InSecAcctDelSeqNo  the value for PBCRS_REPORT_INSECACCTDEL.INSECACCTDELSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInSecAcctDelSeqNo(String InSecAcctDelSeqNo) {
		this.InSecAcctDelSeqNo = InSecAcctDelSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTDEL.INFRECTYPE
	 * @return  the value of PBCRS_REPORT_INSECACCTDEL.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTDEL.INFRECTYPE
	 * @param InfRecType  the value for PBCRS_REPORT_INSECACCTDEL.INFRECTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTDEL.DELRECCODE
	 * @return  the value of PBCRS_REPORT_INSECACCTDEL.DELRECCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelRecCode() {
		return DelRecCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTDEL.DELRECCODE
	 * @param DelRecCode  the value for PBCRS_REPORT_INSECACCTDEL.DELRECCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelRecCode(String DelRecCode) {
		this.DelRecCode = DelRecCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTDEL.DELSGMTCODE
	 * @return  the value of PBCRS_REPORT_INSECACCTDEL.DELSGMTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelSgmtCode() {
		return DelSgmtCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTDEL.DELSGMTCODE
	 * @param DelSgmtCode  the value for PBCRS_REPORT_INSECACCTDEL.DELSGMTCODE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelSgmtCode(String DelSgmtCode) {
		this.DelSgmtCode = DelSgmtCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTDEL.DELSTARTDATE
	 * @return  the value of PBCRS_REPORT_INSECACCTDEL.DELSTARTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelStartDate() {
		return DelStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTDEL.DELSTARTDATE
	 * @param DelStartDate  the value for PBCRS_REPORT_INSECACCTDEL.DELSTARTDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelStartDate(String DelStartDate) {
		this.DelStartDate = DelStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_INSECACCTDEL.DELENDDATE
	 * @return  the value of PBCRS_REPORT_INSECACCTDEL.DELENDDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getDelEndDate() {
		return DelEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_INSECACCTDEL.DELENDDATE
	 * @param DelEndDate  the value for PBCRS_REPORT_INSECACCTDEL.DELENDDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setDelEndDate(String DelEndDate) {
		this.DelEndDate = DelEndDate;
	}
}