package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("CtrctCertRel")
public class PbcrsReportEnctrctcertrel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7769393161997291794L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
	@XStreamOmitField
    private String CtrctCertRelSgmtSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSEQNO
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
	@XStreamOmitField
    private String CtrctCertRelSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTCERTREL.BRERTYPE
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    private String BrerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELNAME
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    private String CertRelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDTYPE
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    private String CertRelIDType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDNUM
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    private String CertRelIDNum;
    
    @XStreamOmitField
    private String ReportFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public String getCtrctCertRelSgmtSeqNo() {
        return CtrctCertRelSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
     *
     * @param CtrctCertRelSgmtSeqNo the value for PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSGMTSEQNO
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public void setCtrctCertRelSgmtSeqNo(String CtrctCertRelSgmtSeqNo) {
        this.CtrctCertRelSgmtSeqNo = CtrctCertRelSgmtSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSEQNO
     *
     * @return the value of PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSEQNO
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public String getCtrctCertRelSeqNo() {
        return CtrctCertRelSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSEQNO
     *
     * @param CtrctCertRelSeqNo the value for PBCRS_REPORT_ENCTRCTCERTREL.CTRCTCERTRELSEQNO
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public void setCtrctCertRelSeqNo(String CtrctCertRelSeqNo) {
        this.CtrctCertRelSeqNo = CtrctCertRelSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.BRERTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTCERTREL.BRERTYPE
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public String getBrerType() {
        return BrerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.BRERTYPE
     *
     * @param BrerType the value for PBCRS_REPORT_ENCTRCTCERTREL.BRERTYPE
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public void setBrerType(String BrerType) {
        this.BrerType = BrerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELNAME
     *
     * @return the value of PBCRS_REPORT_ENCTRCTCERTREL.CERTRELNAME
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public String getCertRelName() {
        return CertRelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELNAME
     *
     * @param CertRelName the value for PBCRS_REPORT_ENCTRCTCERTREL.CERTRELNAME
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public void setCertRelName(String CertRelName) {
        this.CertRelName = CertRelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDTYPE
     *
     * @return the value of PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDTYPE
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public String getCertRelIDType() {
        return CertRelIDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDTYPE
     *
     * @param CertRelIDType the value for PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDTYPE
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public void setCertRelIDType(String CertRelIDType) {
        this.CertRelIDType = CertRelIDType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDNUM
     *
     * @return the value of PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDNUM
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public String getCertRelIDNum() {
        return CertRelIDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDNUM
     *
     * @param CertRelIDNum the value for PBCRS_REPORT_ENCTRCTCERTREL.CERTRELIDNUM
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    public void setCertRelIDNum(String CertRelIDNum) {
        this.CertRelIDNum = CertRelIDNum;
    }

	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
    
    
}