package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("MotgaCltalCtrctBsSgmt")
public class PbcrsReportMotcltctrbssgmt implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column
	 * PBCRS_REPORT_MOTCLTCTRBSSGMT.MOTGACLTALCTRCTBSSGMTSEQNO
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	@XStreamOmitField
	private String MotgaCltalCtrctBsSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.INFRECTYPE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String InfRecType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CCCODE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String CcCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String RptDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATECODE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String RptDateCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.INFOIDTYPE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String InfoIDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.NAME
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTTYPE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String CertType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTNUM
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String CertNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.MNGMTORGCODE
	 * 
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	private String MngmtOrgCode;
	/**
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
	 * 
	 * @mbggenerated Wed Apr 24 09:13:16 CST 2019
	 */
	@XStreamOmitField
	private String reportflag;
	@XStreamOmitField
	private String IsDel;
	@XStreamOmitField
	private String SourceSys;

	private String orgCode;

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getIsDel() {
		return IsDel;
	}

	public void setIsDel(String isDel) {
		IsDel = isDel;
	}

	public String getSourceSys() {
		return SourceSys;
	}

	public void setSourceSys(String sourceSys) {
		SourceSys = sourceSys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
	 * 
	 * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
	 * 
	 * @mbggenerated Wed Apr 24 09:13:16 CST 2019
	 */
	public String getReportflag() {
		return reportflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
	 * 
	 * @param reportflag
	 *            the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
	 * 
	 * @mbggenerated Wed Apr 24 09:13:16 CST 2019
	 */
	public void setReportflag(String reportflag) {
		this.reportflag = reportflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_MOTCLTCTRBSSGMT.MOTGACLTALCTRCTBSSGMTSEQNO
	 * 
	 * @return the value of
	 *         PBCRS_REPORT_MOTCLTCTRBSSGMT.MOTGACLTALCTRCTBSSGMTSEQNO
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMotgaCltalCtrctBsSgmtSeqNo() {
		return MotgaCltalCtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * PBCRS_REPORT_MOTCLTCTRBSSGMT.MOTGACLTALCTRCTBSSGMTSEQNO
	 * 
	 * @param MotgaCltalCtrctBsSgmtSeqNo
	 *            the value for
	 *            PBCRS_REPORT_MOTCLTCTRBSSGMT.MOTGACLTALCTRCTBSSGMTSEQNO
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMotgaCltalCtrctBsSgmtSeqNo(String MotgaCltalCtrctBsSgmtSeqNo) {
		this.MotgaCltalCtrctBsSgmtSeqNo = MotgaCltalCtrctBsSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.INFRECTYPE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.INFRECTYPE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getInfRecType() {
		return InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.INFRECTYPE
	 * 
	 * @param InfRecType
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.INFRECTYPE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setInfRecType(String InfRecType) {
		this.InfRecType = InfRecType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CCCODE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.CCCODE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCcCode() {
		return CcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CCCODE
	 * 
	 * @param CcCode
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.CCCODE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCcCode(String CcCode) {
		this.CcCode = CcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getRptDate() {
		return RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATE
	 * 
	 * @param RptDate
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setRptDate(String RptDate) {
		this.RptDate = RptDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATECODE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATECODE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getRptDateCode() {
		return RptDateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATECODE
	 * 
	 * @param RptDateCode
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.RPTDATECODE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setRptDateCode(String RptDateCode) {
		this.RptDateCode = RptDateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.INFOIDTYPE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.INFOIDTYPE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getInfoIDType() {
		return InfoIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.INFOIDTYPE
	 * 
	 * @param InfoIDType
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.INFOIDTYPE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setInfoIDType(String InfoIDType) {
		this.InfoIDType = InfoIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.NAME
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.NAME
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getName() {
		return Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.NAME
	 * 
	 * @param Name
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.NAME
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setName(String Name) {
		this.Name = Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTTYPE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTTYPE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCertType() {
		return CertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTTYPE
	 * 
	 * @param CertType
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTTYPE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCertType(String CertType) {
		this.CertType = CertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTNUM
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTNUM
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getCertNum() {
		return CertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTNUM
	 * 
	 * @param CertNum
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.CERTNUM
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setCertNum(String CertNum) {
		this.CertNum = CertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.MNGMTORGCODE
	 * 
	 * @return the value of PBCRS_REPORT_MOTCLTCTRBSSGMT.MNGMTORGCODE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public String getMngmtOrgCode() {
		return MngmtOrgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_MOTCLTCTRBSSGMT.MNGMTORGCODE
	 * 
	 * @param MngmtOrgCode
	 *            the value for PBCRS_REPORT_MOTCLTCTRBSSGMT.MNGMTORGCODE
	 * @mbggenerated Tue Mar 26 16:20:32 CST 2019
	 */
	public void setMngmtOrgCode(String MngmtOrgCode) {
		this.MngmtOrgCode = MngmtOrgCode;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 8836674576504402242L;
}