package com.hkbank.pbcrs.model;

import java.io.Serializable;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("GuarMotgaCltalCtrctInfSgmt")
public class PbcrsReportEGuamotcltctrsgmt implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7739140823227094024L;
	
	@XStreamImplicit
    private List<PbcrsReportGuacccinf> GuaCccInf;
	
	public List<PbcrsReportGuacccinf> getGuaCccInf() {
		return GuaCccInf;
	}

	public void setGuaCccInf(List<PbcrsReportGuacccinf> guaCccInf) {
		GuaCccInf = guaCccInf;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column
	 * PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * 
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String GuaMotCltCtrInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * 
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	private String CcNm;
	
	
    @XStreamOmitField
    private String ReportFlag;
	public String getReportFlag() {
		return ReportFlag;
	}

	public void setReportFlag(String reportFlag) {
		ReportFlag = reportFlag;
	}
	
	@XStreamImplicit
	private List<PbcrsReportCccinf> CccInf;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * 
	 * @return the value of
	 *         PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	public String getGuaMotCltCtrInfSgmtSeqNo() {
		return GuaMotCltCtrInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * 
	 * @param GuaMotCltCtrInfSgmtSeqNo
	 *            the value for
	 *            PBCRS_REPORT_GUAMOTCLTCTRSGMT.GUAMOTCLTCTRINFSGMTSEQNO
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	public void setGuaMotCltCtrInfSgmtSeqNo(String GuaMotCltCtrInfSgmtSeqNo) {
		this.GuaMotCltCtrInfSgmtSeqNo = GuaMotCltCtrInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * 
	 * @return the value of PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	public String getCcNm() {
		return CcNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * 
	 * @param CcNm
	 *            the value for PBCRS_REPORT_GUAMOTCLTCTRSGMT.CCNM
	 * @mbggenerated Fri Mar 15 10:54:59 CST 2019
	 */
	public void setCcNm(String CcNm) {
		this.CcNm = CcNm;
	}

	public List<PbcrsReportCccinf> getCccInf() {
		return CccInf;
	}

	public void setCccInf(List<PbcrsReportCccinf> cccInf) {
		CccInf = cccInf;
	}

}