package com.hkbank.pbcrs.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;


@XStreamAlias("PleInf")
public class PbcrsReportPleinf implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7478911998213291587L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String ComRecInfSgmtSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	@XStreamOmitField
	private String PleInfSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLETYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.MOTGAPROPTIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String MotgaProptIDType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLECERTID
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleCertID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEDISTR
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleDistr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEVALUE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLECY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleCy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.VALORGTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ValOrgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.VALDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String ValDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEDGORTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PledgorType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEDGORNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PledgorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEORCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleorCertType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEORCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleorCertNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PBCRS_REPORT_PLEINF.PLEDESC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	private String PleDesc;
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
	@XStreamOmitField
   private String reportflag;
	 /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @return the value of PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public String getReportflag() {
       return reportflag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @param reportflag the value for PBCRS_REPORT_BSSGMT.REPORTFLAG
    *
    * @mbggenerated Wed Apr 24 09:13:16 CST 2019
    */
   public void setReportflag(String reportflag) {
       this.reportflag = reportflag;
   }
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.COMRECINFSGMTSEQNO
	 * @return  the value of PBCRS_REPORT_PLEINF.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getComRecInfSgmtSeqNo() {
		return ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.COMRECINFSGMTSEQNO
	 * @param ComRecInfSgmtSeqNo  the value for PBCRS_REPORT_PLEINF.COMRECINFSGMTSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setComRecInfSgmtSeqNo(String ComRecInfSgmtSeqNo) {
		this.ComRecInfSgmtSeqNo = ComRecInfSgmtSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEINFSEQNO
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleInfSeqNo() {
		return PleInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEINFSEQNO
	 * @param PleInfSeqNo  the value for PBCRS_REPORT_PLEINF.PLEINFSEQNO
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleInfSeqNo(String PleInfSeqNo) {
		this.PleInfSeqNo = PleInfSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLETYPE
	 * @return  the value of PBCRS_REPORT_PLEINF.PLETYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleType() {
		return PleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLETYPE
	 * @param PleType  the value for PBCRS_REPORT_PLEINF.PLETYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleType(String PleType) {
		this.PleType = PleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.MOTGAPROPTIDTYPE
	 * @return  the value of PBCRS_REPORT_PLEINF.MOTGAPROPTIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getMotgaProptIDType() {
		return MotgaProptIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.MOTGAPROPTIDTYPE
	 * @param MotgaProptIDType  the value for PBCRS_REPORT_PLEINF.MOTGAPROPTIDTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setMotgaProptIDType(String MotgaProptIDType) {
		this.MotgaProptIDType = MotgaProptIDType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLECERTID
	 * @return  the value of PBCRS_REPORT_PLEINF.PLECERTID
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleCertID() {
		return PleCertID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLECERTID
	 * @param PleCertID  the value for PBCRS_REPORT_PLEINF.PLECERTID
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleCertID(String PleCertID) {
		this.PleCertID = PleCertID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEDISTR
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEDISTR
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleDistr() {
		return PleDistr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEDISTR
	 * @param PleDistr  the value for PBCRS_REPORT_PLEINF.PLEDISTR
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleDistr(String PleDistr) {
		this.PleDistr = PleDistr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEVALUE
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEVALUE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleValue() {
		return PleValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEVALUE
	 * @param PleValue  the value for PBCRS_REPORT_PLEINF.PLEVALUE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleValue(String PleValue) {
		this.PleValue = PleValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLECY
	 * @return  the value of PBCRS_REPORT_PLEINF.PLECY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleCy() {
		return PleCy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLECY
	 * @param PleCy  the value for PBCRS_REPORT_PLEINF.PLECY
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleCy(String PleCy) {
		this.PleCy = PleCy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.VALORGTYPE
	 * @return  the value of PBCRS_REPORT_PLEINF.VALORGTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getValOrgType() {
		return ValOrgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.VALORGTYPE
	 * @param ValOrgType  the value for PBCRS_REPORT_PLEINF.VALORGTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setValOrgType(String ValOrgType) {
		this.ValOrgType = ValOrgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.VALDATE
	 * @return  the value of PBCRS_REPORT_PLEINF.VALDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getValDate() {
		return ValDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.VALDATE
	 * @param ValDate  the value for PBCRS_REPORT_PLEINF.VALDATE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setValDate(String ValDate) {
		this.ValDate = ValDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEDGORTYPE
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEDGORTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPledgorType() {
		return PledgorType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEDGORTYPE
	 * @param PledgorType  the value for PBCRS_REPORT_PLEINF.PLEDGORTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPledgorType(String PledgorType) {
		this.PledgorType = PledgorType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEDGORNAME
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEDGORNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPledgorName() {
		return PledgorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEDGORNAME
	 * @param PledgorName  the value for PBCRS_REPORT_PLEINF.PLEDGORNAME
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPledgorName(String PledgorName) {
		this.PledgorName = PledgorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEORCERTTYPE
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEORCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleorCertType() {
		return PleorCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEORCERTTYPE
	 * @param PleorCertType  the value for PBCRS_REPORT_PLEINF.PLEORCERTTYPE
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleorCertType(String PleorCertType) {
		this.PleorCertType = PleorCertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEORCERTNUM
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEORCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleorCertNum() {
		return PleorCertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEORCERTNUM
	 * @param PleorCertNum  the value for PBCRS_REPORT_PLEINF.PLEORCERTNUM
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleorCertNum(String PleorCertNum) {
		this.PleorCertNum = PleorCertNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PBCRS_REPORT_PLEINF.PLEDESC
	 * @return  the value of PBCRS_REPORT_PLEINF.PLEDESC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public String getPleDesc() {
		return PleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PBCRS_REPORT_PLEINF.PLEDESC
	 * @param PleDesc  the value for PBCRS_REPORT_PLEINF.PLEDESC
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	public void setPleDesc(String PleDesc) {
		this.PleDesc = PleDesc;
	}
}