package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnguaracctbssgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnguaracctbssgmtMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENGUARACCTBSSGMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    int deleteByPrimaryKey(String GuarAcctBsSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENGUARACCTBSSGMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    int insert(PbcrsReportEnguaracctbssgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENGUARACCTBSSGMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    PbcrsReportEnguaracctbssgmt selectByPrimaryKey(String GuarAcctBsSgmtSeqNo);
    
    PbcrsReportEnguaracctbssgmt selectByKey(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENGUARACCTBSSGMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    List<PbcrsReportEnguaracctbssgmt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENGUARACCTBSSGMT
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnguaracctbssgmt record);
    
    int getKey();
    
    
    int selectAllbyContCount(Map<String,Object> map);
    
    List<Map<String,Object>>selectAllbyContPage(Map<String,Object> map);
    
    PbcrsReportEnguaracctbssgmt selectByEnSecAcctInfSeqNo(String nSecAcctInfSeqNo);
    
    PbcrsReportEnguaracctbssgmt selectByEnSecAcctInfMSeqNo(String nSecAcctInfSeqNo);
    
    int updateByIsDel(Map<String,Object> param);
}