package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportIncandexpstbssgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportIncandexpstbssgmtMapper extends BaseExternalSpi {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTBSSGMT
	 * @mbggenerated  Tue Apr 09 19:47:24 CST 2019
	 */
	int deleteByPrimaryKey(String IncomeAndESBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTBSSGMT
	 * @mbggenerated  Tue Apr 09 19:47:24 CST 2019
	 */
	int insert(PbcrsReportIncandexpstbssgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTBSSGMT
	 * @mbggenerated  Tue Apr 09 19:47:24 CST 2019
	 */
	PbcrsReportIncandexpstbssgmt selectByPrimaryKey(
			String IncomeAndESBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTBSSGMT
	 * @mbggenerated  Tue Apr 09 19:47:24 CST 2019
	 */
	List<PbcrsReportIncandexpstbssgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTBSSGMT
	 * @mbggenerated  Tue Apr 09 19:47:24 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportIncandexpstbssgmt record);
	
	int getKey();
	
	int selectAllbyContCount(Map<String,Object> map);
	
	List<Map<String,Object>> selectAllbyContPage(Map<String,Object> map);
	
	PbcrsReportIncandexpstbssgmt selectByIncomeAndESSeqNo(String IncomeAndESSeqNo);
	
	
    /**
     * 修改基础段时点为：更新
     * @param param
     * @return
     */
    int updateByKey(Map<String,Object> param);
    /**
     * 修改基础段flag和rptdate
     * @param param
     * @return
     */
    int updateByFlagAndDate(Map<String,Object> params);
    int updateByIsDel(Map<String,Object> param);
}