package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportBalancesheet2007;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface PbcrsReportBalancesheet2007Mapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEET2007
     *
     * @mbggenerated Mon Mar 18 10:16:17 CST 2019
     */
    int deleteByPrimaryKey(String BalanceSheetBsSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEET2007
     *
     * @mbggenerated Mon Mar 18 10:16:17 CST 2019
     */
    int insert(PbcrsReportBalancesheet2007 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEET2007
     *
     * @mbggenerated Mon Mar 18 10:16:17 CST 2019
     */
    PbcrsReportBalancesheet2007 selectByPrimaryKey(String BalanceSheetBsSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEET2007
     *
     * @mbggenerated Mon Mar 18 10:16:17 CST 2019
     */
    List<PbcrsReportBalancesheet2007> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEET2007
     *
     * @mbggenerated Mon Mar 18 10:16:17 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportBalancesheet2007 record);
    
    int getKey();
    
    
    PbcrsReportBalancesheet2007 selectByBalanceSheetSeqNo(String BalanceSheetSeqNo);
}