package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnsecacctdel;

import java.util.List;
import java.util.Map;

public interface PbcrsReportEnsecacctdelMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTDEL
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    int deleteByPrimaryKey(Map<String,String> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTDEL
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    int insert(PbcrsReportEnsecacctdel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTDEL
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    PbcrsReportEnsecacctdel selectByPrimaryKey(String EnSecAcctDelSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTDEL
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    List<PbcrsReportEnsecacctdel> selectAll();
    
    List<PbcrsReportEnsecacctdel> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTDEL
     *
     * @mbggenerated Fri Mar 15 11:31:33 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnsecacctdel record);
}