package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnbasinfmmbinf;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportEnbasinfmmbinfMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFMMBINF
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    int deleteByPrimaryKey(@Param("MnMmbInfSgmtSeqNo") String MnMmbInfSgmtSeqNo, @Param("MmbInfSeqNo") String MmbInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFMMBINF
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    int insert(PbcrsReportEnbasinfmmbinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFMMBINF
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    PbcrsReportEnbasinfmmbinf selectByPrimaryKey(@Param("MnMmbInfSgmtSeqNo") String MnMmbInfSgmtSeqNo, @Param("MmbInfSeqNo") String MmbInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFMMBINF
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    List<PbcrsReportEnbasinfmmbinf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFMMBINF
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnbasinfmmbinf record);
    
    List<PbcrsReportEnbasinfmmbinf> selectAllbyidSeqno(String idSeqno);
    
    int getKey();
}