package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnaccinfmdfbssgmt;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportEnaccinfmdfbssgmtMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCINFMDFBSSGMT
	 * @mbggenerated  Fri Mar 15 09:36:37 CST 2019
	 */
	int deleteByPrimaryKey(@Param("BsSgmtSeqNo")String BsSgmtSeqNo,@Param("MdfcSgmtCode")String MsgCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCINFMDFBSSGMT
	 * @mbggenerated  Fri Mar 15 09:36:37 CST 2019
	 */
	int insert(PbcrsReportEnaccinfmdfbssgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCINFMDFBSSGMT
	 * @mbggenerated  Fri Mar 15 09:36:37 CST 2019
	 */
	PbcrsReportEnaccinfmdfbssgmt selectByPrimaryKey(String BsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCINFMDFBSSGMT
	 * @mbggenerated  Fri Mar 15 09:36:37 CST 2019
	 */
	List<PbcrsReportEnaccinfmdfbssgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCINFMDFBSSGMT
	 * @mbggenerated  Fri Mar 15 09:36:37 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportEnaccinfmdfbssgmt record);
	
	int getKey();
}