package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEGuarltrepinfsgmt;
import com.hkbank.pbcrs.model.PbcrsReportGuarltrepinfsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEGuarltrepinfsgmtMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_GUARLTREPINFSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String GuarRltRepymtInfSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_GUARLTREPINFSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportEGuarltrepinfsgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_GUARLTREPINFSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportEGuarltrepinfsgmt selectByPrimaryKey(String GuarRltRepymtInfSgmtSeqNo);
	
	PbcrsReportGuarltrepinfsgmt selectByKey(Map map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_GUARLTREPINFSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportEGuarltrepinfsgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_GUARLTREPINFSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportEGuarltrepinfsgmt record);
	
	int updateByMap(Map map);
	
	  int getKey();
	    
	PbcrsReportEGuarltrepinfsgmt selectByEnSecAcctInfSeqNo(String EnSecAcctInfSeqNo);
	    
	PbcrsReportEGuarltrepinfsgmt selectByEnSecAcctInfMSeqNo(String EnSecAcctInfSeqNo);
}