package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportActlbltyinfsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportActlbltyinfsgmtMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ACTLBLTYINFSGMT
     *
     * @mbggenerated Thu Mar 14 09:30:14 CST 2019
     */
    int deleteByPrimaryKey(String ActLbltyInfSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ACTLBLTYINFSGMT
     *
     * @mbggenerated Thu Mar 14 09:30:14 CST 2019
     */
    int insert(PbcrsReportActlbltyinfsgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ACTLBLTYINFSGMT
     *
     * @mbggenerated Thu Mar 14 09:30:14 CST 2019
     */
    PbcrsReportActlbltyinfsgmt selectByPrimaryKey(String ActLbltyInfSgmtSeqNo);
    
    PbcrsReportActlbltyinfsgmt selectByKey(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ACTLBLTYINFSGMT
     *
     * @mbggenerated Thu Mar 14 09:30:14 CST 2019
     */
    List<PbcrsReportActlbltyinfsgmt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ACTLBLTYINFSGMT
     *
     * @mbggenerated Thu Mar 14 09:30:14 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportActlbltyinfsgmt record);
    
    int getKey();
	
	

    PbcrsReportActlbltyinfsgmt selectByEnAcctInfSeqNo(String EnAcctInfSeqNo);
    PbcrsReportActlbltyinfsgmt selectByEnAcctInfMSeqNo(String EnAcctInfSeqNo);
}