package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnbasinfidrec;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportEnbasinfidrecMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFIDREC
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    int deleteByPrimaryKey(@Param("IDSgmtSeqNo") String IDSgmtSeqNo, @Param("IDSgmtListSeqNo") String IDSgmtListSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFIDREC
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    int insert(PbcrsReportEnbasinfidrec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFIDREC
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    PbcrsReportEnbasinfidrec selectByPrimaryKey(@Param("IDSgmtSeqNo") String IDSgmtSeqNo, @Param("IDSgmtListSeqNo") String IDSgmtListSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFIDREC
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    List<PbcrsReportEnbasinfidrec> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENBASINFIDREC
     *
     * @mbggenerated Thu Mar 14 15:00:52 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnbasinfidrec record);
    
    List<PbcrsReportEnbasinfidrec> selectAllbyidSeqno(String idSeqno);
    
    int getKey();
}