package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnbasinfactcotinf;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportEnbasinfactcotinfMapper extends BaseExternalSpi{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENBASINFACTCOTINF
	 * @mbggenerated  Thu Mar 14 15:00:52 CST 2019
	 */
	int deleteByPrimaryKey(
			@Param("ActuCotrlInfSgmtSeqNo") String ActuCotrlInfSgmtSeqNo,
			@Param("ActuCotrlInfSeqNo") String ActuCotrlInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENBASINFACTCOTINF
	 * @mbggenerated  Thu Mar 14 15:00:52 CST 2019
	 */
	int insert(PbcrsReportEnbasinfactcotinf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENBASINFACTCOTINF
	 * @mbggenerated  Thu Mar 14 15:00:52 CST 2019
	 */
	PbcrsReportEnbasinfactcotinf selectByPrimaryKey(
			@Param("ActuCotrlInfSgmtSeqNo") String ActuCotrlInfSgmtSeqNo,
			@Param("ActuCotrlInfSeqNo") String ActuCotrlInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENBASINFACTCOTINF
	 * @mbggenerated  Thu Mar 14 15:00:52 CST 2019
	 */
	List<PbcrsReportEnbasinfactcotinf> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENBASINFACTCOTINF
	 * @mbggenerated  Thu Mar 14 15:00:52 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportEnbasinfactcotinf record);
	
    
    List<PbcrsReportEnbasinfactcotinf> selectAllbyidSeqno(String idSeqno);
    
    int getKey();
    
}