package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInidefctinf;

import java.util.List;
import java.util.Map;

public interface PbcrsReportInidefctinfMapper extends BaseExternalSpi{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String InIDEfctInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportInidefctinf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportInidefctinf selectByPrimaryKey(String InIDEfctInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportInidefctinf> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportInidefctinf record);

	List<PbcrsReportInidefctinf> selectByMap(Map<String, Object> paramMap);

	int selectByMapCount(Map<String, Object> paramMap);
}