package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportIncomesbssgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportIncomesbssgmtMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESBSSGMT
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	int deleteByPrimaryKey(String IncomeStatementPABsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESBSSGMT
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	int insert(PbcrsReportIncomesbssgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESBSSGMT
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	PbcrsReportIncomesbssgmt selectByPrimaryKey(
			String IncomeStatementPABsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESBSSGMT
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	List<PbcrsReportIncomesbssgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESBSSGMT
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportIncomesbssgmt record);
	
	int selectAllbyContCount(Map<String,Object> map);
	
	List<Map<String,Object>> selectAllbyContPage(Map<String,Object> map);
	
	int getKey();
	
	PbcrsReportIncomesbssgmt selectByIncomeStatementPASeqNo(String IncomeStatementPASeqNo);
	
    /**
     * 修改基础段时点为：更新
     * @param param
     * @return
     */
    int updateByKey(Map<String,Object> param);
    
	int updateByIsDel(Map<String,Object> param);
	
}