package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportIncandexpsta;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportIncandexpstaMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTA
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    int deleteByPrimaryKey(String IncomeAndESSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTA
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    int insert(PbcrsReportIncandexpsta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTA
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    PbcrsReportIncandexpsta selectByPrimaryKey(String IncomeAndESSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTA
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    List<PbcrsReportIncandexpsta> selectAll();
    
    List<PbcrsReportIncandexpsta> selectByMap(Map map);
    
    int selectByMapCount(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INCANDEXPSTA
     *
     * @mbggenerated Mon Mar 18 11:03:15 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportIncandexpsta record);
    
    int getKey();
    
    int insertMod(Map<String,Object> map);
}