package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnacctcredsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnacctcredsgmtMapper extends BaseExternalSpi{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCTCREDSGMT
	 * @mbggenerated  Thu Mar 14 09:27:12 CST 2019
	 */
	int deleteByPrimaryKey(String AcctCredSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCTCREDSGMT
	 * @mbggenerated  Thu Mar 14 09:27:12 CST 2019
	 */
	int insert(PbcrsReportEnacctcredsgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCTCREDSGMT
	 * @mbggenerated  Thu Mar 14 09:27:12 CST 2019
	 */	
	PbcrsReportEnacctcredsgmt selectByPrimaryKey(String AcctCredSgmtSeqNo);
	
	PbcrsReportEnacctcredsgmt selectByKey(Map map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCTCREDSGMT
	 * @mbggenerated  Thu Mar 14 09:27:12 CST 2019
	 */
	List<PbcrsReportEnacctcredsgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENACCTCREDSGMT
	 * @mbggenerated  Thu Mar 14 09:27:12 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportEnacctcredsgmt record);
	
	int getKey();
	
	

	PbcrsReportEnacctcredsgmt selectByEnAcctInfSeqNo(String EnAcctInfSeqNo);
	PbcrsReportEnacctcredsgmt selectByEnAcctInfMSeqNo(String EnAcctInfSeqNo);
}