package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnctrctinfidcagsi;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnctrctinfidcagsiMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFIDCAGSI
     *
     * @mbggenerated Thu Mar 28 09:45:41 CST 2019
     */
    int deleteByPrimaryKey(String EnCtrctInfIDCagsInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFIDCAGSI
     *
     * @mbggenerated Thu Mar 28 09:45:41 CST 2019
     */
    int insert(PbcrsReportEnctrctinfidcagsi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFIDCAGSI
     *
     * @mbggenerated Thu Mar 28 09:45:41 CST 2019
     */
    PbcrsReportEnctrctinfidcagsi selectByPrimaryKey(String EnCtrctInfIDCagsInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFIDCAGSI
     *
     * @mbggenerated Thu Mar 28 09:45:41 CST 2019
     */
    List<PbcrsReportEnctrctinfidcagsi> selectAll();
    
    List<PbcrsReportEnctrctinfidcagsi> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFIDCAGSI
     *
     * @mbggenerated Thu Mar 28 09:45:41 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnctrctinfidcagsi record);
    int getKey();
}