package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEncccinf;

import java.util.List;
import java.util.Map;

public interface PbcrsReportEncccinfMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENCCCINF
	 * @mbggenerated  Mon Mar 25 16:48:32 CST 2019
	 */
	int insert(PbcrsReportEncccinf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENCCCINF
	 * @mbggenerated  Mon Mar 25 16:48:32 CST 2019
	 */
	List<PbcrsReportEncccinf> selectAll();
	
	List<PbcrsReportEncccinf> selectByKey(Map map);
}