package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportBalancesheet;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;


@Repository
public interface PbcrsReportBalancesheetMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_BALANCESHEET
	 * @mbggenerated  Mon Mar 18 10:16:17 CST 2019
	 */
	int deleteByPrimaryKey(String BalanceSheetSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_BALANCESHEET
	 * @mbggenerated  Mon Mar 18 10:16:17 CST 2019
	 */
	int insert(PbcrsReportBalancesheet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_BALANCESHEET
	 * @mbggenerated  Mon Mar 18 10:16:17 CST 2019
	 */
	PbcrsReportBalancesheet selectByPrimaryKey(String BalanceSheetSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_BALANCESHEET
	 * @mbggenerated  Mon Mar 18 10:16:17 CST 2019
	 */
	List<PbcrsReportBalancesheet> selectAll();
	
	List<PbcrsReportBalancesheet> selectByMap(Map map);
	
	int selectByMapCount(Map map);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_BALANCESHEET
	 * @mbggenerated  Mon Mar 18 10:16:17 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportBalancesheet record);
	
	int insertMod(Map<String,Object> map);
	
	int getKey();
}