package com.hkbank.pbcrs.mapper;


import com.hkbank.pbcrs.model.PbcrsReportBalancesheetdlt;

import java.util.List;
import java.util.Map;

public interface PbcrsReportBalancesheetdltMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEETDLT
     *
     * @mbggenerated Tue Mar 26 13:43:34 CST 2019
     */
    int deleteByPrimaryKey(String BalanceSheetDltSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEETDLT
     *
     * @mbggenerated Tue Mar 26 13:43:34 CST 2019
     */
    int insert(PbcrsReportBalancesheetdlt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEETDLT
     *
     * @mbggenerated Tue Mar 26 13:43:34 CST 2019
     */
    PbcrsReportBalancesheetdlt selectByPrimaryKey(String BalanceSheetDltSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEETDLT
     *
     * @mbggenerated Tue Mar 26 13:43:34 CST 2019
     */
    List<PbcrsReportBalancesheetdlt> selectAll();
    
    List<PbcrsReportBalancesheetdlt> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_BALANCESHEETDLT
     *
     * @mbggenerated Tue Mar 26 13:43:34 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportBalancesheetdlt record);
}