package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportIncomesprofitappr;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportIncomesprofitapprMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESPROFITAPPR
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	int deleteByPrimaryKey(String IncomeStatementPASeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESPROFITAPPR
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	int insert(PbcrsReportIncomesprofitappr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESPROFITAPPR
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	PbcrsReportIncomesprofitappr selectByPrimaryKey(
			String IncomeStatementPASeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESPROFITAPPR
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	List<PbcrsReportIncomesprofitappr> selectAll();
	
	List<PbcrsReportIncomesprofitappr> selectByMap(Map map);
	
	int selectByMapCount(Map map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCOMESPROFITAPPR
	 * @mbggenerated  Fri Mar 15 16:25:20 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportIncomesprofitappr record);
	
	int getKey();
	
	int insertMod(Map<String,Object> map);
}