package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportErrinf;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportErrinfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ERRINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    int deleteByPrimaryKey(@Param("Fbinfseqno") Short Fbinfseqno, @Param("ErrInfseqno") Short ErrInfseqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ERRINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    int insert(PbcrsReportErrinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ERRINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    PbcrsReportErrinf selectByPrimaryKey(@Param("Fbinfseqno") Short Fbinfseqno, @Param("ErrInfseqno") Short ErrInfseqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ERRINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    List<PbcrsReportErrinf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ERRINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportErrinf record);
    
    int getKey();
}