package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportAcctbssgmt;

import java.util.List;
import java.util.Map;

public interface PbcrsReportAcctbssgmtMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ACCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String AcctBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ACCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportAcctbssgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ACCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportAcctbssgmt selectByPrimaryKey(String AcctBsSgmtSeqNo);
	
	PbcrsReportAcctbssgmt selectByPrimaryKeyModify(String AcctBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ACCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportAcctbssgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ACCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportAcctbssgmt record);

	int getKey();

	int getCount(Map<String, Object> param);

	List<Map<String, Object>> getAllandPage(Map<String, Object> param);

	int deleteByPrimaryKeyM(String AcctBsSgmtSeqNo);


	int confirm(Map<String, Object> param);

    int selectBadCount(Map<String, Object> param);
}