package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEncagoftrdinf;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEncagoftrdinfMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCAGOFTRDINF
     *
     * @mbggenerated Thu Mar 14 09:33:53 CST 2019
     */
    int deleteByPrimaryKey(@Param("AcctSpecTrstDspnSgmtSeqNo") String AcctSpecTrstDspnSgmtSeqNo, @Param("CagOfTrdInfSeqNo") String CagOfTrdInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCAGOFTRDINF
     *
     * @mbggenerated Thu Mar 14 09:33:53 CST 2019
     */
    int insert(PbcrsReportEncagoftrdinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCAGOFTRDINF
     *
     * @mbggenerated Thu Mar 14 09:33:53 CST 2019
     */
    PbcrsReportEncagoftrdinf selectByPrimaryKey(@Param("AcctSpecTrstDspnSgmtSeqNo") String AcctSpecTrstDspnSgmtSeqNo, @Param("CagOfTrdInfSeqNo") String CagOfTrdInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCAGOFTRDINF
     *
     * @mbggenerated Thu Mar 14 09:33:53 CST 2019
     */
    List<PbcrsReportEncagoftrdinf> selectAll();
    
    List<PbcrsReportEncagoftrdinf> selectByKey(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCAGOFTRDINF
     *
     * @mbggenerated Thu Mar 14 09:33:53 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEncagoftrdinf record);
    int getKey();
    
    List<PbcrsReportEncagoftrdinf> selectByAcctSpecTrstDspnSgmtSeqNo(String AcctSpecTrstDspnSgmtSeqNo);
}