package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInsbalshesgmt;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportInsbalshesgmtMapper extends BaseExternalSpi {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHESGMT
	 * @mbggenerated  Tue Apr 09 18:32:22 CST 2019
	 */
	int deleteByPrimaryKey(String InstitutionBSSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHESGMT
	 * @mbggenerated  Tue Apr 09 18:32:22 CST 2019
	 */
	int insert(PbcrsReportInsbalshesgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHESGMT
	 * @mbggenerated  Tue Apr 09 18:32:22 CST 2019
	 */
	PbcrsReportInsbalshesgmt selectByPrimaryKey(String InstitutionBSSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHESGMT
	 * @mbggenerated  Tue Apr 09 18:32:22 CST 2019
	 */
	List<PbcrsReportInsbalshesgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHESGMT
	 * @mbggenerated  Tue Apr 09 18:32:22 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportInsbalshesgmt record);
	
	int getKey();
	PbcrsReportInsbalshesgmt selectByInstitutionBSSeqNo(String InstitutionBSSeqNo);
	
}