package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportGuacccinf;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PbcrsReportGuacccinfMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GUACCCINF
     *
     * @mbggenerated Fri Mar 15 10:54:59 CST 2019
     */
    int deleteByPrimaryKey(@Param("GuaMotCltCtrInfSgmtSeqNo") String GuaMotCltCtrInfSgmtSeqNo, @Param("CccInfSeqNo") String CccInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GUACCCINF
     *
     * @mbggenerated Fri Mar 15 10:54:59 CST 2019
     */
    int insert(PbcrsReportGuacccinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GUACCCINF
     *
     * @mbggenerated Fri Mar 15 10:54:59 CST 2019
     */
    PbcrsReportGuacccinf selectByPrimaryKey(@Param("GuaMotCltCtrInfSgmtSeqNo") String GuaMotCltCtrInfSgmtSeqNo, @Param("CccInfSeqNo") String CccInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GUACCCINF
     *
     * @mbggenerated Fri Mar 15 10:54:59 CST 2019
     */
    List<PbcrsReportGuacccinf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GUACCCINF
     *
     * @mbggenerated Fri Mar 15 10:54:59 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportGuacccinf record);
}