package com.hkbank.pbcrs.mapper;


import com.hkbank.pbcrs.model.PbcrsReportGsrltrepymtinf;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PbcrsReportGsrltrepymtinfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GSRLTREPYMTINF
     *
     * @mbggenerated Thu Apr 11 10:24:17 CST 2019
     */
    int deleteByPrimaryKey(@Param("RltRepymtInfSgmtSeqNo") String RltRepymtInfSgmtSeqNo, @Param("GsRltRepymtInfSeqNo") String GsRltRepymtInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GSRLTREPYMTINF
     *
     * @mbggenerated Thu Apr 11 10:24:17 CST 2019
     */
    int insert(PbcrsReportGsrltrepymtinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GSRLTREPYMTINF
     *
     * @mbggenerated Thu Apr 11 10:24:17 CST 2019
     */
    PbcrsReportGsrltrepymtinf selectByPrimaryKey(@Param("RltRepymtInfSgmtSeqNo") String RltRepymtInfSgmtSeqNo, @Param("GsRltRepymtInfSeqNo") String GsRltRepymtInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GSRLTREPYMTINF
     *
     * @mbggenerated Thu Apr 11 10:24:17 CST 2019
     */
    List<PbcrsReportGsrltrepymtinf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_GSRLTREPYMTINF
     *
     * @mbggenerated Thu Apr 11 10:24:17 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportGsrltrepymtinf record);
    
    List<PbcrsReportGsrltrepymtinf> getByFirstKey(String RltRepymtInfSgmtSeqNo);

	int getKey();

	 int deleteByPrimaryKeyM(@Param("RltRepymtInfSgmtSeqNo") String RltRepymtInfSgmtSeqNo, @Param("GsRltRepymtInfSeqNo") String GsRltRepymtInfSeqNo);
	 int insertM(PbcrsReportGsrltrepymtinf record);
}