package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnacctbsinfsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnacctbsinfsgmtMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENACCTBSINFSGMT
     *
     * @mbggenerated Thu Mar 14 10:19:55 CST 2019
     */
    int deleteByPrimaryKey(String AcctBsInfSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENACCTBSINFSGMT
     *
     * @mbggenerated Thu Mar 14 10:19:55 CST 2019
     */
    int insert(PbcrsReportEnacctbsinfsgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENACCTBSINFSGMT
     *
     * @mbggenerated Thu Mar 14 10:19:55 CST 2019
     */
    PbcrsReportEnacctbsinfsgmt selectByPrimaryKey(String AcctBsInfSgmtSeqNo);
    PbcrsReportEnacctbsinfsgmt selectByKey(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENACCTBSINFSGMT
     *
     * @mbggenerated Thu Mar 14 10:19:55 CST 2019
     */
    List<PbcrsReportEnacctbsinfsgmt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENACCTBSINFSGMT
     *
     * @mbggenerated Thu Mar 14 10:19:55 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnacctbsinfsgmt record);
    
    int getKey();
    
    PbcrsReportEnacctbsinfsgmt selectByEnAcctInfSeqNo(String EnAcctInfSeqNo);
    
    PbcrsReportEnacctbsinfsgmt selectByEnAcctInfMSeqNo(String EnAcctInfSeqNo);
}