package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportTrace;

import java.util.List;

public interface PbcrsReportTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_TRACE
     *
     * @mbggenerated Wed Apr 24 09:25:43 CST 2019
     */
    int deleteByPrimaryKey(Short seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_TRACE
     *
     * @mbggenerated Wed Apr 24 09:25:43 CST 2019
     */
    int insert(PbcrsReportTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_TRACE
     *
     * @mbggenerated Wed Apr 24 09:25:43 CST 2019
     */
    PbcrsReportTrace selectByPrimaryKey(Short seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_TRACE
     *
     * @mbggenerated Wed Apr 24 09:25:43 CST 2019
     */
    List<PbcrsReportTrace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_TRACE
     *
     * @mbggenerated Wed Apr 24 09:25:43 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportTrace record);
}