package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportCashflows2007sgmt;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportCashflows2007sgmtMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CASHFLOWS2007SGMT
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    int deleteByPrimaryKey(String CashFlows2007SgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CASHFLOWS2007SGMT
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    int insert(PbcrsReportCashflows2007sgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CASHFLOWS2007SGMT
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    PbcrsReportCashflows2007sgmt selectByPrimaryKey(String CashFlows2007SgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CASHFLOWS2007SGMT
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    List<PbcrsReportCashflows2007sgmt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CASHFLOWS2007SGMT
     *
     * @mbggenerated Mon Mar 18 10:44:59 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportCashflows2007sgmt record);
    
    int getKey();
    
    PbcrsReportCashflows2007sgmt selectByCashFlowsSeqNo(String CashFlowsSeqNo);
}