package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInctrctidcagsinf;

import java.util.List;
import java.util.Map;

public interface PbcrsReportInctrctidcagsinfMapper extends BaseExternalSpi{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCTRCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String InCtrctIDCagsInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCTRCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportInctrctidcagsinf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCTRCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportInctrctidcagsinf selectByPrimaryKey(String InCtrctIDCagsInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCTRCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportInctrctidcagsinf> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INCTRCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportInctrctidcagsinf record);

	int getKey();

	List<PbcrsReportInctrctidcagsinf> selectByMap(Map<String, Object> paramMap);
}