package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportCtrctbssgmt;

import java.util.List;
import java.util.Map;

public interface PbcrsReportCtrctbssgmtMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_CTRCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String CtrctBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_CTRCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportCtrctbssgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_CTRCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportCtrctbssgmt selectByPrimaryKey(String CtrctBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_CTRCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportCtrctbssgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_CTRCTBSSGMT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportCtrctbssgmt record);

	int getKey();

	int getCount(Map<String, Object> param);

	List<Map<String, Object>> getAllandPage(Map<String, Object> param);

	int deleteByPrimaryKeyM(String CtrctBsSgmtSeqNo);

}