package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInacctidcagsinf;

import java.util.List;
import java.util.Map;

public interface PbcrsReportInacctidcagsinfMapper extends BaseExternalSpi {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INACCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String InAcctIDCagsInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INACCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportInacctidcagsinf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INACCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportInacctidcagsinf selectByPrimaryKey(String InAcctIDCagsInfSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INACCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportInacctidcagsinf> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INACCTIDCAGSINF
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportInacctidcagsinf record);

	int getKey();

	List<PbcrsReportInacctidcagsinf> selectByMap(Map<String, Object> paramMap);
}