package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInsecaccmdfmdsgmt;

import java.util.List;

public interface PbcrsReportInsecaccmdfmdsgmtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSECACCMDFMDSGMT
     *
     * @mbggenerated Tue Mar 26 16:20:32 CST 2019
     */
    int insert(PbcrsReportInsecaccmdfmdsgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSECACCMDFMDSGMT
     *
     * @mbggenerated Tue Mar 26 16:20:32 CST 2019
     */
    List<PbcrsReportInsecaccmdfmdsgmt> selectAll();

	int getKey();
}