package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInsbalshebssgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;


@Repository
public interface PbcrsReportInsbalshebssgmtMapper extends BaseExternalSpi{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHEBSSGMT
	 * @mbggenerated  Tue Apr 09 18:27:38 CST 2019
	 */
	int deleteByPrimaryKey(String InstitutionBSBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHEBSSGMT
	 * @mbggenerated  Tue Apr 09 18:27:38 CST 2019
	 */
	int insert(PbcrsReportInsbalshebssgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHEBSSGMT
	 * @mbggenerated  Tue Apr 09 18:27:38 CST 2019
	 */
	PbcrsReportInsbalshebssgmt selectByPrimaryKey(
			String InstitutionBSBsSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHEBSSGMT
	 * @mbggenerated  Tue Apr 09 18:27:38 CST 2019
	 */
	List<PbcrsReportInsbalshebssgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INSBALSHEBSSGMT
	 * @mbggenerated  Tue Apr 09 18:27:38 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportInsbalshebssgmt record);
	
	int selectAllbyContCount(Map<String,Object> map);
	
	List<Map<String,Object>> selectAllbyContPage(Map<String,Object> map);
	
	int getKey();
	
	
	PbcrsReportInsbalshebssgmt selectByInstitutionBSSeqNo(String InstitutionBSSeqNo);
	
    /**
     * 修改基础段时点为：更新
     * @param param
     * @return
     */
    int updateByKey(Map<String,Object> param);
    int updateByIsDel(Map<String,Object> param);
	
}