package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnctfitginf;

import java.util.List;
import java.util.Map;

public interface PbcrsReportEnctfitginfMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTFITGINF
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    int deleteByPrimaryKey(String EnCtfItgInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTFITGINF
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    int insert(PbcrsReportEnctfitginf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTFITGINF
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    PbcrsReportEnctfitginf selectByPrimaryKey(String EnCtfItgInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTFITGINF
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    List<PbcrsReportEnctfitginf> selectAll();
    
    List<PbcrsReportEnctfitginf> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTFITGINF
     *
     * @mbggenerated Fri Mar 15 08:53:31 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnctfitginf record);
}