package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEncreditlimsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEncreditlimsgmtMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCREDITLIMSGMT
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    int deleteByPrimaryKey(String CreditLimSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCREDITLIMSGMT
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    int insert(PbcrsReportEncreditlimsgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCREDITLIMSGMT
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    PbcrsReportEncreditlimsgmt selectByPrimaryKey(String CreditLimSgmtSeqNo);
    
    PbcrsReportEncreditlimsgmt selectByKey(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCREDITLIMSGMT
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    List<PbcrsReportEncreditlimsgmt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCREDITLIMSGMT
     *
     * @mbggenerated Fri Mar 15 10:38:24 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEncreditlimsgmt record);
    
    int getKey();
    
    PbcrsReportEncreditlimsgmt selectByEnCtrctInfSeqNo(String EnCtrctInfSeqNo);
    
    PbcrsReportEncreditlimsgmt selectByEnCtrctInfMSeqNo(String EnCtrctInfSeqNo);
    
    int update(Map<String,Object> param);
    int getCount(String key);
    
}