package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportCccinf;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportCccinfMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CCCINF
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    int deleteByPrimaryKey(@Param("MotgaCltalCtrctInfSgmtSeqNo") String MotgaCltalCtrctInfSgmtSeqNo, @Param("CccInfSeqNo") String CccInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CCCINF
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    int insert(PbcrsReportCccinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CCCINF
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    PbcrsReportCccinf selectByPrimaryKey(@Param("MotgaCltalCtrctInfSgmtSeqNo") String MotgaCltalCtrctInfSgmtSeqNo, @Param("CccInfSeqNo") String CccInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CCCINF
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    List<PbcrsReportCccinf> selectAll();
    
    List<PbcrsReportCccinf> selectByKey(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CCCINF
     *
     * @mbggenerated Mon Apr 15 19:17:45 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportCccinf record);
    //根据抵质押物流水号查询抵质押物合同信息
	PbcrsReportCccinf getByMotgaCltalCtrctInfSeqNo(@Param("MotgaCltalCtrctInfSeqNo")String MotgaCltalCtrctInfSeqNo);

	List<PbcrsReportCccinf> getByFirstKey(@Param("MotgaCltalCtrctInfSgmtSeqNo")String MotgaCltalCtrctInfSgmtSeqNo,@Param("MotgaCltalCtrctInfType")String MotgaCltalCtrctInfType);
	
	int getKey();
	
	List<PbcrsReportCccinf> selectByMotgaCltalCtrctInfSgmtSeqNo(String MotgaCltalCtrctInfSgmtSeqNo);

	int deleteByPrimaryKeyM(@Param("MotgaCltalCtrctInfSgmtSeqNo") String MotgaCltalCtrctInfSgmtSeqNo, @Param("CccInfSeqNo") String CccInfSeqNo);
	
	int insertM(PbcrsReportCccinf record);

	
	
}