package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnicdnrltpinf;

import java.util.List;
import java.util.Map;

public interface PbcrsReportEnicdnrltpinfMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENICDNRLTPINF
     *
     * @mbggenerated Fri Mar 15 08:56:34 CST 2019
     */
    int deleteByPrimaryKey(String EnIcdnRltpInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENICDNRLTPINF
     *
     * @mbggenerated Fri Mar 15 08:56:34 CST 2019
     */
    int insert(PbcrsReportEnicdnrltpinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENICDNRLTPINF
     *
     * @mbggenerated Fri Mar 15 08:56:34 CST 2019
     */
    PbcrsReportEnicdnrltpinf selectByPrimaryKey(String EnIcdnRltpInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENICDNRLTPINF
     *
     * @mbggenerated Fri Mar 15 08:56:34 CST 2019
     */
    List<PbcrsReportEnicdnrltpinf> selectAll();
    
    List<PbcrsReportEnicdnrltpinf> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENICDNRLTPINF
     *
     * @mbggenerated Fri Mar 15 08:56:34 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnicdnrltpinf record);
}