package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnctrcerrelsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnctrcerrelsgmtMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCERRELSGMT
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    int deleteByPrimaryKey(String CtrctCertRelSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCERRELSGMT
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    int insert(PbcrsReportEnctrcerrelsgmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCERRELSGMT
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    PbcrsReportEnctrcerrelsgmt selectByPrimaryKey(String CtrctCertRelSgmtSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCERRELSGMT
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    List<PbcrsReportEnctrcerrelsgmt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCERRELSGMT
     *
     * @mbggenerated Fri Mar 15 10:00:01 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnctrcerrelsgmt record);
    
    int getKey();
    
    int selectAllbyContCount(Map<String,Object> map);
    
    List<Map<String,Object>> selectAllbyContPage(Map<String,Object> map);
    
    int selectAllbyContCountm(Map<String,Object> map);
    
    List<Map<String,Object>> selectAllbyContPagem(Map<String,Object> map);
    
}