package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportCondition;

import java.util.List;
import java.util.Map;

public interface PbcrsReportConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CONDITION
     *
     * @mbggenerated Thu Sep 12 14:21:18 CST 2019
     */
    int insert(PbcrsReportCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_CONDITION
     *
     * @mbggenerated Thu Sep 12 14:21:18 CST 2019
     */
    List<PbcrsReportCondition> selectAll();
    
    
    List<PbcrsReportCondition> selectStatus3(PbcrsReportCondition record);
    /**
     * 查询当前任务是否执行成功
     * @param uuidMap
     * @return
     */
    int count(Map<String,Object> uuidMap);
    /**
     * 得到报送层表中到机构列表
     */
    List<Map<String,Object>> getOrgInfo(Map<String,Object> params);
    
    List<Map<String,Object>> getOrgInfoBySeqno(Map<String,Object> params);
    /**
     * 根据报文号查询对应的基础表
     * @param sysid
     * @return
     */
	List<Map<String, Object>> getTableInfo(String sysid);
}