package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInsbalshedlt;

import java.util.List;
import java.util.Map;

public interface PbcrsReportInsbalshedltMapper extends BaseExternalSpi{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSBALSHEDLT
     *
     * @mbggenerated Tue Mar 26 14:16:53 CST 2019
     */
    int deleteByPrimaryKey(String InsBalSheDltSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSBALSHEDLT
     *
     * @mbggenerated Tue Mar 26 14:16:53 CST 2019
     */
    int insert(PbcrsReportInsbalshedlt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSBALSHEDLT
     *
     * @mbggenerated Tue Mar 26 14:16:53 CST 2019
     */
    PbcrsReportInsbalshedlt selectByPrimaryKey(String InsBalSheDltSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSBALSHEDLT
     *
     * @mbggenerated Tue Mar 26 14:16:53 CST 2019
     */
    List<PbcrsReportInsbalshedlt> selectAll();
    
    List<PbcrsReportInsbalshedlt> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_INSBALSHEDLT
     *
     * @mbggenerated Tue Mar 26 14:16:53 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportInsbalshedlt record);
}