package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportInidefctinfdlt;

import java.util.List;
import java.util.Map;

public interface PbcrsReportInidefctinfdltMapper extends BaseExternalSpi{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINFDLT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int deleteByPrimaryKey(String InIDEfctInfDltSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINFDLT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int insert(PbcrsReportInidefctinfdlt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINFDLT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	PbcrsReportInidefctinfdlt selectByPrimaryKey(String InIDEfctInfDltSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINFDLT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	List<PbcrsReportInidefctinfdlt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_INIDEFCTINFDLT
	 * @mbggenerated  Fri Mar 15 10:54:59 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportInidefctinfdlt record);

	List<PbcrsReportInidefctinfdlt> selectByMap(Map<String, Object> paramMap);
}