package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnsecacctinf;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnsecacctinfMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTINF
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    int deleteByPrimaryKey(String EnSecAcctInfSeqNo);

    /**
     * This method was generate*d by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTINF
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    int insert(PbcrsReportEnsecacctinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTINF
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    PbcrsReportEnsecacctinf selectByPrimaryKey(String EnSecAcctInfSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTINF
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    List<PbcrsReportEnsecacctinf> selectAll();
    
    List<PbcrsReportEnsecacctinf> selectByMap(Map map);

    int selectByMapCount(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENSECACCTINF
     *
     * @mbggenerated Thu Mar 14 16:52:51 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnsecacctinf record);
    
    
    int getKey();
}