package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnctrctcertrel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportEnctrctcertrelMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTCERTREL
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    int deleteByPrimaryKey(@Param("CtrctCertRelSgmtSeqNo") String CtrctCertRelSgmtSeqNo, @Param("CtrctCertRelSeqNo") String CtrctCertRelSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTCERTREL
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    int insert(PbcrsReportEnctrctcertrel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTCERTREL
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    PbcrsReportEnctrctcertrel selectByPrimaryKey(@Param("CtrctCertRelSgmtSeqNo") String CtrctCertRelSgmtSeqNo, @Param("CtrctCertRelSeqNo") String CtrctCertRelSeqNo);
    
    PbcrsReportEnctrctcertrel selectByKeyByCtrctCertRelSeqNo(@Param("CtrctCertRelSeqNo") String CtrctCertRelSeqNo);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTCERTREL
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    List<PbcrsReportEnctrctcertrel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTCERTREL
     *
     * @mbggenerated Fri Mar 15 10:15:27 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnctrctcertrel record);
    
    int getKey();
    
    List<PbcrsReportEnctrctcertrel> selectByCtrctCertRelSgmtSeqNo(String CtrctCertRelSgmtSeqNo);
}