package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnctrctinfmdfc;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnctrctinfmdfcMapper extends BaseExternalSpi {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFMDFC
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    int deleteByPrimaryKey(String EnCtrctInfMdfcSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFMDFC
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    int insert(PbcrsReportEnctrctinfmdfc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFMDFC
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    PbcrsReportEnctrctinfmdfc selectByPrimaryKey(String EnCtrctInfMdfcSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFMDFC
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    List<PbcrsReportEnctrctinfmdfc> selectAll();
    
    List<PbcrsReportEnctrctinfmdfc> selectByMap(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_ENCTRCTINFMDFC
     *
     * @mbggenerated Fri Mar 15 11:05:23 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportEnctrctinfmdfc record);
    
    int getKey();
}