package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportFbinf;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcrsReportFbinfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_FBINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    int deleteByPrimaryKey(Short Fbinfseqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_FBINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    int insert(PbcrsReportFbinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_FBINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    PbcrsReportFbinf selectByPrimaryKey(Short Fbinfseqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_FBINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    List<PbcrsReportFbinf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCRS_REPORT_FBINF
     *
     * @mbggenerated Wed Apr 17 14:38:02 CST 2019
     */
    int updateByPrimaryKey(PbcrsReportFbinf record);
    int getKey();
}