package com.hkbank.pbcrs.mapper;

import com.hkbank.pbcrs.model.PbcrsReportEnrltrepinfsgmt;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface PbcrsReportEnrltrepinfsgmtMapper extends BaseExternalSpi{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENRLTREPINFSGMT
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	int deleteByPrimaryKey(String RltRepymtInfSgmtSeqNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENRLTREPINFSGMT
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	int insert(PbcrsReportEnrltrepinfsgmt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENRLTREPINFSGMT
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	PbcrsReportEnrltrepinfsgmt selectByPrimaryKey(String RltRepymtInfSgmtSeqNo);
	
	PbcrsReportEnrltrepinfsgmt selectByKey(Map map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENRLTREPINFSGMT
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	List<PbcrsReportEnrltrepinfsgmt> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PBCRS_REPORT_ENRLTREPINFSGMT
	 * @mbggenerated  Thu Mar 14 10:18:17 CST 2019
	 */
	int updateByPrimaryKey(PbcrsReportEnrltrepinfsgmt record);
	
	int getKey();
	
	int selectAllbyContCount(Map<String,Object> map);
	int selectAllbyContCountm(Map<String,Object> map);
	
	List<Map<String,Object>> selectAllbyContPage(Map<String,Object> map);
	List<Map<String,Object>> selectAllbyContPagem(Map<String,Object> map);
}